// Code generated by Databricks SDK Generator. DO NOT EDIT.

package budgetpolicy

type budgetPolicyWire struct {
	PolicyId            *string               `json:"policy_id,omitempty"`
	PolicyName          *string               `json:"policy_name,omitempty"`
	CustomTags          []customPolicyTagWire `json:"custom_tags,omitempty"`
	BindingWorkspaceIds []int64               `json:"binding_workspace_ids,omitempty"`
}

func budgetPolicyToWire(v *BudgetPolicy) *budgetPolicyWire {
	if v == nil {
		return nil
	}
	return &budgetPolicyWire{
		PolicyId:            v.PolicyId,
		PolicyName:          v.PolicyName,
		CustomTags:          convertSlice(v.CustomTags, customPolicyTagToWire),
		BindingWorkspaceIds: v.BindingWorkspaceIds,
	}
}

func budgetPolicyFromWire(w *budgetPolicyWire) *BudgetPolicy {
	if w == nil {
		return nil
	}
	return &BudgetPolicy{
		PolicyId:            w.PolicyId,
		PolicyName:          w.PolicyName,
		CustomTags:          convertSlice(w.CustomTags, customPolicyTagFromWire),
		BindingWorkspaceIds: w.BindingWorkspaceIds,
	}
}

type createBudgetPolicyRequestWire struct {
	RequestId *string           `json:"request_id,omitempty"`
	AccountId *string           `json:"account_id,omitempty"`
	Policy    *budgetPolicyWire `json:"policy,omitempty"`
}

func createBudgetPolicyRequestToWire(v *CreateBudgetPolicyRequest) *createBudgetPolicyRequestWire {
	if v == nil {
		return nil
	}
	return &createBudgetPolicyRequestWire{
		RequestId: v.RequestId,
		AccountId: v.AccountId,
		Policy:    budgetPolicyToWire(v.Policy),
	}
}

func createBudgetPolicyRequestFromWire(w *createBudgetPolicyRequestWire) *CreateBudgetPolicyRequest {
	if w == nil {
		return nil
	}
	return &CreateBudgetPolicyRequest{
		RequestId: w.RequestId,
		AccountId: w.AccountId,
		Policy:    budgetPolicyFromWire(w.Policy),
	}
}

type customPolicyTagWire struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

func customPolicyTagToWire(v *CustomPolicyTag) *customPolicyTagWire {
	if v == nil {
		return nil
	}
	return &customPolicyTagWire{
		Key:   v.Key,
		Value: v.Value,
	}
}

func customPolicyTagFromWire(w *customPolicyTagWire) *CustomPolicyTag {
	if w == nil {
		return nil
	}
	return &CustomPolicyTag{
		Key:   w.Key,
		Value: w.Value,
	}
}

type deleteBudgetPolicyRequestWire struct {
	PolicyId  *string `json:"policy_id,omitempty"`
	AccountId *string `json:"account_id,omitempty"`
}

func deleteBudgetPolicyRequestToWire(v *DeleteBudgetPolicyRequest) *deleteBudgetPolicyRequestWire {
	if v == nil {
		return nil
	}
	return &deleteBudgetPolicyRequestWire{
		PolicyId:  v.PolicyId,
		AccountId: v.AccountId,
	}
}

func deleteBudgetPolicyRequestFromWire(w *deleteBudgetPolicyRequestWire) *DeleteBudgetPolicyRequest {
	if w == nil {
		return nil
	}
	return &DeleteBudgetPolicyRequest{
		PolicyId:  w.PolicyId,
		AccountId: w.AccountId,
	}
}

type filterWire struct {
	PolicyName      *string `json:"policy_name,omitempty"`
	CreatorUserId   *int64  `json:"creator_user_id,omitempty"`
	CreatorUserName *string `json:"creator_user_name,omitempty"`
}

func filterToWire(v *Filter) *filterWire {
	if v == nil {
		return nil
	}
	return &filterWire{
		PolicyName:      v.PolicyName,
		CreatorUserId:   v.CreatorUserId,
		CreatorUserName: v.CreatorUserName,
	}
}

func filterFromWire(w *filterWire) *Filter {
	if w == nil {
		return nil
	}
	return &Filter{
		PolicyName:      w.PolicyName,
		CreatorUserId:   w.CreatorUserId,
		CreatorUserName: w.CreatorUserName,
	}
}

type getBudgetPolicyRequestWire struct {
	PolicyId  *string `json:"policy_id,omitempty"`
	AccountId *string `json:"account_id,omitempty"`
}

func getBudgetPolicyRequestToWire(v *GetBudgetPolicyRequest) *getBudgetPolicyRequestWire {
	if v == nil {
		return nil
	}
	return &getBudgetPolicyRequestWire{
		PolicyId:  v.PolicyId,
		AccountId: v.AccountId,
	}
}

func getBudgetPolicyRequestFromWire(w *getBudgetPolicyRequestWire) *GetBudgetPolicyRequest {
	if w == nil {
		return nil
	}
	return &GetBudgetPolicyRequest{
		PolicyId:  w.PolicyId,
		AccountId: w.AccountId,
	}
}

type limitConfigWire struct {
}

func limitConfigToWire(v *LimitConfig) *limitConfigWire {
	if v == nil {
		return nil
	}
	return &limitConfigWire{}
}

func limitConfigFromWire(w *limitConfigWire) *LimitConfig {
	if w == nil {
		return nil
	}
	return &LimitConfig{}
}

type listBudgetPoliciesRequestWire struct {
	PageSize  *int          `json:"page_size,omitempty"`
	PageToken *string       `json:"page_token,omitempty"`
	FilterBy  *filterWire   `json:"filter_by,omitempty"`
	SortSpec  *sortSpecWire `json:"sort_spec,omitempty"`
	AccountId *string       `json:"account_id,omitempty"`
}

func listBudgetPoliciesRequestToWire(v *ListBudgetPoliciesRequest) *listBudgetPoliciesRequestWire {
	if v == nil {
		return nil
	}
	return &listBudgetPoliciesRequestWire{
		PageSize:  v.PageSize,
		PageToken: v.PageToken,
		FilterBy:  filterToWire(v.FilterBy),
		SortSpec:  sortSpecToWire(v.SortSpec),
		AccountId: v.AccountId,
	}
}

func listBudgetPoliciesRequestFromWire(w *listBudgetPoliciesRequestWire) *ListBudgetPoliciesRequest {
	if w == nil {
		return nil
	}
	return &ListBudgetPoliciesRequest{
		PageSize:  w.PageSize,
		PageToken: w.PageToken,
		FilterBy:  filterFromWire(w.FilterBy),
		SortSpec:  sortSpecFromWire(w.SortSpec),
		AccountId: w.AccountId,
	}
}

type listBudgetPoliciesResponseWire struct {
	Policies          []budgetPolicyWire `json:"policies,omitempty"`
	NextPageToken     *string            `json:"next_page_token,omitempty"`
	PreviousPageToken *string            `json:"previous_page_token,omitempty"`
}

func listBudgetPoliciesResponseToWire(v *ListBudgetPoliciesResponse) *listBudgetPoliciesResponseWire {
	if v == nil {
		return nil
	}
	return &listBudgetPoliciesResponseWire{
		Policies:          convertSlice(v.Policies, budgetPolicyToWire),
		NextPageToken:     v.NextPageToken,
		PreviousPageToken: v.PreviousPageToken,
	}
}

func listBudgetPoliciesResponseFromWire(w *listBudgetPoliciesResponseWire) *ListBudgetPoliciesResponse {
	if w == nil {
		return nil
	}
	return &ListBudgetPoliciesResponse{
		Policies:          convertSlice(w.Policies, budgetPolicyFromWire),
		NextPageToken:     w.NextPageToken,
		PreviousPageToken: w.PreviousPageToken,
	}
}

type sortSpecWire struct {
	Field      SortSpec_Field `json:"field,omitempty"`
	Descending *bool          `json:"descending,omitempty"`
}

func sortSpecToWire(v *SortSpec) *sortSpecWire {
	if v == nil {
		return nil
	}
	return &sortSpecWire{
		Field:      v.Field,
		Descending: v.Descending,
	}
}

func sortSpecFromWire(w *sortSpecWire) *SortSpec {
	if w == nil {
		return nil
	}
	return &SortSpec{
		Field:      w.Field,
		Descending: w.Descending,
	}
}

type updateBudgetPolicyRequestWire struct {
	Policy      *budgetPolicyWire `json:"policy,omitempty"`
	AccountId   *string           `json:"account_id,omitempty"`
	LimitConfig *limitConfigWire  `json:"limit_config,omitempty"`
}

func updateBudgetPolicyRequestToWire(v *UpdateBudgetPolicyRequest) *updateBudgetPolicyRequestWire {
	if v == nil {
		return nil
	}
	return &updateBudgetPolicyRequestWire{
		Policy:      budgetPolicyToWire(v.Policy),
		AccountId:   v.AccountId,
		LimitConfig: limitConfigToWire(v.LimitConfig),
	}
}

func updateBudgetPolicyRequestFromWire(w *updateBudgetPolicyRequestWire) *UpdateBudgetPolicyRequest {
	if w == nil {
		return nil
	}
	return &UpdateBudgetPolicyRequest{
		Policy:      budgetPolicyFromWire(w.Policy),
		AccountId:   w.AccountId,
		LimitConfig: limitConfigFromWire(w.LimitConfig),
	}
}

func convertSlice[T, W any](s []T, conv func(*T) *W) []W {
	if s == nil {
		return nil
	}
	out := make([]W, len(s))
	for i := range s {
		out[i] = *conv(&s[i])
	}
	return out
}
