// Code generated by Databricks SDK Generator. DO NOT EDIT.

package vectorsearch

import (
	"bytes"
	"context"
	"encoding/json"
	"iter"
	"log/slog"
	"net/http"
	"net/url"
	"sync"

	"github.com/databricks/sdk-go/auth"
	"github.com/databricks/sdk-go/core/clientinfo"
	"github.com/databricks/sdk-go/options/call"
	"github.com/databricks/sdk-go/options/client"
	"github.com/databricks/sdk-go/options/internaloptions"
	"github.com/databricks/sdk-go/vectorsearch/internal"
)

type Client struct {
	internalClient

	// extensions is a per-client store for hand-written mixins to attach
	// lazily-built state. Keys should be unexported types private to the
	// mixin, following the context.Value convention, to avoid collisions.
	// The zero value is ready to use; it is safe for concurrent use.
	extensions sync.Map
}

type internalClient struct {
	httpClient  *http.Client
	credentials auth.Credentials
	logger      *slog.Logger
	userAgent   string
	host        string
	workspaceID string
	accountID   string
}

func NewClient(ctx context.Context, opts ...client.Option) (*Client, error) {
	cfg := internaloptions.ClientOptions{}
	for _, opt := range opts {
		if err := opt(&cfg); err != nil {
			return nil, err
		}
	}
	if err := cfg.Resolve(); err != nil {
		return nil, err
	}
	info, err := clientinfo.Default().With(
		internal.ModuleName, internal.Version,
		"auth", cfg.Credentials.Name(),
	)
	if err != nil {
		return nil, err
	}

	return &Client{
		internalClient: internalClient{
			httpClient:  cfg.HTTPClient,
			credentials: cfg.Credentials,
			logger:      cfg.Logger,
			userAgent:   info.String(),
			host:        cfg.Host,
			workspaceID: cfg.WorkspaceID,
			accountID:   cfg.AccountID,
		},
	}, nil
}

// Create a new endpoint.
func (c *internalClient) CreateEndpoint(ctx context.Context, req *CreateEndpointRequest, opts ...call.Option) (*Endpoint, error) {
	body, err := json.Marshal(createEndpointRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/vector-search/endpoints"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *Endpoint

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp endpointWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = endpointFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Create a new index.
func (c *internalClient) CreateVectorIndex(ctx context.Context, req *CreateVectorIndexRequest, opts ...call.Option) (*VectorIndex, error) {
	body, err := json.Marshal(createVectorIndexRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/vector-search/indexes"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *VectorIndex

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp vectorIndexWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = vectorIndexFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Handles the deletion of data from a specified vector index.
func (c *internalClient) DeleteDataVectorIndex(ctx context.Context, req *DeleteDataVectorIndexRequest, opts ...call.Option) (*DeleteDataVectorIndexResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/indexes/")
	pb.singleSegment(*req.Name)
	pb.literal("/delete-data")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "primary_keys", req.PrimaryKeys); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DeleteDataVectorIndexResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp deleteDataVectorIndexResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = deleteDataVectorIndexResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Delete an AI Search endpoint.
func (c *internalClient) DeleteEndpoint(ctx context.Context, req *DeleteEndpointRequest, opts ...call.Option) (*DeleteEndpointResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/endpoints/")
	pb.singleSegment(*req.Name)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DeleteEndpointResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &DeleteEndpointResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Delete an index.
func (c *internalClient) DeleteVectorIndex(ctx context.Context, req *DeleteVectorIndexRequest, opts ...call.Option) (*DeleteVectorIndexResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/indexes/")
	pb.singleSegment(*req.Name)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DeleteVectorIndexResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &DeleteVectorIndexResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Get details for a single AI Search endpoint.
func (c *internalClient) GetEndpoint(ctx context.Context, req *GetEndpointRequest, opts ...call.Option) (*Endpoint, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/endpoints/")
	pb.singleSegment(*req.Name)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *Endpoint

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp endpointWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = endpointFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Get an index.
func (c *internalClient) GetVectorIndex(ctx context.Context, req *GetVectorIndexRequest, opts ...call.Option) (*VectorIndex, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/indexes/")
	pb.singleSegment(*req.Name)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "ensure_reranker_compatible", req.EnsureRerankerCompatible); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *VectorIndex

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp vectorIndexWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = vectorIndexFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// List all AI Search endpoints in the workspace.
func (c *internalClient) ListEndpoints(ctx context.Context, req *ListEndpointsRequest, opts ...call.Option) (*ListEndpointResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/vector-search/endpoints"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "page_token", req.PageToken); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListEndpointResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listEndpointResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = listEndpointResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// ListEndpointsIter returns an iterator that iterates
// over the results of ListEndpoints.
//
// For example:
//
//	for item, err := range c.ListEndpointsIter(ctx, &ListEndpointsRequest{}) {
//	  if err != nil {
//	    return err
//	  }
//	  fmt.Println(item)
//	}
//
// Options opts are passed to each ListEndpoints call
// made by the iterator under the hood.
//
// Callers who need custom pagination logic should use
// ListEndpoints directly.
func (c *internalClient) ListEndpointsIter(ctx context.Context, req *ListEndpointsRequest, opts ...call.Option) iter.Seq2[*Endpoint, error] {
	return func(yield func(*Endpoint, error) bool) {
		// Deep copy the request via JSON round-trip to avoid modifying the original.
		reqBody, err := json.Marshal(req)
		if err != nil {
			yield(nil, err)
			return
		}
		pageReq := ListEndpointsRequest{}
		if err := json.Unmarshal(reqBody, &pageReq); err != nil {
			yield(nil, err)
			return
		}
		for {
			resp, err := c.ListEndpoints(ctx, &pageReq, opts...)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range resp.Endpoints {
				if !yield(&resp.Endpoints[i], nil) {
					return
				}
			}
			if resp.NextPageToken == nil || *resp.NextPageToken == "" {
				return
			}
			pageReq.PageToken = resp.NextPageToken
		}
	}
}

// List all indexes in the given endpoint.
func (c *internalClient) ListVectorIndex(ctx context.Context, req *ListVectorIndexRequest, opts ...call.Option) (*ListVectorIndexResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/vector-search/indexes"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "endpoint_name", req.EndpointName); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "page_token", req.PageToken); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListVectorIndexResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listVectorIndexResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = listVectorIndexResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// ListVectorIndexIter returns an iterator that iterates
// over the results of ListVectorIndex.
//
// For example:
//
//	for item, err := range c.ListVectorIndexIter(ctx, &ListVectorIndexRequest{}) {
//	  if err != nil {
//	    return err
//	  }
//	  fmt.Println(item)
//	}
//
// Options opts are passed to each ListVectorIndex call
// made by the iterator under the hood.
//
// Callers who need custom pagination logic should use
// ListVectorIndex directly.
func (c *internalClient) ListVectorIndexIter(ctx context.Context, req *ListVectorIndexRequest, opts ...call.Option) iter.Seq2[*MiniVectorIndex, error] {
	return func(yield func(*MiniVectorIndex, error) bool) {
		// Deep copy the request via JSON round-trip to avoid modifying the original.
		reqBody, err := json.Marshal(req)
		if err != nil {
			yield(nil, err)
			return
		}
		pageReq := ListVectorIndexRequest{}
		if err := json.Unmarshal(reqBody, &pageReq); err != nil {
			yield(nil, err)
			return
		}
		for {
			resp, err := c.ListVectorIndex(ctx, &pageReq, opts...)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range resp.VectorIndexes {
				if !yield(&resp.VectorIndexes[i], nil) {
					return
				}
			}
			if resp.NextPageToken == nil || *resp.NextPageToken == "" {
				return
			}
			pageReq.PageToken = resp.NextPageToken
		}
	}
}

// Update an endpoint
func (c *internalClient) PatchEndpoint(ctx context.Context, req *PatchEndpointRequest, opts ...call.Option) (*Endpoint, error) {
	body, err := json.Marshal(patchEndpointRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/endpoints/")
	pb.singleSegment(*req.Name)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *Endpoint

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PATCH",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp endpointWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = endpointFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Update the budget policy of an endpoint
func (c *internalClient) PatchEndpointBudgetPolicy(ctx context.Context, req *PatchEndpointBudgetPolicyRequest, opts ...call.Option) (*PatchEndpointBudgetPolicyResponse, error) {
	body, err := json.Marshal(patchEndpointBudgetPolicyRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/endpoints/")
	pb.singleSegment(*req.Name)
	pb.literal("/budget-policy")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *PatchEndpointBudgetPolicyResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PATCH",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp patchEndpointBudgetPolicyResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = patchEndpointBudgetPolicyResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Query the specified vector index.
func (c *internalClient) QueryVectorIndex(ctx context.Context, req *QueryVectorIndexRequest, opts ...call.Option) (*QueryVectorIndexResponse, error) {
	body, err := json.Marshal(queryVectorIndexRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/indexes/")
	pb.singleSegment(*req.Name)
	pb.literal("/query")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *QueryVectorIndexResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp queryVectorIndexResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = queryVectorIndexResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Use `next_page_token` returned from previous `QueryVectorIndex` or
// `QueryVectorIndexNextPage` request to fetch next page of results.
func (c *internalClient) QueryVectorIndexNextPage(ctx context.Context, req *QueryVectorIndexNextPageRequest, opts ...call.Option) (*QueryVectorIndexResponse, error) {
	body, err := json.Marshal(queryVectorIndexNextPageRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/indexes/")
	pb.singleSegment(*req.Name)
	pb.literal("/query-next-page")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *QueryVectorIndexResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp queryVectorIndexResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = queryVectorIndexResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Retrieve user-visible metrics for an endpoint
func (c *internalClient) RetrieveUserVisibleMetrics(ctx context.Context, req *RetrieveUserVisibleMetricsRequest, opts ...call.Option) (*RetrieveUserVisibleMetricsResponse, error) {
	body, err := json.Marshal(retrieveUserVisibleMetricsRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/endpoints/")
	pb.singleSegment(*req.Name)
	pb.literal("/metrics")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *RetrieveUserVisibleMetricsResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp retrieveUserVisibleMetricsResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = retrieveUserVisibleMetricsResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Scan the specified vector index and return the first `num_results` entries
// after the exclusive `primary_key`.
func (c *internalClient) ScanVectorIndex(ctx context.Context, req *ScanVectorIndexRequest, opts ...call.Option) (*ScanVectorIndexResponse, error) {
	body, err := json.Marshal(scanVectorIndexRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/indexes/")
	pb.singleSegment(*req.Name)
	pb.literal("/scan")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ScanVectorIndexResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp scanVectorIndexResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = scanVectorIndexResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Triggers a synchronization process for a specified vector index.
func (c *internalClient) SyncVectorIndex(ctx context.Context, req *SyncVectorIndexRequest, opts ...call.Option) (*SyncVectorIndexResponse, error) {
	body, err := json.Marshal(syncVectorIndexRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/indexes/")
	pb.singleSegment(*req.Name)
	pb.literal("/sync")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *SyncVectorIndexResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &SyncVectorIndexResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Update the custom tags of an endpoint.
func (c *internalClient) UpdateEndpointCustomTags(ctx context.Context, req *UpdateEndpointCustomTagsRequest, opts ...call.Option) (*UpdateEndpointCustomTagsResponse, error) {
	body, err := json.Marshal(updateEndpointCustomTagsRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/endpoints/")
	pb.singleSegment(*req.Name)
	pb.literal("/tags")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *UpdateEndpointCustomTagsResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PATCH",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp updateEndpointCustomTagsResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = updateEndpointCustomTagsResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Handles the upserting of data into a specified vector index.
func (c *internalClient) UpsertDataVectorIndex(ctx context.Context, req *UpsertDataVectorIndexRequest, opts ...call.Option) (*UpsertDataVectorIndexResponse, error) {
	body, err := json.Marshal(upsertDataVectorIndexRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/vector-search/indexes/")
	pb.singleSegment(*req.Name)
	pb.literal("/upsert-data")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *UpsertDataVectorIndexResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp upsertDataVectorIndexResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = upsertDataVectorIndexResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}
