// Code generated by Databricks SDK Generator. DO NOT EDIT.

package secrets

type aclItemWire struct {
	Principal  *string       `json:"principal,omitempty"`
	Permission AclPermission `json:"permission,omitempty"`
}

func aclItemToWire(v *AclItem) *aclItemWire {
	if v == nil {
		return nil
	}
	return &aclItemWire{
		Principal:  v.Principal,
		Permission: v.Permission,
	}
}

func aclItemFromWire(w *aclItemWire) *AclItem {
	if w == nil {
		return nil
	}
	return &AclItem{
		Principal:  w.Principal,
		Permission: w.Permission,
	}
}

type azureKeyVaultSecretScopeMetadataWire struct {
	ResourceId *string `json:"resource_id,omitempty"`
	DnsName    *string `json:"dns_name,omitempty"`
}

func azureKeyVaultSecretScopeMetadataToWire(v *AzureKeyVaultSecretScopeMetadata) *azureKeyVaultSecretScopeMetadataWire {
	if v == nil {
		return nil
	}
	return &azureKeyVaultSecretScopeMetadataWire{
		ResourceId: v.ResourceId,
		DnsName:    v.DnsName,
	}
}

func azureKeyVaultSecretScopeMetadataFromWire(w *azureKeyVaultSecretScopeMetadataWire) *AzureKeyVaultSecretScopeMetadata {
	if w == nil {
		return nil
	}
	return &AzureKeyVaultSecretScopeMetadata{
		ResourceId: w.ResourceId,
		DnsName:    w.DnsName,
	}
}

type createScopeRequestWire struct {
	Scope                  *string                               `json:"scope,omitempty"`
	InitialManagePrincipal *string                               `json:"initial_manage_principal,omitempty"`
	ScopeBackendType       ScopeBackendType                      `json:"scope_backend_type,omitempty"`
	BackendAzureKeyvault   *azureKeyVaultSecretScopeMetadataWire `json:"backend_azure_keyvault,omitempty"`
}

func createScopeRequestToWire(v *CreateScopeRequest) *createScopeRequestWire {
	if v == nil {
		return nil
	}
	return &createScopeRequestWire{
		Scope:                  v.Scope,
		InitialManagePrincipal: v.InitialManagePrincipal,
		ScopeBackendType:       v.ScopeBackendType,
		BackendAzureKeyvault:   azureKeyVaultSecretScopeMetadataToWire(v.BackendAzureKeyvault),
	}
}

func createScopeRequestFromWire(w *createScopeRequestWire) *CreateScopeRequest {
	if w == nil {
		return nil
	}
	return &CreateScopeRequest{
		Scope:                  w.Scope,
		InitialManagePrincipal: w.InitialManagePrincipal,
		ScopeBackendType:       w.ScopeBackendType,
		BackendAzureKeyvault:   azureKeyVaultSecretScopeMetadataFromWire(w.BackendAzureKeyvault),
	}
}

type createScopeResponseWire struct {
}

func createScopeResponseToWire(v *CreateScopeResponse) *createScopeResponseWire {
	if v == nil {
		return nil
	}
	return &createScopeResponseWire{}
}

func createScopeResponseFromWire(w *createScopeResponseWire) *CreateScopeResponse {
	if w == nil {
		return nil
	}
	return &CreateScopeResponse{}
}

type deleteAclRequestWire struct {
	Scope     *string `json:"scope,omitempty"`
	Principal *string `json:"principal,omitempty"`
}

func deleteAclRequestToWire(v *DeleteAclRequest) *deleteAclRequestWire {
	if v == nil {
		return nil
	}
	return &deleteAclRequestWire{
		Scope:     v.Scope,
		Principal: v.Principal,
	}
}

func deleteAclRequestFromWire(w *deleteAclRequestWire) *DeleteAclRequest {
	if w == nil {
		return nil
	}
	return &DeleteAclRequest{
		Scope:     w.Scope,
		Principal: w.Principal,
	}
}

type deleteAclResponseWire struct {
}

func deleteAclResponseToWire(v *DeleteAclResponse) *deleteAclResponseWire {
	if v == nil {
		return nil
	}
	return &deleteAclResponseWire{}
}

func deleteAclResponseFromWire(w *deleteAclResponseWire) *DeleteAclResponse {
	if w == nil {
		return nil
	}
	return &DeleteAclResponse{}
}

type deleteScopeRequestWire struct {
	Scope *string `json:"scope,omitempty"`
}

func deleteScopeRequestToWire(v *DeleteScopeRequest) *deleteScopeRequestWire {
	if v == nil {
		return nil
	}
	return &deleteScopeRequestWire{
		Scope: v.Scope,
	}
}

func deleteScopeRequestFromWire(w *deleteScopeRequestWire) *DeleteScopeRequest {
	if w == nil {
		return nil
	}
	return &DeleteScopeRequest{
		Scope: w.Scope,
	}
}

type deleteScopeResponseWire struct {
}

func deleteScopeResponseToWire(v *DeleteScopeResponse) *deleteScopeResponseWire {
	if v == nil {
		return nil
	}
	return &deleteScopeResponseWire{}
}

func deleteScopeResponseFromWire(w *deleteScopeResponseWire) *DeleteScopeResponse {
	if w == nil {
		return nil
	}
	return &DeleteScopeResponse{}
}

type deleteSecretRequestWire struct {
	Scope *string `json:"scope,omitempty"`
	Key   *string `json:"key,omitempty"`
}

func deleteSecretRequestToWire(v *DeleteSecretRequest) *deleteSecretRequestWire {
	if v == nil {
		return nil
	}
	return &deleteSecretRequestWire{
		Scope: v.Scope,
		Key:   v.Key,
	}
}

func deleteSecretRequestFromWire(w *deleteSecretRequestWire) *DeleteSecretRequest {
	if w == nil {
		return nil
	}
	return &DeleteSecretRequest{
		Scope: w.Scope,
		Key:   w.Key,
	}
}

type deleteSecretResponseWire struct {
}

func deleteSecretResponseToWire(v *DeleteSecretResponse) *deleteSecretResponseWire {
	if v == nil {
		return nil
	}
	return &deleteSecretResponseWire{}
}

func deleteSecretResponseFromWire(w *deleteSecretResponseWire) *DeleteSecretResponse {
	if w == nil {
		return nil
	}
	return &DeleteSecretResponse{}
}

type getAclRequestWire struct {
	Scope     *string `json:"scope,omitempty"`
	Principal *string `json:"principal,omitempty"`
}

func getAclRequestToWire(v *GetAclRequest) *getAclRequestWire {
	if v == nil {
		return nil
	}
	return &getAclRequestWire{
		Scope:     v.Scope,
		Principal: v.Principal,
	}
}

func getAclRequestFromWire(w *getAclRequestWire) *GetAclRequest {
	if w == nil {
		return nil
	}
	return &GetAclRequest{
		Scope:     w.Scope,
		Principal: w.Principal,
	}
}

type getSecretRequestWire struct {
	Scope *string `json:"scope,omitempty"`
	Key   *string `json:"key,omitempty"`
}

func getSecretRequestToWire(v *GetSecretRequest) *getSecretRequestWire {
	if v == nil {
		return nil
	}
	return &getSecretRequestWire{
		Scope: v.Scope,
		Key:   v.Key,
	}
}

func getSecretRequestFromWire(w *getSecretRequestWire) *GetSecretRequest {
	if w == nil {
		return nil
	}
	return &GetSecretRequest{
		Scope: w.Scope,
		Key:   w.Key,
	}
}

type getSecretResponseWire struct {
	Key   *string `json:"key,omitempty"`
	Value []byte  `json:"value,omitempty"`
}

func getSecretResponseToWire(v *GetSecretResponse) *getSecretResponseWire {
	if v == nil {
		return nil
	}
	return &getSecretResponseWire{
		Key:   v.Key,
		Value: v.Value,
	}
}

func getSecretResponseFromWire(w *getSecretResponseWire) *GetSecretResponse {
	if w == nil {
		return nil
	}
	return &GetSecretResponse{
		Key:   w.Key,
		Value: w.Value,
	}
}

type listAclsRequestWire struct {
	Scope *string `json:"scope,omitempty"`
}

func listAclsRequestToWire(v *ListAclsRequest) *listAclsRequestWire {
	if v == nil {
		return nil
	}
	return &listAclsRequestWire{
		Scope: v.Scope,
	}
}

func listAclsRequestFromWire(w *listAclsRequestWire) *ListAclsRequest {
	if w == nil {
		return nil
	}
	return &ListAclsRequest{
		Scope: w.Scope,
	}
}

type listAclsResponseWire struct {
	Items []aclItemWire `json:"items,omitempty"`
}

func listAclsResponseToWire(v *ListAclsResponse) *listAclsResponseWire {
	if v == nil {
		return nil
	}
	return &listAclsResponseWire{
		Items: convertSlice(v.Items, aclItemToWire),
	}
}

func listAclsResponseFromWire(w *listAclsResponseWire) *ListAclsResponse {
	if w == nil {
		return nil
	}
	return &ListAclsResponse{
		Items: convertSlice(w.Items, aclItemFromWire),
	}
}

type listScopesRequestWire struct {
}

func listScopesRequestToWire(v *ListScopesRequest) *listScopesRequestWire {
	if v == nil {
		return nil
	}
	return &listScopesRequestWire{}
}

func listScopesRequestFromWire(w *listScopesRequestWire) *ListScopesRequest {
	if w == nil {
		return nil
	}
	return &ListScopesRequest{}
}

type listScopesResponseWire struct {
	Scopes []secretScopeWire `json:"scopes,omitempty"`
}

func listScopesResponseToWire(v *ListScopesResponse) *listScopesResponseWire {
	if v == nil {
		return nil
	}
	return &listScopesResponseWire{
		Scopes: convertSlice(v.Scopes, secretScopeToWire),
	}
}

func listScopesResponseFromWire(w *listScopesResponseWire) *ListScopesResponse {
	if w == nil {
		return nil
	}
	return &ListScopesResponse{
		Scopes: convertSlice(w.Scopes, secretScopeFromWire),
	}
}

type listSecretsRequestWire struct {
	Scope *string `json:"scope,omitempty"`
}

func listSecretsRequestToWire(v *ListSecretsRequest) *listSecretsRequestWire {
	if v == nil {
		return nil
	}
	return &listSecretsRequestWire{
		Scope: v.Scope,
	}
}

func listSecretsRequestFromWire(w *listSecretsRequestWire) *ListSecretsRequest {
	if w == nil {
		return nil
	}
	return &ListSecretsRequest{
		Scope: w.Scope,
	}
}

type listSecretsResponseWire struct {
	Secrets []secretMetadataWire `json:"secrets,omitempty"`
}

func listSecretsResponseToWire(v *ListSecretsResponse) *listSecretsResponseWire {
	if v == nil {
		return nil
	}
	return &listSecretsResponseWire{
		Secrets: convertSlice(v.Secrets, secretMetadataToWire),
	}
}

func listSecretsResponseFromWire(w *listSecretsResponseWire) *ListSecretsResponse {
	if w == nil {
		return nil
	}
	return &ListSecretsResponse{
		Secrets: convertSlice(w.Secrets, secretMetadataFromWire),
	}
}

type putAclRequestWire struct {
	Scope      *string       `json:"scope,omitempty"`
	Principal  *string       `json:"principal,omitempty"`
	Permission AclPermission `json:"permission,omitempty"`
}

func putAclRequestToWire(v *PutAclRequest) *putAclRequestWire {
	if v == nil {
		return nil
	}
	return &putAclRequestWire{
		Scope:      v.Scope,
		Principal:  v.Principal,
		Permission: v.Permission,
	}
}

func putAclRequestFromWire(w *putAclRequestWire) *PutAclRequest {
	if w == nil {
		return nil
	}
	return &PutAclRequest{
		Scope:      w.Scope,
		Principal:  w.Principal,
		Permission: w.Permission,
	}
}

type putAclResponseWire struct {
}

func putAclResponseToWire(v *PutAclResponse) *putAclResponseWire {
	if v == nil {
		return nil
	}
	return &putAclResponseWire{}
}

func putAclResponseFromWire(w *putAclResponseWire) *PutAclResponse {
	if w == nil {
		return nil
	}
	return &PutAclResponse{}
}

type putSecretRequestWire struct {
	Scope       *string `json:"scope,omitempty"`
	Key         *string `json:"key,omitempty"`
	StringValue *string `json:"string_value,omitempty"`
	BytesValue  []byte  `json:"bytes_value,omitempty"`
}

func putSecretRequestToWire(v *PutSecretRequest) *putSecretRequestWire {
	if v == nil {
		return nil
	}
	return &putSecretRequestWire{
		Scope:       v.Scope,
		Key:         v.Key,
		StringValue: v.StringValue,
		BytesValue:  v.BytesValue,
	}
}

func putSecretRequestFromWire(w *putSecretRequestWire) *PutSecretRequest {
	if w == nil {
		return nil
	}
	return &PutSecretRequest{
		Scope:       w.Scope,
		Key:         w.Key,
		StringValue: w.StringValue,
		BytesValue:  w.BytesValue,
	}
}

type putSecretResponseWire struct {
}

func putSecretResponseToWire(v *PutSecretResponse) *putSecretResponseWire {
	if v == nil {
		return nil
	}
	return &putSecretResponseWire{}
}

func putSecretResponseFromWire(w *putSecretResponseWire) *PutSecretResponse {
	if w == nil {
		return nil
	}
	return &PutSecretResponse{}
}

type secretMetadataWire struct {
	Key                  *string `json:"key,omitempty"`
	LastUpdatedTimestamp *int64  `json:"last_updated_timestamp,omitempty"`
}

func secretMetadataToWire(v *SecretMetadata) *secretMetadataWire {
	if v == nil {
		return nil
	}
	return &secretMetadataWire{
		Key:                  v.Key,
		LastUpdatedTimestamp: v.LastUpdatedTimestamp,
	}
}

func secretMetadataFromWire(w *secretMetadataWire) *SecretMetadata {
	if w == nil {
		return nil
	}
	return &SecretMetadata{
		Key:                  w.Key,
		LastUpdatedTimestamp: w.LastUpdatedTimestamp,
	}
}

type secretScopeWire struct {
	Name             *string                               `json:"name,omitempty"`
	BackendType      ScopeBackendType                      `json:"backend_type,omitempty"`
	KeyvaultMetadata *azureKeyVaultSecretScopeMetadataWire `json:"keyvault_metadata,omitempty"`
}

func secretScopeToWire(v *SecretScope) *secretScopeWire {
	if v == nil {
		return nil
	}
	return &secretScopeWire{
		Name:             v.Name,
		BackendType:      v.BackendType,
		KeyvaultMetadata: azureKeyVaultSecretScopeMetadataToWire(v.KeyvaultMetadata),
	}
}

func secretScopeFromWire(w *secretScopeWire) *SecretScope {
	if w == nil {
		return nil
	}
	return &SecretScope{
		Name:             w.Name,
		BackendType:      w.BackendType,
		KeyvaultMetadata: azureKeyVaultSecretScopeMetadataFromWire(w.KeyvaultMetadata),
	}
}

func convertSlice[T, W any](s []T, conv func(*T) *W) []W {
	if s == nil {
		return nil
	}
	out := make([]W, len(s))
	for i := range s {
		out[i] = *conv(&s[i])
	}
	return out
}
