// Code generated by Databricks SDK Generator. DO NOT EDIT.

package tokens

type createTokenRequestWire struct {
	LifetimeSeconds  *int64   `json:"lifetime_seconds,omitempty"`
	Comment          *string  `json:"comment,omitempty"`
	Scopes           []string `json:"scopes,omitempty"`
	AutoscopeEnabled *bool    `json:"autoscope_enabled,omitempty"`
}

func createTokenRequestToWire(v *CreateTokenRequest) *createTokenRequestWire {
	if v == nil {
		return nil
	}
	return &createTokenRequestWire{
		LifetimeSeconds:  v.LifetimeSeconds,
		Comment:          v.Comment,
		Scopes:           v.Scopes,
		AutoscopeEnabled: v.AutoscopeEnabled,
	}
}

func createTokenRequestFromWire(w *createTokenRequestWire) *CreateTokenRequest {
	if w == nil {
		return nil
	}
	return &CreateTokenRequest{
		LifetimeSeconds:  w.LifetimeSeconds,
		Comment:          w.Comment,
		Scopes:           w.Scopes,
		AutoscopeEnabled: w.AutoscopeEnabled,
	}
}

type createTokenResponseWire struct {
	TokenValue *string              `json:"token_value,omitempty"`
	TokenInfo  *publicTokenInfoWire `json:"token_info,omitempty"`
}

func createTokenResponseToWire(v *CreateTokenResponse) *createTokenResponseWire {
	if v == nil {
		return nil
	}
	return &createTokenResponseWire{
		TokenValue: v.TokenValue,
		TokenInfo:  publicTokenInfoToWire(v.TokenInfo),
	}
}

func createTokenResponseFromWire(w *createTokenResponseWire) *CreateTokenResponse {
	if w == nil {
		return nil
	}
	return &CreateTokenResponse{
		TokenValue: w.TokenValue,
		TokenInfo:  publicTokenInfoFromWire(w.TokenInfo),
	}
}

type listTokensRequestWire struct {
}

func listTokensRequestToWire(v *ListTokensRequest) *listTokensRequestWire {
	if v == nil {
		return nil
	}
	return &listTokensRequestWire{}
}

func listTokensRequestFromWire(w *listTokensRequestWire) *ListTokensRequest {
	if w == nil {
		return nil
	}
	return &ListTokensRequest{}
}

type listTokensResponseWire struct {
	TokenInfos []publicTokenInfoWire `json:"token_infos,omitempty"`
}

func listTokensResponseToWire(v *ListTokensResponse) *listTokensResponseWire {
	if v == nil {
		return nil
	}
	return &listTokensResponseWire{
		TokenInfos: convertSlice(v.TokenInfos, publicTokenInfoToWire),
	}
}

func listTokensResponseFromWire(w *listTokensResponseWire) *ListTokensResponse {
	if w == nil {
		return nil
	}
	return &ListTokensResponse{
		TokenInfos: convertSlice(w.TokenInfos, publicTokenInfoFromWire),
	}
}

type publicTokenInfoWire struct {
	TokenId        *string        `json:"token_id,omitempty"`
	CreationTime   *int64         `json:"creation_time,omitempty"`
	ExpiryTime     *int64         `json:"expiry_time,omitempty"`
	Comment        *string        `json:"comment,omitempty"`
	Scopes         []string       `json:"scopes,omitempty"`
	AutoscopeState AutoscopeState `json:"autoscope_state,omitempty"`
	InferredScopes []string       `json:"inferred_scopes,omitempty"`
	BackfillScopes []string       `json:"backfill_scopes,omitempty"`
}

func publicTokenInfoToWire(v *PublicTokenInfo) *publicTokenInfoWire {
	if v == nil {
		return nil
	}
	return &publicTokenInfoWire{
		TokenId:        v.TokenId,
		CreationTime:   v.CreationTime,
		ExpiryTime:     v.ExpiryTime,
		Comment:        v.Comment,
		Scopes:         v.Scopes,
		AutoscopeState: v.AutoscopeState,
		InferredScopes: v.InferredScopes,
		BackfillScopes: v.BackfillScopes,
	}
}

func publicTokenInfoFromWire(w *publicTokenInfoWire) *PublicTokenInfo {
	if w == nil {
		return nil
	}
	return &PublicTokenInfo{
		TokenId:        w.TokenId,
		CreationTime:   w.CreationTime,
		ExpiryTime:     w.ExpiryTime,
		Comment:        w.Comment,
		Scopes:         w.Scopes,
		AutoscopeState: w.AutoscopeState,
		InferredScopes: w.InferredScopes,
		BackfillScopes: w.BackfillScopes,
	}
}

type revokeTokenRequestWire struct {
	TokenId *string `json:"token_id,omitempty"`
}

func revokeTokenRequestToWire(v *RevokeTokenRequest) *revokeTokenRequestWire {
	if v == nil {
		return nil
	}
	return &revokeTokenRequestWire{
		TokenId: v.TokenId,
	}
}

func revokeTokenRequestFromWire(w *revokeTokenRequestWire) *RevokeTokenRequest {
	if w == nil {
		return nil
	}
	return &RevokeTokenRequest{
		TokenId: w.TokenId,
	}
}

type revokeTokenResponseWire struct {
}

func revokeTokenResponseToWire(v *RevokeTokenResponse) *revokeTokenResponseWire {
	if v == nil {
		return nil
	}
	return &revokeTokenResponseWire{}
}

func revokeTokenResponseFromWire(w *revokeTokenResponseWire) *RevokeTokenResponse {
	if w == nil {
		return nil
	}
	return &RevokeTokenResponse{}
}

type updateTokenRequestWire struct {
	TokenId    *string              `json:"token_id,omitempty"`
	Token      *publicTokenInfoWire `json:"token,omitempty"`
	UpdateMask *string              `json:"update_mask,omitempty"`
}

func updateTokenRequestToWire(v *UpdateTokenRequest) *updateTokenRequestWire {
	if v == nil {
		return nil
	}
	return &updateTokenRequestWire{
		TokenId:    v.TokenId,
		Token:      publicTokenInfoToWire(v.Token),
		UpdateMask: v.UpdateMask,
	}
}

func updateTokenRequestFromWire(w *updateTokenRequestWire) *UpdateTokenRequest {
	if w == nil {
		return nil
	}
	return &UpdateTokenRequest{
		TokenId:    w.TokenId,
		Token:      publicTokenInfoFromWire(w.Token),
		UpdateMask: w.UpdateMask,
	}
}

type updateTokenResponseWire struct {
}

func updateTokenResponseToWire(v *UpdateTokenResponse) *updateTokenResponseWire {
	if v == nil {
		return nil
	}
	return &updateTokenResponseWire{}
}

func updateTokenResponseFromWire(w *updateTokenResponseWire) *UpdateTokenResponse {
	if w == nil {
		return nil
	}
	return &UpdateTokenResponse{}
}

func convertSlice[T, W any](s []T, conv func(*T) *W) []W {
	if s == nil {
		return nil
	}
	out := make([]W, len(s))
	for i := range s {
		out[i] = *conv(&s[i])
	}
	return out
}
