// Code generated by Databricks SDK Generator. DO NOT EDIT.

package schemas

import (
	"bytes"
	"context"
	"encoding/json"
	"iter"
	"log/slog"
	"net/http"
	"net/url"
	"sync"

	"github.com/databricks/sdk-go/auth"
	"github.com/databricks/sdk-go/core/clientinfo"
	"github.com/databricks/sdk-go/options/call"
	"github.com/databricks/sdk-go/options/client"
	"github.com/databricks/sdk-go/options/internaloptions"
	"github.com/databricks/sdk-go/uc/schemas/internal"
)

type Client struct {
	internalClient

	// extensions is a per-client store for hand-written mixins to attach
	// lazily-built state. Keys should be unexported types private to the
	// mixin, following the context.Value convention, to avoid collisions.
	// The zero value is ready to use; it is safe for concurrent use.
	extensions sync.Map
}

type internalClient struct {
	httpClient  *http.Client
	credentials auth.Credentials
	logger      *slog.Logger
	userAgent   func() (string, error)
	host        string
	workspaceID string
	accountID   string
}

func NewClient(ctx context.Context, opts ...client.Option) (*Client, error) {
	cfg := internaloptions.ClientOptions{}
	for _, opt := range opts {
		if err := opt(&cfg); err != nil {
			return nil, err
		}
	}
	if err := cfg.Resolve(); err != nil {
		return nil, err
	}
	userAgent := func() (string, error) {
		info, err := clientinfo.Default().With(
			internal.ModuleName, internal.Version,
			"auth", cfg.Credentials.Name(),
		)
		if err != nil {
			return "", err
		}
		return info.String(), nil
	}

	return &Client{
		internalClient: internalClient{
			httpClient:  cfg.HTTPClient,
			credentials: cfg.Credentials,
			logger:      cfg.Logger,
			userAgent:   userAgent,
			host:        cfg.Host,
			workspaceID: cfg.WorkspaceID,
			accountID:   cfg.AccountID,
		},
	}, nil
}

// Creates a new schema for catalog in the Metastore. The caller must be a
// metastore admin, or have the **CREATE_SCHEMA** privilege in the parent
// catalog.
func (c *internalClient) CreateSchema(ctx context.Context, req CreateSchemaRequest, opts ...call.Option) (*SchemaInfo, error) {
	wireReq, err := createSchemaRequestToWire(&req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.1/unity-catalog/schemas"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *SchemaInfo

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp schemaInfoWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = schemaInfoFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Deletes the specified schema from the parent catalog. The caller must be the
// owner of the schema or an owner of the parent catalog.
func (c *internalClient) DeleteSchema(ctx context.Context, req DeleteSchemaRequest, opts ...call.Option) (*DeleteSchemaResponse, error) {
	wireReq, err := deleteSchemaRequestToWire(&req)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.1/unity-catalog/schemas/")
	if req.FullNameArg == nil {
		pb.singleSegment("")
	} else {
		pb.singleSegment(*req.FullNameArg)
	}
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "force", wireReq.Force); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DeleteSchemaResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &DeleteSchemaResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Gets the specified schema within the metastore. The caller must be a
// metastore admin, the owner of the schema, or a user that has the
// **USE_SCHEMA** privilege on the schema.
func (c *internalClient) GetSchema(ctx context.Context, req GetSchemaRequest, opts ...call.Option) (*SchemaInfo, error) {
	wireReq, err := getSchemaRequestToWire(&req)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.1/unity-catalog/schemas/")
	if req.FullNameArg == nil {
		pb.singleSegment("")
	} else {
		pb.singleSegment(*req.FullNameArg)
	}
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "include_browse", wireReq.IncludeBrowse); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *SchemaInfo

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp schemaInfoWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = schemaInfoFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Gets an array of schemas for a catalog in the metastore. If the caller is the
// metastore admin or the owner of the parent catalog, all schemas for the
// catalog will be retrieved. Otherwise, only schemas owned by the caller (or
// for which the caller has the **USE_SCHEMA** privilege) will be retrieved.
// There is no guarantee of a specific ordering of the elements in the array.
//
// NOTE: we recommend using max_results=0 to use the paginated version of this
// API. Unpaginated calls will be deprecated soon.
//
// PAGINATION BEHAVIOR: When using pagination (max_results >= 0), a page may
// contain zero results while still providing a next_page_token. Clients must
// continue reading pages until next_page_token is absent, which is the only
// indication that the end of results has been reached.
func (c *internalClient) ListSchemas(ctx context.Context, req ListSchemasRequest, opts ...call.Option) (*ListSchemasResponse, error) {
	wireReq, err := listSchemasRequestToWire(&req)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.1/unity-catalog/schemas"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "catalog_name", wireReq.CatalogName); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "max_results", wireReq.MaxResults); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "page_token", wireReq.PageToken); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "include_browse", wireReq.IncludeBrowse); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListSchemasResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listSchemasResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = listSchemasResponseFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// ListSchemasIter returns an iterator that iterates
// over the results of ListSchemas.
//
// For example:
//
//	for item, err := range c.ListSchemasIter(ctx, ListSchemasRequest{}) {
//	  if err != nil {
//	    return err
//	  }
//	  fmt.Println(item)
//	}
//
// Options opts are passed to each ListSchemas call
// made by the iterator under the hood.
//
// Callers who need custom pagination logic should use
// ListSchemas directly.
func (c *internalClient) ListSchemasIter(ctx context.Context, req ListSchemasRequest, opts ...call.Option) iter.Seq2[*SchemaInfo, error] {
	return func(yield func(*SchemaInfo, error) bool) {
		// Keep pagination state local to this traversal so reusing the iterator starts
		// from the original request. Reference-bearing fields remain shared and read-only.
		pageReq := req
		for {
			resp, err := c.ListSchemas(ctx, pageReq, opts...)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range resp.Schemas {
				if !yield(&resp.Schemas[i], nil) {
					return
				}
			}
			if resp.NextPageToken == nil || *resp.NextPageToken == "" {
				return
			}
			pageReq.PageToken = resp.NextPageToken
		}
	}
}

// Updates a schema for a catalog. The caller must be the owner of the schema or
// a metastore admin. If the caller is a metastore admin, only the __owner__
// field can be changed in the update. If the __name__ field must be updated,
// the caller must be a metastore admin or have the **CREATE_SCHEMA** privilege
// on the parent catalog.
func (c *internalClient) UpdateSchema(ctx context.Context, req UpdateSchemaRequest, opts ...call.Option) (*SchemaInfo, error) {
	wireReq, err := updateSchemaRequestToWire(&req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.1/unity-catalog/schemas/")
	if req.FullNameArg == nil {
		pb.singleSegment("")
	} else {
		pb.singleSegment(*req.FullNameArg)
	}
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *SchemaInfo

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PATCH",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp schemaInfoWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = schemaInfoFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}
