// Code generated by Databricks SDK Generator. DO NOT EDIT.

package schemas

import (
	"fmt"
)

type createSchemaRequestWire struct {
	Name                                *string                                  `json:"name,omitempty"`
	CatalogName                         *string                                  `json:"catalog_name,omitempty"`
	Owner                               *string                                  `json:"owner,omitempty"`
	Comment                             *string                                  `json:"comment,omitempty"`
	StorageRoot                         *string                                  `json:"storage_root,omitempty"`
	EnablePredictiveOptimization        *string                                  `json:"enable_predictive_optimization,omitempty"`
	MetastoreId                         *string                                  `json:"metastore_id,omitempty"`
	FullName                            *string                                  `json:"full_name,omitempty"`
	CreatedAt                           *int64                                   `json:"created_at,omitempty"`
	CreatedBy                           *string                                  `json:"created_by,omitempty"`
	UpdatedAt                           *int64                                   `json:"updated_at,omitempty"`
	UpdatedBy                           *string                                  `json:"updated_by,omitempty"`
	CatalogType                         CatalogType                              `json:"catalog_type,omitempty"`
	StorageLocation                     *string                                  `json:"storage_location,omitempty"`
	EffectivePredictiveOptimizationFlag *effectivePredictiveOptimizationFlagWire `json:"effective_predictive_optimization_flag,omitempty"`
	SchemaId                            *string                                  `json:"schema_id,omitempty"`
	BrowseOnly                          *bool                                    `json:"browse_only,omitempty"`
	CustomMaxRetentionHours             *int64                                   `json:"custom_max_retention_hours,omitempty"`
	Properties                          map[string]string                        `json:"properties,omitempty"`
	Options                             map[string]string                        `json:"options,omitempty"`
}

func createSchemaRequestToWire(v *CreateSchemaRequest) (*createSchemaRequestWire, error) {
	if v == nil {
		return nil, nil
	}
	effectivePredictiveOptimizationFlagWireValue, err := effectivePredictiveOptimizationFlagToWire(v.EffectivePredictiveOptimizationFlag)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "CreateSchemaRequest.EffectivePredictiveOptimizationFlag", err)
	}
	return &createSchemaRequestWire{
		Name:                                v.Name,
		CatalogName:                         v.CatalogName,
		Owner:                               v.Owner,
		Comment:                             v.Comment,
		StorageRoot:                         v.StorageRoot,
		EnablePredictiveOptimization:        v.EnablePredictiveOptimization,
		MetastoreId:                         v.MetastoreId,
		FullName:                            v.FullName,
		CreatedAt:                           v.CreatedAt,
		CreatedBy:                           v.CreatedBy,
		UpdatedAt:                           v.UpdatedAt,
		UpdatedBy:                           v.UpdatedBy,
		CatalogType:                         v.CatalogType,
		StorageLocation:                     v.StorageLocation,
		EffectivePredictiveOptimizationFlag: effectivePredictiveOptimizationFlagWireValue,
		SchemaId:                            v.SchemaId,
		BrowseOnly:                          v.BrowseOnly,
		CustomMaxRetentionHours:             v.CustomMaxRetentionHours,
		Properties:                          v.Properties,
		Options:                             v.Options,
	}, nil
}

type deleteSchemaRequestWire struct {
	FullNameArg *string `json:"full_name_arg,omitempty"`
	Force       *bool   `json:"force,omitempty"`
}

func deleteSchemaRequestToWire(v *DeleteSchemaRequest) (*deleteSchemaRequestWire, error) {
	if v == nil {
		return nil, nil
	}
	return &deleteSchemaRequestWire{
		FullNameArg: v.FullNameArg,
		Force:       v.Force,
	}, nil
}

type effectivePredictiveOptimizationFlagWire struct {
	Value             *string `json:"value,omitempty"`
	InheritedFromType *string `json:"inherited_from_type,omitempty"`
	InheritedFromName *string `json:"inherited_from_name,omitempty"`
}

func effectivePredictiveOptimizationFlagToWire(v *EffectivePredictiveOptimizationFlag) (*effectivePredictiveOptimizationFlagWire, error) {
	if v == nil {
		return nil, nil
	}
	return &effectivePredictiveOptimizationFlagWire{
		Value:             v.Value,
		InheritedFromType: v.InheritedFromType,
		InheritedFromName: v.InheritedFromName,
	}, nil
}

func effectivePredictiveOptimizationFlagFromWire(w *effectivePredictiveOptimizationFlagWire) (*EffectivePredictiveOptimizationFlag, error) {
	if w == nil {
		return nil, nil
	}
	return &EffectivePredictiveOptimizationFlag{
		Value:             w.Value,
		InheritedFromType: w.InheritedFromType,
		InheritedFromName: w.InheritedFromName,
	}, nil
}

type getSchemaRequestWire struct {
	FullNameArg   *string `json:"full_name_arg,omitempty"`
	IncludeBrowse *bool   `json:"include_browse,omitempty"`
}

func getSchemaRequestToWire(v *GetSchemaRequest) (*getSchemaRequestWire, error) {
	if v == nil {
		return nil, nil
	}
	return &getSchemaRequestWire{
		FullNameArg:   v.FullNameArg,
		IncludeBrowse: v.IncludeBrowse,
	}, nil
}

type listSchemasRequestWire struct {
	CatalogName   *string `json:"catalog_name,omitempty"`
	MaxResults    *int    `json:"max_results,omitempty"`
	PageToken     *string `json:"page_token,omitempty"`
	IncludeBrowse *bool   `json:"include_browse,omitempty"`
}

func listSchemasRequestToWire(v *ListSchemasRequest) (*listSchemasRequestWire, error) {
	if v == nil {
		return nil, nil
	}
	return &listSchemasRequestWire{
		CatalogName:   v.CatalogName,
		MaxResults:    v.MaxResults,
		PageToken:     v.PageToken,
		IncludeBrowse: v.IncludeBrowse,
	}, nil
}

type listSchemasResponseWire struct {
	Schemas       []schemaInfoWire `json:"schemas,omitempty"`
	NextPageToken *string          `json:"next_page_token,omitempty"`
}

func listSchemasResponseFromWire(w *listSchemasResponseWire) (*ListSchemasResponse, error) {
	if w == nil {
		return nil, nil
	}
	schemasPublicValue, err := convertSlice(w.Schemas, schemaInfoFromWire)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "ListSchemasResponse.Schemas", err)
	}
	return &ListSchemasResponse{
		Schemas:       schemasPublicValue,
		NextPageToken: w.NextPageToken,
	}, nil
}

type schemaInfoWire struct {
	Name                                *string                                  `json:"name,omitempty"`
	CatalogName                         *string                                  `json:"catalog_name,omitempty"`
	Owner                               *string                                  `json:"owner,omitempty"`
	Comment                             *string                                  `json:"comment,omitempty"`
	StorageRoot                         *string                                  `json:"storage_root,omitempty"`
	EnablePredictiveOptimization        *string                                  `json:"enable_predictive_optimization,omitempty"`
	MetastoreId                         *string                                  `json:"metastore_id,omitempty"`
	FullName                            *string                                  `json:"full_name,omitempty"`
	CreatedAt                           *int64                                   `json:"created_at,omitempty"`
	CreatedBy                           *string                                  `json:"created_by,omitempty"`
	UpdatedAt                           *int64                                   `json:"updated_at,omitempty"`
	UpdatedBy                           *string                                  `json:"updated_by,omitempty"`
	CatalogType                         CatalogType                              `json:"catalog_type,omitempty"`
	StorageLocation                     *string                                  `json:"storage_location,omitempty"`
	EffectivePredictiveOptimizationFlag *effectivePredictiveOptimizationFlagWire `json:"effective_predictive_optimization_flag,omitempty"`
	SchemaId                            *string                                  `json:"schema_id,omitempty"`
	BrowseOnly                          *bool                                    `json:"browse_only,omitempty"`
	CustomMaxRetentionHours             *int64                                   `json:"custom_max_retention_hours,omitempty"`
	Properties                          map[string]string                        `json:"properties,omitempty"`
	Options                             map[string]string                        `json:"options,omitempty"`
}

func schemaInfoFromWire(w *schemaInfoWire) (*SchemaInfo, error) {
	if w == nil {
		return nil, nil
	}
	effectivePredictiveOptimizationFlagPublicValue, err := effectivePredictiveOptimizationFlagFromWire(w.EffectivePredictiveOptimizationFlag)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "SchemaInfo.EffectivePredictiveOptimizationFlag", err)
	}
	return &SchemaInfo{
		Name:                                w.Name,
		CatalogName:                         w.CatalogName,
		Owner:                               w.Owner,
		Comment:                             w.Comment,
		StorageRoot:                         w.StorageRoot,
		EnablePredictiveOptimization:        w.EnablePredictiveOptimization,
		MetastoreId:                         w.MetastoreId,
		FullName:                            w.FullName,
		CreatedAt:                           w.CreatedAt,
		CreatedBy:                           w.CreatedBy,
		UpdatedAt:                           w.UpdatedAt,
		UpdatedBy:                           w.UpdatedBy,
		CatalogType:                         w.CatalogType,
		StorageLocation:                     w.StorageLocation,
		EffectivePredictiveOptimizationFlag: effectivePredictiveOptimizationFlagPublicValue,
		SchemaId:                            w.SchemaId,
		BrowseOnly:                          w.BrowseOnly,
		CustomMaxRetentionHours:             w.CustomMaxRetentionHours,
		Properties:                          w.Properties,
		Options:                             w.Options,
	}, nil
}

type updateSchemaRequestWire struct {
	FullNameArg                         *string                                  `json:"full_name_arg,omitempty"`
	NewName                             *string                                  `json:"new_name,omitempty"`
	Name                                *string                                  `json:"name,omitempty"`
	CatalogName                         *string                                  `json:"catalog_name,omitempty"`
	Owner                               *string                                  `json:"owner,omitempty"`
	Comment                             *string                                  `json:"comment,omitempty"`
	StorageRoot                         *string                                  `json:"storage_root,omitempty"`
	EnablePredictiveOptimization        *string                                  `json:"enable_predictive_optimization,omitempty"`
	MetastoreId                         *string                                  `json:"metastore_id,omitempty"`
	FullName                            *string                                  `json:"full_name,omitempty"`
	CreatedAt                           *int64                                   `json:"created_at,omitempty"`
	CreatedBy                           *string                                  `json:"created_by,omitempty"`
	UpdatedAt                           *int64                                   `json:"updated_at,omitempty"`
	UpdatedBy                           *string                                  `json:"updated_by,omitempty"`
	CatalogType                         CatalogType                              `json:"catalog_type,omitempty"`
	StorageLocation                     *string                                  `json:"storage_location,omitempty"`
	EffectivePredictiveOptimizationFlag *effectivePredictiveOptimizationFlagWire `json:"effective_predictive_optimization_flag,omitempty"`
	SchemaId                            *string                                  `json:"schema_id,omitempty"`
	BrowseOnly                          *bool                                    `json:"browse_only,omitempty"`
	CustomMaxRetentionHours             *int64                                   `json:"custom_max_retention_hours,omitempty"`
	Properties                          map[string]string                        `json:"properties,omitempty"`
	Options                             map[string]string                        `json:"options,omitempty"`
}

func updateSchemaRequestToWire(v *UpdateSchemaRequest) (*updateSchemaRequestWire, error) {
	if v == nil {
		return nil, nil
	}
	effectivePredictiveOptimizationFlagWireValue, err := effectivePredictiveOptimizationFlagToWire(v.EffectivePredictiveOptimizationFlag)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "UpdateSchemaRequest.EffectivePredictiveOptimizationFlag", err)
	}
	return &updateSchemaRequestWire{
		FullNameArg:                         v.FullNameArg,
		NewName:                             v.NewName,
		Name:                                v.Name,
		CatalogName:                         v.CatalogName,
		Owner:                               v.Owner,
		Comment:                             v.Comment,
		StorageRoot:                         v.StorageRoot,
		EnablePredictiveOptimization:        v.EnablePredictiveOptimization,
		MetastoreId:                         v.MetastoreId,
		FullName:                            v.FullName,
		CreatedAt:                           v.CreatedAt,
		CreatedBy:                           v.CreatedBy,
		UpdatedAt:                           v.UpdatedAt,
		UpdatedBy:                           v.UpdatedBy,
		CatalogType:                         v.CatalogType,
		StorageLocation:                     v.StorageLocation,
		EffectivePredictiveOptimizationFlag: effectivePredictiveOptimizationFlagWireValue,
		SchemaId:                            v.SchemaId,
		BrowseOnly:                          v.BrowseOnly,
		CustomMaxRetentionHours:             v.CustomMaxRetentionHours,
		Properties:                          v.Properties,
		Options:                             v.Options,
	}, nil
}

func convertSlice[T, W any](s []T, conv func(*T) (*W, error)) ([]W, error) {
	if s == nil {
		return nil, nil
	}
	out := make([]W, len(s))
	for i := range s {
		converted, err := conv(&s[i])
		if err != nil {
			return nil, fmt.Errorf("element %d: %w", i, err)
		}
		out[i] = *converted
	}
	return out, nil
}
