// Code generated by Databricks SDK Generator. DO NOT EDIT.

package oauth

type createCustomOAuthAppIntegrationRequestWire struct {
	AccountId            *string                `json:"account_id,omitempty"`
	RedirectUrls         []string               `json:"redirect_urls,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	Confidential         *bool                  `json:"confidential,omitempty"`
	TokenAccessPolicy    *tokenAccessPolicyWire `json:"token_access_policy,omitempty"`
	Scopes               []string               `json:"scopes,omitempty"`
	UserAuthorizedScopes []string               `json:"user_authorized_scopes,omitempty"`
}

func createCustomOAuthAppIntegrationRequestToWire(v *CreateCustomOAuthAppIntegrationRequest) *createCustomOAuthAppIntegrationRequestWire {
	if v == nil {
		return nil
	}
	return &createCustomOAuthAppIntegrationRequestWire{
		AccountId:            v.AccountId,
		RedirectUrls:         v.RedirectUrls,
		Name:                 v.Name,
		Confidential:         v.Confidential,
		TokenAccessPolicy:    tokenAccessPolicyToWire(v.TokenAccessPolicy),
		Scopes:               v.Scopes,
		UserAuthorizedScopes: v.UserAuthorizedScopes,
	}
}

func createCustomOAuthAppIntegrationRequestFromWire(w *createCustomOAuthAppIntegrationRequestWire) *CreateCustomOAuthAppIntegrationRequest {
	if w == nil {
		return nil
	}
	return &CreateCustomOAuthAppIntegrationRequest{
		AccountId:            w.AccountId,
		RedirectUrls:         w.RedirectUrls,
		Name:                 w.Name,
		Confidential:         w.Confidential,
		TokenAccessPolicy:    tokenAccessPolicyFromWire(w.TokenAccessPolicy),
		Scopes:               w.Scopes,
		UserAuthorizedScopes: w.UserAuthorizedScopes,
	}
}

type createPublishedOAuthAppIntegrationRequestWire struct {
	AccountId         *string                `json:"account_id,omitempty"`
	AppId             *string                `json:"app_id,omitempty"`
	TokenAccessPolicy *tokenAccessPolicyWire `json:"token_access_policy,omitempty"`
}

func createPublishedOAuthAppIntegrationRequestToWire(v *CreatePublishedOAuthAppIntegrationRequest) *createPublishedOAuthAppIntegrationRequestWire {
	if v == nil {
		return nil
	}
	return &createPublishedOAuthAppIntegrationRequestWire{
		AccountId:         v.AccountId,
		AppId:             v.AppId,
		TokenAccessPolicy: tokenAccessPolicyToWire(v.TokenAccessPolicy),
	}
}

func createPublishedOAuthAppIntegrationRequestFromWire(w *createPublishedOAuthAppIntegrationRequestWire) *CreatePublishedOAuthAppIntegrationRequest {
	if w == nil {
		return nil
	}
	return &CreatePublishedOAuthAppIntegrationRequest{
		AccountId:         w.AccountId,
		AppId:             w.AppId,
		TokenAccessPolicy: tokenAccessPolicyFromWire(w.TokenAccessPolicy),
	}
}

type createPublishedOAuthAppIntegrationResponseWire struct {
	IntegrationId *string `json:"integration_id,omitempty"`
}

func createPublishedOAuthAppIntegrationResponseToWire(v *CreatePublishedOAuthAppIntegrationResponse) *createPublishedOAuthAppIntegrationResponseWire {
	if v == nil {
		return nil
	}
	return &createPublishedOAuthAppIntegrationResponseWire{
		IntegrationId: v.IntegrationId,
	}
}

func createPublishedOAuthAppIntegrationResponseFromWire(w *createPublishedOAuthAppIntegrationResponseWire) *CreatePublishedOAuthAppIntegrationResponse {
	if w == nil {
		return nil
	}
	return &CreatePublishedOAuthAppIntegrationResponse{
		IntegrationId: w.IntegrationId,
	}
}

type customOAuthAppIntegrationWire struct {
	IntegrationId        *string                `json:"integration_id,omitempty"`
	ClientId             *string                `json:"client_id,omitempty"`
	RedirectUrls         []string               `json:"redirect_urls,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	Confidential         *bool                  `json:"confidential,omitempty"`
	TokenAccessPolicy    *tokenAccessPolicyWire `json:"token_access_policy,omitempty"`
	Scopes               []string               `json:"scopes,omitempty"`
	CreatedBy            *int64                 `json:"created_by,omitempty"`
	CreateTime           *string                `json:"create_time,omitempty"`
	CreatorUsername      *string                `json:"creator_username,omitempty"`
	UserAuthorizedScopes []string               `json:"user_authorized_scopes,omitempty"`
}

func customOAuthAppIntegrationToWire(v *CustomOAuthAppIntegration) *customOAuthAppIntegrationWire {
	if v == nil {
		return nil
	}
	return &customOAuthAppIntegrationWire{
		IntegrationId:        v.IntegrationId,
		ClientId:             v.ClientId,
		RedirectUrls:         v.RedirectUrls,
		Name:                 v.Name,
		Confidential:         v.Confidential,
		TokenAccessPolicy:    tokenAccessPolicyToWire(v.TokenAccessPolicy),
		Scopes:               v.Scopes,
		CreatedBy:            v.CreatedBy,
		CreateTime:           v.CreateTime,
		CreatorUsername:      v.CreatorUsername,
		UserAuthorizedScopes: v.UserAuthorizedScopes,
	}
}

func customOAuthAppIntegrationFromWire(w *customOAuthAppIntegrationWire) *CustomOAuthAppIntegration {
	if w == nil {
		return nil
	}
	return &CustomOAuthAppIntegration{
		IntegrationId:        w.IntegrationId,
		ClientId:             w.ClientId,
		RedirectUrls:         w.RedirectUrls,
		Name:                 w.Name,
		Confidential:         w.Confidential,
		TokenAccessPolicy:    tokenAccessPolicyFromWire(w.TokenAccessPolicy),
		Scopes:               w.Scopes,
		CreatedBy:            w.CreatedBy,
		CreateTime:           w.CreateTime,
		CreatorUsername:      w.CreatorUsername,
		UserAuthorizedScopes: w.UserAuthorizedScopes,
	}
}

type customOAuthAppIntegrationSecretWire struct {
	IntegrationId *string `json:"integration_id,omitempty"`
	ClientId      *string `json:"client_id,omitempty"`
	ClientSecret  *string `json:"client_secret,omitempty"`
}

func customOAuthAppIntegrationSecretToWire(v *CustomOAuthAppIntegrationSecret) *customOAuthAppIntegrationSecretWire {
	if v == nil {
		return nil
	}
	return &customOAuthAppIntegrationSecretWire{
		IntegrationId: v.IntegrationId,
		ClientId:      v.ClientId,
		ClientSecret:  v.ClientSecret,
	}
}

func customOAuthAppIntegrationSecretFromWire(w *customOAuthAppIntegrationSecretWire) *CustomOAuthAppIntegrationSecret {
	if w == nil {
		return nil
	}
	return &CustomOAuthAppIntegrationSecret{
		IntegrationId: w.IntegrationId,
		ClientId:      w.ClientId,
		ClientSecret:  w.ClientSecret,
	}
}

type deleteCustomOAuthAppIntegrationRequestWire struct {
	AccountId     *string `json:"account_id,omitempty"`
	IntegrationId *string `json:"integration_id,omitempty"`
}

func deleteCustomOAuthAppIntegrationRequestToWire(v *DeleteCustomOAuthAppIntegrationRequest) *deleteCustomOAuthAppIntegrationRequestWire {
	if v == nil {
		return nil
	}
	return &deleteCustomOAuthAppIntegrationRequestWire{
		AccountId:     v.AccountId,
		IntegrationId: v.IntegrationId,
	}
}

func deleteCustomOAuthAppIntegrationRequestFromWire(w *deleteCustomOAuthAppIntegrationRequestWire) *DeleteCustomOAuthAppIntegrationRequest {
	if w == nil {
		return nil
	}
	return &DeleteCustomOAuthAppIntegrationRequest{
		AccountId:     w.AccountId,
		IntegrationId: w.IntegrationId,
	}
}

type deleteCustomOAuthAppIntegrationResponseWire struct {
}

func deleteCustomOAuthAppIntegrationResponseToWire(v *DeleteCustomOAuthAppIntegrationResponse) *deleteCustomOAuthAppIntegrationResponseWire {
	if v == nil {
		return nil
	}
	return &deleteCustomOAuthAppIntegrationResponseWire{}
}

func deleteCustomOAuthAppIntegrationResponseFromWire(w *deleteCustomOAuthAppIntegrationResponseWire) *DeleteCustomOAuthAppIntegrationResponse {
	if w == nil {
		return nil
	}
	return &DeleteCustomOAuthAppIntegrationResponse{}
}

type deletePublishedOAuthAppIntegrationRequestWire struct {
	AccountId     *string `json:"account_id,omitempty"`
	IntegrationId *string `json:"integration_id,omitempty"`
}

func deletePublishedOAuthAppIntegrationRequestToWire(v *DeletePublishedOAuthAppIntegrationRequest) *deletePublishedOAuthAppIntegrationRequestWire {
	if v == nil {
		return nil
	}
	return &deletePublishedOAuthAppIntegrationRequestWire{
		AccountId:     v.AccountId,
		IntegrationId: v.IntegrationId,
	}
}

func deletePublishedOAuthAppIntegrationRequestFromWire(w *deletePublishedOAuthAppIntegrationRequestWire) *DeletePublishedOAuthAppIntegrationRequest {
	if w == nil {
		return nil
	}
	return &DeletePublishedOAuthAppIntegrationRequest{
		AccountId:     w.AccountId,
		IntegrationId: w.IntegrationId,
	}
}

type deletePublishedOAuthAppIntegrationResponseWire struct {
}

func deletePublishedOAuthAppIntegrationResponseToWire(v *DeletePublishedOAuthAppIntegrationResponse) *deletePublishedOAuthAppIntegrationResponseWire {
	if v == nil {
		return nil
	}
	return &deletePublishedOAuthAppIntegrationResponseWire{}
}

func deletePublishedOAuthAppIntegrationResponseFromWire(w *deletePublishedOAuthAppIntegrationResponseWire) *DeletePublishedOAuthAppIntegrationResponse {
	if w == nil {
		return nil
	}
	return &DeletePublishedOAuthAppIntegrationResponse{}
}

type getCustomOAuthAppIntegrationRequestWire struct {
	AccountId     *string `json:"account_id,omitempty"`
	IntegrationId *string `json:"integration_id,omitempty"`
}

func getCustomOAuthAppIntegrationRequestToWire(v *GetCustomOAuthAppIntegrationRequest) *getCustomOAuthAppIntegrationRequestWire {
	if v == nil {
		return nil
	}
	return &getCustomOAuthAppIntegrationRequestWire{
		AccountId:     v.AccountId,
		IntegrationId: v.IntegrationId,
	}
}

func getCustomOAuthAppIntegrationRequestFromWire(w *getCustomOAuthAppIntegrationRequestWire) *GetCustomOAuthAppIntegrationRequest {
	if w == nil {
		return nil
	}
	return &GetCustomOAuthAppIntegrationRequest{
		AccountId:     w.AccountId,
		IntegrationId: w.IntegrationId,
	}
}

type getPublishedOAuthAppIntegrationRequestWire struct {
	AccountId     *string `json:"account_id,omitempty"`
	IntegrationId *string `json:"integration_id,omitempty"`
}

func getPublishedOAuthAppIntegrationRequestToWire(v *GetPublishedOAuthAppIntegrationRequest) *getPublishedOAuthAppIntegrationRequestWire {
	if v == nil {
		return nil
	}
	return &getPublishedOAuthAppIntegrationRequestWire{
		AccountId:     v.AccountId,
		IntegrationId: v.IntegrationId,
	}
}

func getPublishedOAuthAppIntegrationRequestFromWire(w *getPublishedOAuthAppIntegrationRequestWire) *GetPublishedOAuthAppIntegrationRequest {
	if w == nil {
		return nil
	}
	return &GetPublishedOAuthAppIntegrationRequest{
		AccountId:     w.AccountId,
		IntegrationId: w.IntegrationId,
	}
}

type listCustomOAuthAppIntegrationsRequestWire struct {
	AccountId              *string `json:"account_id,omitempty"`
	PageToken              *string `json:"page_token,omitempty"`
	PageSize               *int    `json:"page_size,omitempty"`
	IncludeCreatorUsername *bool   `json:"include_creator_username,omitempty"`
}

func listCustomOAuthAppIntegrationsRequestToWire(v *ListCustomOAuthAppIntegrationsRequest) *listCustomOAuthAppIntegrationsRequestWire {
	if v == nil {
		return nil
	}
	return &listCustomOAuthAppIntegrationsRequestWire{
		AccountId:              v.AccountId,
		PageToken:              v.PageToken,
		PageSize:               v.PageSize,
		IncludeCreatorUsername: v.IncludeCreatorUsername,
	}
}

func listCustomOAuthAppIntegrationsRequestFromWire(w *listCustomOAuthAppIntegrationsRequestWire) *ListCustomOAuthAppIntegrationsRequest {
	if w == nil {
		return nil
	}
	return &ListCustomOAuthAppIntegrationsRequest{
		AccountId:              w.AccountId,
		PageToken:              w.PageToken,
		PageSize:               w.PageSize,
		IncludeCreatorUsername: w.IncludeCreatorUsername,
	}
}

type listCustomOAuthAppIntegrationsResponseWire struct {
	Apps          []customOAuthAppIntegrationWire `json:"apps,omitempty"`
	NextPageToken *string                         `json:"next_page_token,omitempty"`
}

func listCustomOAuthAppIntegrationsResponseToWire(v *ListCustomOAuthAppIntegrationsResponse) *listCustomOAuthAppIntegrationsResponseWire {
	if v == nil {
		return nil
	}
	return &listCustomOAuthAppIntegrationsResponseWire{
		Apps:          convertSlice(v.Apps, customOAuthAppIntegrationToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listCustomOAuthAppIntegrationsResponseFromWire(w *listCustomOAuthAppIntegrationsResponseWire) *ListCustomOAuthAppIntegrationsResponse {
	if w == nil {
		return nil
	}
	return &ListCustomOAuthAppIntegrationsResponse{
		Apps:          convertSlice(w.Apps, customOAuthAppIntegrationFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type listPublishedOAuthAppIntegrationsRequestWire struct {
	AccountId *string `json:"account_id,omitempty"`
	PageToken *string `json:"page_token,omitempty"`
	PageSize  *int    `json:"page_size,omitempty"`
}

func listPublishedOAuthAppIntegrationsRequestToWire(v *ListPublishedOAuthAppIntegrationsRequest) *listPublishedOAuthAppIntegrationsRequestWire {
	if v == nil {
		return nil
	}
	return &listPublishedOAuthAppIntegrationsRequestWire{
		AccountId: v.AccountId,
		PageToken: v.PageToken,
		PageSize:  v.PageSize,
	}
}

func listPublishedOAuthAppIntegrationsRequestFromWire(w *listPublishedOAuthAppIntegrationsRequestWire) *ListPublishedOAuthAppIntegrationsRequest {
	if w == nil {
		return nil
	}
	return &ListPublishedOAuthAppIntegrationsRequest{
		AccountId: w.AccountId,
		PageToken: w.PageToken,
		PageSize:  w.PageSize,
	}
}

type listPublishedOAuthAppIntegrationsResponseWire struct {
	Apps          []publishedOAuthAppIntegrationWire `json:"apps,omitempty"`
	NextPageToken *string                            `json:"next_page_token,omitempty"`
}

func listPublishedOAuthAppIntegrationsResponseToWire(v *ListPublishedOAuthAppIntegrationsResponse) *listPublishedOAuthAppIntegrationsResponseWire {
	if v == nil {
		return nil
	}
	return &listPublishedOAuthAppIntegrationsResponseWire{
		Apps:          convertSlice(v.Apps, publishedOAuthAppIntegrationToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listPublishedOAuthAppIntegrationsResponseFromWire(w *listPublishedOAuthAppIntegrationsResponseWire) *ListPublishedOAuthAppIntegrationsResponse {
	if w == nil {
		return nil
	}
	return &ListPublishedOAuthAppIntegrationsResponse{
		Apps:          convertSlice(w.Apps, publishedOAuthAppIntegrationFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type listPublishedOAuthAppsRequestWire struct {
	AccountId *string `json:"account_id,omitempty"`
	PageToken *string `json:"page_token,omitempty"`
	PageSize  *int    `json:"page_size,omitempty"`
}

func listPublishedOAuthAppsRequestToWire(v *ListPublishedOAuthAppsRequest) *listPublishedOAuthAppsRequestWire {
	if v == nil {
		return nil
	}
	return &listPublishedOAuthAppsRequestWire{
		AccountId: v.AccountId,
		PageToken: v.PageToken,
		PageSize:  v.PageSize,
	}
}

func listPublishedOAuthAppsRequestFromWire(w *listPublishedOAuthAppsRequestWire) *ListPublishedOAuthAppsRequest {
	if w == nil {
		return nil
	}
	return &ListPublishedOAuthAppsRequest{
		AccountId: w.AccountId,
		PageToken: w.PageToken,
		PageSize:  w.PageSize,
	}
}

type listPublishedOAuthAppsResponseWire struct {
	Apps          []publishedOAuthAppWire `json:"apps,omitempty"`
	NextPageToken *string                 `json:"next_page_token,omitempty"`
}

func listPublishedOAuthAppsResponseToWire(v *ListPublishedOAuthAppsResponse) *listPublishedOAuthAppsResponseWire {
	if v == nil {
		return nil
	}
	return &listPublishedOAuthAppsResponseWire{
		Apps:          convertSlice(v.Apps, publishedOAuthAppToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listPublishedOAuthAppsResponseFromWire(w *listPublishedOAuthAppsResponseWire) *ListPublishedOAuthAppsResponse {
	if w == nil {
		return nil
	}
	return &ListPublishedOAuthAppsResponse{
		Apps:          convertSlice(w.Apps, publishedOAuthAppFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type publishedOAuthAppWire struct {
	AppId                *string  `json:"app_id,omitempty"`
	ClientId             *string  `json:"client_id,omitempty"`
	Name                 *string  `json:"name,omitempty"`
	Description          *string  `json:"description,omitempty"`
	IsConfidentialClient *bool    `json:"is_confidential_client,omitempty"`
	RedirectUrls         []string `json:"redirect_urls,omitempty"`
	Scopes               []string `json:"scopes,omitempty"`
}

func publishedOAuthAppToWire(v *PublishedOAuthApp) *publishedOAuthAppWire {
	if v == nil {
		return nil
	}
	return &publishedOAuthAppWire{
		AppId:                v.AppId,
		ClientId:             v.ClientId,
		Name:                 v.Name,
		Description:          v.Description,
		IsConfidentialClient: v.IsConfidentialClient,
		RedirectUrls:         v.RedirectUrls,
		Scopes:               v.Scopes,
	}
}

func publishedOAuthAppFromWire(w *publishedOAuthAppWire) *PublishedOAuthApp {
	if w == nil {
		return nil
	}
	return &PublishedOAuthApp{
		AppId:                w.AppId,
		ClientId:             w.ClientId,
		Name:                 w.Name,
		Description:          w.Description,
		IsConfidentialClient: w.IsConfidentialClient,
		RedirectUrls:         w.RedirectUrls,
		Scopes:               w.Scopes,
	}
}

type publishedOAuthAppIntegrationWire struct {
	AppId             *string                `json:"app_id,omitempty"`
	IntegrationId     *string                `json:"integration_id,omitempty"`
	Name              *string                `json:"name,omitempty"`
	TokenAccessPolicy *tokenAccessPolicyWire `json:"token_access_policy,omitempty"`
	CreatedBy         *int64                 `json:"created_by,omitempty"`
	CreateTime        *string                `json:"create_time,omitempty"`
}

func publishedOAuthAppIntegrationToWire(v *PublishedOAuthAppIntegration) *publishedOAuthAppIntegrationWire {
	if v == nil {
		return nil
	}
	return &publishedOAuthAppIntegrationWire{
		AppId:             v.AppId,
		IntegrationId:     v.IntegrationId,
		Name:              v.Name,
		TokenAccessPolicy: tokenAccessPolicyToWire(v.TokenAccessPolicy),
		CreatedBy:         v.CreatedBy,
		CreateTime:        v.CreateTime,
	}
}

func publishedOAuthAppIntegrationFromWire(w *publishedOAuthAppIntegrationWire) *PublishedOAuthAppIntegration {
	if w == nil {
		return nil
	}
	return &PublishedOAuthAppIntegration{
		AppId:             w.AppId,
		IntegrationId:     w.IntegrationId,
		Name:              w.Name,
		TokenAccessPolicy: tokenAccessPolicyFromWire(w.TokenAccessPolicy),
		CreatedBy:         w.CreatedBy,
		CreateTime:        w.CreateTime,
	}
}

type tokenAccessPolicyWire struct {
	AccessTokenTtlInMinutes          *int  `json:"access_token_ttl_in_minutes,omitempty"`
	RefreshTokenTtlInMinutes         *int  `json:"refresh_token_ttl_in_minutes,omitempty"`
	EnableSingleUseRefreshTokens     *bool `json:"enable_single_use_refresh_tokens,omitempty"`
	AbsoluteSessionLifetimeInMinutes *int  `json:"absolute_session_lifetime_in_minutes,omitempty"`
}

func tokenAccessPolicyToWire(v *TokenAccessPolicy) *tokenAccessPolicyWire {
	if v == nil {
		return nil
	}
	return &tokenAccessPolicyWire{
		AccessTokenTtlInMinutes:          v.AccessTokenTtlInMinutes,
		RefreshTokenTtlInMinutes:         v.RefreshTokenTtlInMinutes,
		EnableSingleUseRefreshTokens:     v.EnableSingleUseRefreshTokens,
		AbsoluteSessionLifetimeInMinutes: v.AbsoluteSessionLifetimeInMinutes,
	}
}

func tokenAccessPolicyFromWire(w *tokenAccessPolicyWire) *TokenAccessPolicy {
	if w == nil {
		return nil
	}
	return &TokenAccessPolicy{
		AccessTokenTtlInMinutes:          w.AccessTokenTtlInMinutes,
		RefreshTokenTtlInMinutes:         w.RefreshTokenTtlInMinutes,
		EnableSingleUseRefreshTokens:     w.EnableSingleUseRefreshTokens,
		AbsoluteSessionLifetimeInMinutes: w.AbsoluteSessionLifetimeInMinutes,
	}
}

type updateCustomOAuthAppIntegrationRequestWire struct {
	AccountId            *string                `json:"account_id,omitempty"`
	IntegrationId        *string                `json:"integration_id,omitempty"`
	RedirectUrls         []string               `json:"redirect_urls,omitempty"`
	TokenAccessPolicy    *tokenAccessPolicyWire `json:"token_access_policy,omitempty"`
	Scopes               []string               `json:"scopes,omitempty"`
	UserAuthorizedScopes []string               `json:"user_authorized_scopes,omitempty"`
}

func updateCustomOAuthAppIntegrationRequestToWire(v *UpdateCustomOAuthAppIntegrationRequest) *updateCustomOAuthAppIntegrationRequestWire {
	if v == nil {
		return nil
	}
	return &updateCustomOAuthAppIntegrationRequestWire{
		AccountId:            v.AccountId,
		IntegrationId:        v.IntegrationId,
		RedirectUrls:         v.RedirectUrls,
		TokenAccessPolicy:    tokenAccessPolicyToWire(v.TokenAccessPolicy),
		Scopes:               v.Scopes,
		UserAuthorizedScopes: v.UserAuthorizedScopes,
	}
}

func updateCustomOAuthAppIntegrationRequestFromWire(w *updateCustomOAuthAppIntegrationRequestWire) *UpdateCustomOAuthAppIntegrationRequest {
	if w == nil {
		return nil
	}
	return &UpdateCustomOAuthAppIntegrationRequest{
		AccountId:            w.AccountId,
		IntegrationId:        w.IntegrationId,
		RedirectUrls:         w.RedirectUrls,
		TokenAccessPolicy:    tokenAccessPolicyFromWire(w.TokenAccessPolicy),
		Scopes:               w.Scopes,
		UserAuthorizedScopes: w.UserAuthorizedScopes,
	}
}

type updateCustomOAuthAppIntegrationResponseWire struct {
}

func updateCustomOAuthAppIntegrationResponseToWire(v *UpdateCustomOAuthAppIntegrationResponse) *updateCustomOAuthAppIntegrationResponseWire {
	if v == nil {
		return nil
	}
	return &updateCustomOAuthAppIntegrationResponseWire{}
}

func updateCustomOAuthAppIntegrationResponseFromWire(w *updateCustomOAuthAppIntegrationResponseWire) *UpdateCustomOAuthAppIntegrationResponse {
	if w == nil {
		return nil
	}
	return &UpdateCustomOAuthAppIntegrationResponse{}
}

type updatePublishedOAuthAppIntegrationRequestWire struct {
	AccountId         *string                `json:"account_id,omitempty"`
	IntegrationId     *string                `json:"integration_id,omitempty"`
	TokenAccessPolicy *tokenAccessPolicyWire `json:"token_access_policy,omitempty"`
}

func updatePublishedOAuthAppIntegrationRequestToWire(v *UpdatePublishedOAuthAppIntegrationRequest) *updatePublishedOAuthAppIntegrationRequestWire {
	if v == nil {
		return nil
	}
	return &updatePublishedOAuthAppIntegrationRequestWire{
		AccountId:         v.AccountId,
		IntegrationId:     v.IntegrationId,
		TokenAccessPolicy: tokenAccessPolicyToWire(v.TokenAccessPolicy),
	}
}

func updatePublishedOAuthAppIntegrationRequestFromWire(w *updatePublishedOAuthAppIntegrationRequestWire) *UpdatePublishedOAuthAppIntegrationRequest {
	if w == nil {
		return nil
	}
	return &UpdatePublishedOAuthAppIntegrationRequest{
		AccountId:         w.AccountId,
		IntegrationId:     w.IntegrationId,
		TokenAccessPolicy: tokenAccessPolicyFromWire(w.TokenAccessPolicy),
	}
}

type updatePublishedOAuthAppIntegrationResponseWire struct {
}

func updatePublishedOAuthAppIntegrationResponseToWire(v *UpdatePublishedOAuthAppIntegrationResponse) *updatePublishedOAuthAppIntegrationResponseWire {
	if v == nil {
		return nil
	}
	return &updatePublishedOAuthAppIntegrationResponseWire{}
}

func updatePublishedOAuthAppIntegrationResponseFromWire(w *updatePublishedOAuthAppIntegrationResponseWire) *UpdatePublishedOAuthAppIntegrationResponse {
	if w == nil {
		return nil
	}
	return &UpdatePublishedOAuthAppIntegrationResponse{}
}

func convertSlice[T, W any](s []T, conv func(*T) *W) []W {
	if s == nil {
		return nil
	}
	out := make([]W, len(s))
	for i := range s {
		out[i] = *conv(&s[i])
	}
	return out
}
