// Code generated by Databricks SDK Generator. DO NOT EDIT.

package tagassignments

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"log/slog"
	"net/http"
	"net/url"
	"sync"

	"github.com/databricks/sdk-go/auth"
	"github.com/databricks/sdk-go/core/clientinfo"
	"github.com/databricks/sdk-go/options/call"
	"github.com/databricks/sdk-go/options/client"
	"github.com/databricks/sdk-go/options/internaloptions"
	"github.com/databricks/sdk-go/tagassignments/internal"
)

type Client struct {
	internalClient

	// extensions is a per-client store for hand-written mixins to attach
	// lazily-built state. Keys should be unexported types private to the
	// mixin, following the context.Value convention, to avoid collisions.
	// The zero value is ready to use; it is safe for concurrent use.
	extensions sync.Map
}

type internalClient struct {
	httpClient  *http.Client
	credentials auth.Credentials
	logger      *slog.Logger
	userAgent   func() (string, error)
	host        string
	workspaceID string
	accountID   string
}

func NewClient(ctx context.Context, opts ...client.Option) (*Client, error) {
	cfg := internaloptions.ClientOptions{}
	for _, opt := range opts {
		if err := opt(&cfg); err != nil {
			return nil, err
		}
	}
	if err := cfg.Resolve(); err != nil {
		return nil, err
	}
	userAgent := func() (string, error) {
		info, err := clientinfo.Default().With(
			internal.ModuleName, internal.Version,
			"auth", cfg.Credentials.Name(),
		)
		if err != nil {
			return "", err
		}
		return info.String(), nil
	}

	return &Client{
		internalClient: internalClient{
			httpClient:  cfg.HTTPClient,
			credentials: cfg.Credentials,
			logger:      cfg.Logger,
			userAgent:   userAgent,
			host:        cfg.Host,
			workspaceID: cfg.WorkspaceID,
			accountID:   cfg.AccountID,
		},
	}, nil
}

// Create a tag assignment
func (c *internalClient) CreateTagAssignment(ctx context.Context, req CreateTagAssignmentRequest, opts ...call.Option) (*TagAssignment, error) {
	wireReq, err := createTagAssignmentRequestToWire(&req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq.TagAssignment)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/entity-tag-assignments"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *TagAssignment

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp tagAssignmentWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = tagAssignmentFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Delete a tag assignment
func (c *internalClient) DeleteTagAssignment(ctx context.Context, req DeleteTagAssignmentRequest, opts ...call.Option) error {

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/entity-tag-assignments/")
	if req.EntityType == nil {
		return fmt.Errorf("path parameter %q is required", "entity_type")
	}
	pb.singleSegment(*req.EntityType)
	pb.literal("/")
	if req.EntityId == nil {
		return fmt.Errorf("path parameter %q is required", "entity_id")
	}
	pb.singleSegment(*req.EntityId)
	pb.literal("/tags/")
	if req.TagKey == nil {
		return fmt.Errorf("path parameter %q is required", "tag_key")
	}
	pb.singleSegment(*req.TagKey)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return err
	}
	return nil
}

// Get a tag assignment
func (c *internalClient) GetTagAssignment(ctx context.Context, req GetTagAssignmentRequest, opts ...call.Option) (*TagAssignment, error) {

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/entity-tag-assignments/")
	if req.EntityType == nil {
		return nil, fmt.Errorf("path parameter %q is required", "entity_type")
	}
	pb.singleSegment(*req.EntityType)
	pb.literal("/")
	if req.EntityId == nil {
		return nil, fmt.Errorf("path parameter %q is required", "entity_id")
	}
	pb.singleSegment(*req.EntityId)
	pb.literal("/tags/")
	if req.TagKey == nil {
		return nil, fmt.Errorf("path parameter %q is required", "tag_key")
	}
	pb.singleSegment(*req.TagKey)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *TagAssignment

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp tagAssignmentWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = tagAssignmentFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// List the tag assignments for an entity
func (c *internalClient) ListTagAssignments(ctx context.Context, req ListTagAssignmentsRequest, opts ...call.Option) (*ListTagAssignmentsResponse, error) {
	wireReq, err := listTagAssignmentsRequestToWire(&req)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/entity-tag-assignments/")
	if req.EntityType == nil {
		return nil, fmt.Errorf("path parameter %q is required", "entity_type")
	}
	pb.singleSegment(*req.EntityType)
	pb.literal("/")
	if req.EntityId == nil {
		return nil, fmt.Errorf("path parameter %q is required", "entity_id")
	}
	pb.singleSegment(*req.EntityId)
	pb.literal("/tags")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "page_size", wireReq.PageSize); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "page_token", wireReq.PageToken); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListTagAssignmentsResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listTagAssignmentsResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = listTagAssignmentsResponseFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// ListTagAssignmentsIter returns an iterator that iterates
// over the results of ListTagAssignments.
//
// For example:
//
//	for item, err := range c.ListTagAssignmentsIter(ctx, ListTagAssignmentsRequest{}) {
//	  if err != nil {
//	    return err
//	  }
//	  fmt.Println(item)
//	}
//
// Options opts are passed to each ListTagAssignments call
// made by the iterator under the hood.
//
// Callers who need custom pagination logic should use
// ListTagAssignments directly.
func (c *internalClient) ListTagAssignmentsIter(ctx context.Context, req ListTagAssignmentsRequest, opts ...call.Option) iter.Seq2[*TagAssignment, error] {
	return func(yield func(*TagAssignment, error) bool) {
		// Keep pagination state local to this traversal so reusing the iterator starts
		// from the original request. Reference-bearing fields remain shared and read-only.
		pageReq := req
		for {
			resp, err := c.ListTagAssignments(ctx, pageReq, opts...)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range resp.TagAssignments {
				if !yield(&resp.TagAssignments[i], nil) {
					return
				}
			}
			if resp.NextPageToken == nil || *resp.NextPageToken == "" {
				return
			}
			pageReq.PageToken = resp.NextPageToken
		}
	}
}

// Update a tag assignment
func (c *internalClient) UpdateTagAssignment(ctx context.Context, req UpdateTagAssignmentRequest, opts ...call.Option) (*TagAssignment, error) {
	wireReq, err := updateTagAssignmentRequestToWire(&req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq.TagAssignment)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/entity-tag-assignments/")
	if req.TagAssignment == nil || req.TagAssignment.EntityType == nil {
		return nil, fmt.Errorf("path parameter %q is required", "entity_type")
	}
	pb.singleSegment(*req.TagAssignment.EntityType)
	pb.literal("/")
	if req.TagAssignment == nil || req.TagAssignment.EntityId == nil {
		return nil, fmt.Errorf("path parameter %q is required", "entity_id")
	}
	pb.singleSegment(*req.TagAssignment.EntityId)
	pb.literal("/tags/")
	if req.TagAssignment == nil || req.TagAssignment.TagKey == nil {
		return nil, fmt.Errorf("path parameter %q is required", "tag_key")
	}
	pb.singleSegment(*req.TagAssignment.TagKey)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "update_mask", wireReq.UpdateMask); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *TagAssignment

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PATCH",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp tagAssignmentWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = tagAssignmentFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}
