// Code generated by Databricks SDK Generator. DO NOT EDIT.

package tagassignments

type CreateTagAssignmentRequest struct {
	TagAssignment *TagAssignment
}

type DeleteTagAssignmentRequest struct {
	EntityType *string
	EntityId   *string
	TagKey     *string
}

type GetTagAssignmentRequest struct {
	EntityType *string
	EntityId   *string
	TagKey     *string
}

type ListTagAssignmentsRequest struct {
	EntityType *string
	EntityId   *string
	PageSize   *int
	PageToken  *string
}

type ListTagAssignmentsResponse struct {
	TagAssignments []TagAssignment
	NextPageToken  *string
}

type TagAssignment struct {
	EntityType *string
	EntityId   *string
	TagKey     *string
	TagValue   *string
}

type UpdateTagAssignmentRequest struct {
	TagAssignment *TagAssignment
	UpdateMask    *string
}
