// Code generated by Databricks SDK Generator. DO NOT EDIT.

package apps

import (
	"encoding/json"
	"fmt"

	"github.com/databricks/sdk-go/core/types"
)

type ComputeSize string

const (
	ComputeSize_Unspecified ComputeSize = ""
	ComputeSize_Medium      ComputeSize = "MEDIUM"
	ComputeSize_Large       ComputeSize = "LARGE"
	ComputeSize_Xlarge      ComputeSize = "XLARGE"
)

// Error codes returned by Databricks APIs to indicate specific failure
// conditions.
type ErrorCode string

const (
	ErrorCode_Unspecified ErrorCode = ""
	// Internal error. This means that some invariants expected by the underlying
	// system have been broken. This error code is reserved for serious errors,
	// which generally cannot be resolved by the user.
	//
	// Prefer this over all kinds of detailed error messages (e.g IO_ERROR), unless
	// there's some automation that relies on the custom error code.
	//
	// Maps to: - google.rpc.Code: INTERNAL = 13; - HTTP code: 500 Internal Server
	// Error
	ErrorCode_InternalError ErrorCode = "INTERNAL_ERROR"
	// The service is currently unavailable. This is most likely a transient
	// condition, which can be corrected by retrying with a backoff. Note that it is
	// not always safe to retry non-idempotent operations.
	//
	// Prefer this over SERVICE_UNDER_MAINTENANCE,
	// WORKSPACE_TEMPORARILY_UNAVAILABLE.
	//
	// See
	// https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
	// for guideline on how to pick this vs RESOURCE_EXHAUSTED.
	//
	// Maps to: - google.rpc.Code: UNAVAILABLE = 14; - HTTP code: 503 Service
	// Unavailable
	ErrorCode_TemporarilyUnavailable ErrorCode = "TEMPORARILY_UNAVAILABLE"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes. Indicates that an IOException has been internally
	// thrown.
	ErrorCode_IoError ErrorCode = "IO_ERROR"
	// The request is invalid. Prefer more specific error code whenever possible.
	// Also see similar recommendation for the google.rpc.Code.FAILED_PRECONDITION.
	//
	// Prefer this error code over MALFORMED_REQUEST, INVALID_STATE,
	// UNPARSEABLE_HTTP_ERROR.
	//
	// Maps to: - google.rpc.Code: FAILED_PRECONDITION = 9; - HTTP code: 400 Bad
	// Request
	ErrorCode_BadRequest ErrorCode = "BAD_REQUEST"
	// An external service is unavailable temporarily as it is being
	// updated/re-deployed. Indicates gateway proxy to safely retry the request.
	ErrorCode_ServiceUnderMaintenance ErrorCode = "SERVICE_UNDER_MAINTENANCE"
	// A workspace is temporarily unavailable as the workspace is being re-assigned.
	ErrorCode_WorkspaceTemporarilyUnavailable ErrorCode = "WORKSPACE_TEMPORARILY_UNAVAILABLE"
	// The deadline expired before the operation could complete. For operations that
	// change the state of the system, this error may be returned even if the
	// operation has completed successfully. For example, a successful response from
	// a server could have been delayed long enough for the deadline to expire. When
	// possible - implementations should make sure further processing of the request
	// is aborted, e.g. by throwing an exception instead of making the RPC request,
	// making the database query, etc.
	//
	// Maps to: - google.rpc.Code: DEADLINE_EXCEEDED = 4; - HTTP code: 504 Gateway
	// Timeout
	ErrorCode_DeadlineExceeded ErrorCode = "DEADLINE_EXCEEDED"
	// The operation was canceled by the caller. An example - client closed the
	// connection without waiting for a response.
	//
	// Maps to: - google.rpc.Code: CANCELLED = 1; - HTTP code: 499 Client Closed
	// Request
	ErrorCode_Cancelled ErrorCode = "CANCELLED"
	// The operation is rejected because of either rate limiting or resource quota,
	// such as the client has sent too many requests recently or the client has
	// allocated too many resources.
	//
	// See
	// https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
	// for guideline on how to pick this vs TEMPORARILY_UNAVAILABLE.
	//
	// Maps to: - google.rpc.Code: RESOURCE_EXHAUSTED = 8; - HTTP code: 429 Too Many
	// Requests
	ErrorCode_ResourceExhausted ErrorCode = "RESOURCE_EXHAUSTED"
	// The operation was aborted, typically due to a concurrency issue such as a
	// sequencer check failure, transaction abort, or transaction conflict.
	//
	// Maps to: - google.rpc.Code: ABORTED = 10; - HTTP code: 409 Conflict
	ErrorCode_Aborted ErrorCode = "ABORTED"
	// Operation was performed on a resource that does not exist, e.g. file or
	// directory was not found.
	//
	// Maps to: - google.rpc.Code: NOT_FOUND = 5; - HTTP code: 404 Not Found
	ErrorCode_NotFound ErrorCode = "NOT_FOUND"
	// Operation was rejected due a conflict with an existing resource, e.g.
	// attempted to create file or directory that already exists.
	//
	// Prefer this over RESOURCE_CONFLICT.
	//
	// Maps to: - google.rpc.Code: ALREADY_EXISTS = 6; - HTTP code: 409 Conflict
	ErrorCode_AlreadyExists ErrorCode = "ALREADY_EXISTS"
	// The request does not have valid authentication (AuthN) credentials for the
	// operation.
	//
	// Prefer this over CUSTOMER_UNAUTHORIZED, unless you need to keep consistent
	// behavior with legacy code. For authorization (AuthZ) errors use
	// PERMISSION_DENIED. Maps to: - google.rpc.Code: UNAUTHENTICATED = 16; - HTTP
	// code: 401 Unauthorized
	ErrorCode_Unauthenticated ErrorCode = "UNAUTHENTICATED"
	// The service is currently unavailable. Please note that the unavailability may
	// or may not be transient. That means if this is a non-transient condition,
	// retrying it does not work. If the unavailability is certainly a transient
	// condition, pleases use `TEMPORARILY_UNAVAILABLE` which signals its transient
	// nature explicitly. An example of this error code’s use case is that when
	// DNS resolution fails, the DNS resolver does not know whether it is because
	// the domain name is completely wrong (non-transient situation) or the domain
	// name is valid but the DNS server does not have an entry for this domain name
	// yet (transient situation). Hence, `UNAVAILABLE` is suitable for this case.
	//
	// Maps to: - google.rpc.Code: UNAVAILABLE = 14; - HTTP code: 503 Service
	// Unavailable
	ErrorCode_Unavailable ErrorCode = "UNAVAILABLE"
	// Supplied value for a parameter was invalid (e.g., giving a number for a
	// string parameter).
	//
	// Maps to: - google.rpc.Code: INVALID_ARGUMENT = 3; - HTTP code: 400 Bad
	// Request
	ErrorCode_InvalidParameterValue ErrorCode = "INVALID_PARAMETER_VALUE"
	// Indicates that the given API endpoint does not exist. Legacy, when possible -
	// NOT_IMPLEMENTED should be used instead to indicate that API doesn't exist.
	//
	// Maps to: - google.rpc.Code: NOT_FOUND = 5; - HTTP code: 404 Not Found
	ErrorCode_EndpointNotFound ErrorCode = "ENDPOINT_NOT_FOUND"
	// Indicates that the given API request was malformed.
	ErrorCode_MalformedRequest ErrorCode = "MALFORMED_REQUEST"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes. If one or more of the inputs to a given RPC are not in
	// a valid state for the action.
	ErrorCode_InvalidState ErrorCode = "INVALID_STATE"
	// The caller does not have permission to execute the specified operation.
	// PERMISSION_DENIED must not be used for rejections caused by exhausting some
	// resource, use RESOURCE_EXHAUSTED instead for those errors. PERMISSION_DENIED
	// must not be used if the caller can not be identified, use
	// CUSTOMER_UNAUTHORIZED instead for those errors. This error code does not
	// imply the request is valid or the requested entity exists or satisfies other
	// pre-conditions.
	//
	// Maps to: - google.rpc.Code: PERMISSION_DENIED = 7; - HTTP code: 403 Forbidden
	ErrorCode_PermissionDenied ErrorCode = "PERMISSION_DENIED"
	// NOTE: Deprecated due to inconsistent mapping in legacy code, see
	// https://docs.google.com/document/d/17TZIKX_Y39cJMBr333lc-d5dTvvBLSu3DPUyGU5eMJg/edit?disco=AAAAzVGt6FA.
	// Prefer using NOT_FOUND or PERMISSION_DENIED.
	//
	// If a given user/entity is trying to use a feature which has been disabled.
	//
	// Maps to: - google.rpc.Code: NOT_FOUND = 5; - HTTP code: 404 Not Found
	ErrorCode_FeatureDisabled ErrorCode = "FEATURE_DISABLED"
	// The request does not have valid authentication (AuthN) credentials for the
	// operation.
	//
	// For authentication (AuthN) errors prefer using UNAUTHENTICATED, unless you
	// need to keep consistent behavior with legacy code. For authorization (AuthZ)
	// errors use PERMISSION_DENIED.
	//
	// Important: name is confusing, this error code is for authentication (AuthN)
	// errors, not authorization (AuthZ) errors. It maps to 401 Unauthorized and
	// suffers from the same confusing naming. See
	// https://datatracker.ietf.org/doc/html/rfc7235#section-3.1 - "[...] status
	// code indicates that the request has not been applied because it lacks valid
	// authentication credentials for the target resource. [...] If the request
	// included authentication credentials, then the 401 response indicates that
	// authorization has been refused for those credentials."
	//
	// Also, see https://stackoverflow.com/a/6937030/16352922, it covers it pretty
	// well.
	//
	// Maps to: - google.rpc.Code: UNAUTHENTICATED = 16; - HTTP code: 401
	// Unauthorized
	ErrorCode_CustomerUnauthorized ErrorCode = "CUSTOMER_UNAUTHORIZED"
	// The operation is rejected because of request rate limit, for example rate
	// limiting applied to users, workspaces, IP addresses, etc.
	//
	// Prefer a more generic RESOURCE_EXHAUSTED for the new use cases.
	//
	// See
	// https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
	// for guideline on the rate limiting vs throttling.
	//
	// Maps to: - google.rpc.Code: RESOURCE_EXHAUSTED = 8; - HTTP code: 429 Too Many
	// Requests
	ErrorCode_RequestLimitExceeded ErrorCode = "REQUEST_LIMIT_EXCEEDED"
	// Indicates API request was rejected due a conflict with an existing resource.
	ErrorCode_ResourceConflict ErrorCode = "RESOURCE_CONFLICT"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes. Indicates that the HTTP response cannot be correctly
	// deserialized. This currently is only used in DUST test clients, and not by
	// any real service code.
	ErrorCode_UnparseableHttpError ErrorCode = "UNPARSEABLE_HTTP_ERROR"
	// The operation is not implemented or is not supported/enabled in this service.
	//
	// Maps to: - google.rpc.Code: UNIMPLEMENTED = 12; - HTTP code: 501 Not
	// Implemented
	ErrorCode_NotImplemented ErrorCode = "NOT_IMPLEMENTED"
	// Unrecoverable data loss or corruption.
	//
	// One of the major use cases is to indicate that server failed to validate the
	// integrity of the request. This error can occur when the checksum specified in
	// the `X-Databricks-Checksum` request header (or trailer) doesn't match the
	// actual request content checksum.
	//
	// Note, in case of the severe corruption that results in a malformed request,
	// the server may send a generic `400 Bad Request` response rather than sending
	// this error code.
	//
	// Maps to: - google.rpc.Code: DATA_LOSS = 15; - HTTP code: 500 Internal Server
	// Error
	ErrorCode_DataLoss ErrorCode = "DATA_LOSS"
	// If the user attempts to perform an invalid state transition on a shard.
	ErrorCode_InvalidStateTransition ErrorCode = "INVALID_STATE_TRANSITION"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes. Unable to perform the operation because the shard was
	// locked by some other operation.
	ErrorCode_CouldNotAcquireLock ErrorCode = "COULD_NOT_ACQUIRE_LOCK"
	// NOTE: Deprecated, prefer using ALREADY_EXISTS. Unlike ALREADY_EXISTS - this
	// maps to HTTP code 400 Bad Request due to legacy reasons, remapping will be a
	// backwards incompatible change.
	//
	// Operation was performed on a resource that already exists.
	ErrorCode_ResourceAlreadyExists ErrorCode = "RESOURCE_ALREADY_EXISTS"
	// NOTE: Deprecated, prefer using NOT_FOUND - see the note for the
	// RESOURCE_ALREADY_EXISTS, because this pair of codes is related and
	// RESOURCE_ALREADY_EXISTS has bad mapping to the HTTP codes we added new error
	// codes NOT_FOUND and ALREADY_EXISTS, and recommend to use them instead.
	//
	// Operation was performed on a resource that does not exist.
	ErrorCode_ResourceDoesNotExist ErrorCode = "RESOURCE_DOES_NOT_EXIST"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_QuotaExceeded ErrorCode = "QUOTA_EXCEEDED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_MaxBlockSizeExceeded ErrorCode = "MAX_BLOCK_SIZE_EXCEEDED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_MaxReadSizeExceeded ErrorCode = "MAX_READ_SIZE_EXCEEDED"
	ErrorCode_PartialDelete       ErrorCode = "PARTIAL_DELETE"
	ErrorCode_MaxListSizeExceeded ErrorCode = "MAX_LIST_SIZE_EXCEEDED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_DryRunFailed ErrorCode = "DRY_RUN_FAILED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes. Cluster request was rejected because it would exceed a
	// resource limit.
	ErrorCode_ResourceLimitExceeded ErrorCode = "RESOURCE_LIMIT_EXCEEDED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_DirectoryNotEmpty ErrorCode = "DIRECTORY_NOT_EMPTY"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_DirectoryProtected ErrorCode = "DIRECTORY_PROTECTED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_MaxNotebookSizeExceeded  ErrorCode = "MAX_NOTEBOOK_SIZE_EXCEEDED"
	ErrorCode_MaxChildNodeSizeExceeded ErrorCode = "MAX_CHILD_NODE_SIZE_EXCEEDED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_SearchQueryTooLong ErrorCode = "SEARCH_QUERY_TOO_LONG"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_SearchQueryTooShort ErrorCode = "SEARCH_QUERY_TOO_SHORT"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_ManagedResourceGroupDoesNotExist ErrorCode = "MANAGED_RESOURCE_GROUP_DOES_NOT_EXIST"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_PermissionNotPropagated ErrorCode = "PERMISSION_NOT_PROPAGATED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_DeploymentTimeout ErrorCode = "DEPLOYMENT_TIMEOUT"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_GitConflict ErrorCode = "GIT_CONFLICT"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_GitUnknownRef ErrorCode = "GIT_UNKNOWN_REF"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_GitSensitiveTokenDetected ErrorCode = "GIT_SENSITIVE_TOKEN_DETECTED"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_GitUrlNotOnAllowList ErrorCode = "GIT_URL_NOT_ON_ALLOW_LIST"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_GitRemoteError ErrorCode = "GIT_REMOTE_ERROR"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_ProjectsOperationTimeout ErrorCode = "PROJECTS_OPERATION_TIMEOUT"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_IpynbFileInRepo ErrorCode = "IPYNB_FILE_IN_REPO"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_InsecurePartnerResponse ErrorCode = "INSECURE_PARTNER_RESPONSE"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_MalformedPartnerResponse ErrorCode = "MALFORMED_PARTNER_RESPONSE"
	ErrorCode_MetastoreDoesNotExist    ErrorCode = "METASTORE_DOES_NOT_EXIST"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_DacDoesNotExist               ErrorCode = "DAC_DOES_NOT_EXIST"
	ErrorCode_CatalogDoesNotExist           ErrorCode = "CATALOG_DOES_NOT_EXIST"
	ErrorCode_SchemaDoesNotExist            ErrorCode = "SCHEMA_DOES_NOT_EXIST"
	ErrorCode_TableDoesNotExist             ErrorCode = "TABLE_DOES_NOT_EXIST"
	ErrorCode_ShareDoesNotExist             ErrorCode = "SHARE_DOES_NOT_EXIST"
	ErrorCode_RecipientDoesNotExist         ErrorCode = "RECIPIENT_DOES_NOT_EXIST"
	ErrorCode_StorageCredentialDoesNotExist ErrorCode = "STORAGE_CREDENTIAL_DOES_NOT_EXIST"
	ErrorCode_ExternalLocationDoesNotExist  ErrorCode = "EXTERNAL_LOCATION_DOES_NOT_EXIST"
	ErrorCode_PrincipalDoesNotExist         ErrorCode = "PRINCIPAL_DOES_NOT_EXIST"
	ErrorCode_ProviderDoesNotExist          ErrorCode = "PROVIDER_DOES_NOT_EXIST"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_MetastoreAlreadyExists ErrorCode = "METASTORE_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_DacAlreadyExists ErrorCode = "DAC_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_CatalogAlreadyExists ErrorCode = "CATALOG_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_SchemaAlreadyExists ErrorCode = "SCHEMA_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_TableAlreadyExists ErrorCode = "TABLE_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_ShareAlreadyExists ErrorCode = "SHARE_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_RecipientAlreadyExists ErrorCode = "RECIPIENT_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_StorageCredentialAlreadyExists ErrorCode = "STORAGE_CREDENTIAL_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_ExternalLocationAlreadyExists ErrorCode = "EXTERNAL_LOCATION_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_ProviderAlreadyExists ErrorCode = "PROVIDER_ALREADY_EXISTS"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_CatalogNotEmpty ErrorCode = "CATALOG_NOT_EMPTY"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_SchemaNotEmpty ErrorCode = "SCHEMA_NOT_EMPTY"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_MetastoreNotEmpty ErrorCode = "METASTORE_NOT_EMPTY"
	// NOTE: Deprecated and kept to maintain backwards compatibility for public APIs
	// that use it, avoid using it in the new APIs, refer error codes listed in the
	// http://go/error-codes.
	ErrorCode_ProviderShareNotAccessible ErrorCode = "PROVIDER_SHARE_NOT_ACCESSIBLE"
)

type SpaceUpdateState string

const (
	SpaceUpdateState_Unspecified SpaceUpdateState = ""
	SpaceUpdateState_NotUpdated  SpaceUpdateState = "NOT_UPDATED"
	SpaceUpdateState_InProgress  SpaceUpdateState = "IN_PROGRESS"
	SpaceUpdateState_Succeeded   SpaceUpdateState = "SUCCEEDED"
	SpaceUpdateState_Failed      SpaceUpdateState = "FAILED"
)

type AppDeployment_Mode string

const (
	AppDeployment_Mode_Unspecified AppDeployment_Mode = ""
	AppDeployment_Mode_Snapshot    AppDeployment_Mode = "SNAPSHOT"
	AppDeployment_Mode_AutoSync    AppDeployment_Mode = "AUTO_SYNC"
)

type AppDeployment_State string

const (
	AppDeployment_State_Unspecified AppDeployment_State = ""
	AppDeployment_State_Succeeded   AppDeployment_State = "SUCCEEDED"
	AppDeployment_State_Failed      AppDeployment_State = "FAILED"
	AppDeployment_State_InProgress  AppDeployment_State = "IN_PROGRESS"
	AppDeployment_State_Cancelled   AppDeployment_State = "CANCELLED"
)

type AppManifest_AppResourceExperimentSpec_ExperimentPermission string

const (
	AppManifest_AppResourceExperimentSpec_ExperimentPermission_Unspecified AppManifest_AppResourceExperimentSpec_ExperimentPermission = ""
	AppManifest_AppResourceExperimentSpec_ExperimentPermission_CanManage   AppManifest_AppResourceExperimentSpec_ExperimentPermission = "CAN_MANAGE"
	AppManifest_AppResourceExperimentSpec_ExperimentPermission_CanEdit     AppManifest_AppResourceExperimentSpec_ExperimentPermission = "CAN_EDIT"
	AppManifest_AppResourceExperimentSpec_ExperimentPermission_CanRead     AppManifest_AppResourceExperimentSpec_ExperimentPermission = "CAN_READ"
)

type AppManifest_AppResourceJobSpec_JobPermission string

const (
	AppManifest_AppResourceJobSpec_JobPermission_Unspecified  AppManifest_AppResourceJobSpec_JobPermission = ""
	AppManifest_AppResourceJobSpec_JobPermission_CanManage    AppManifest_AppResourceJobSpec_JobPermission = "CAN_MANAGE"
	AppManifest_AppResourceJobSpec_JobPermission_IsOwner      AppManifest_AppResourceJobSpec_JobPermission = "IS_OWNER"
	AppManifest_AppResourceJobSpec_JobPermission_CanManageRun AppManifest_AppResourceJobSpec_JobPermission = "CAN_MANAGE_RUN"
	AppManifest_AppResourceJobSpec_JobPermission_CanView      AppManifest_AppResourceJobSpec_JobPermission = "CAN_VIEW"
)

// Permission to grant on the secret scope. Supported permissions are: "READ",
// "WRITE", "MANAGE".
type AppManifest_AppResourceSecretSpec_SecretPermission string

const (
	AppManifest_AppResourceSecretSpec_SecretPermission_Unspecified AppManifest_AppResourceSecretSpec_SecretPermission = ""
	AppManifest_AppResourceSecretSpec_SecretPermission_Read        AppManifest_AppResourceSecretSpec_SecretPermission = "READ"
	AppManifest_AppResourceSecretSpec_SecretPermission_Write       AppManifest_AppResourceSecretSpec_SecretPermission = "WRITE"
	AppManifest_AppResourceSecretSpec_SecretPermission_Manage      AppManifest_AppResourceSecretSpec_SecretPermission = "MANAGE"
)

type AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission string

const (
	AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission_Unspecified AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission = ""
	AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission_CanManage   AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission = "CAN_MANAGE"
	AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission_CanQuery    AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission = "CAN_QUERY"
	AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission_CanView     AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission = "CAN_VIEW"
)

type AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission string

const (
	AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission_Unspecified AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission = ""
	AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission_CanManage   AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission = "CAN_MANAGE"
	AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission_CanUse      AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission = "CAN_USE"
	AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission_IsOwner     AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission = "IS_OWNER"
)

type AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission string

const (
	AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission_Unspecified   AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission = ""
	AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission_ReadVolume    AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission = "READ_VOLUME"
	AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission_WriteVolume   AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission = "WRITE_VOLUME"
	AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission_Manage        AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission = "MANAGE"
	AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission_Select        AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission = "SELECT"
	AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission_Execute       AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission = "EXECUTE"
	AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission_UseConnection AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission = "USE_CONNECTION"
)

type AppManifest_AppResourceUcSecurableSpec_UcSecurableType string

const (
	AppManifest_AppResourceUcSecurableSpec_UcSecurableType_Unspecified AppManifest_AppResourceUcSecurableSpec_UcSecurableType = ""
	AppManifest_AppResourceUcSecurableSpec_UcSecurableType_Volume      AppManifest_AppResourceUcSecurableSpec_UcSecurableType = "VOLUME"
	AppManifest_AppResourceUcSecurableSpec_UcSecurableType_Table       AppManifest_AppResourceUcSecurableSpec_UcSecurableType = "TABLE"
	AppManifest_AppResourceUcSecurableSpec_UcSecurableType_Function    AppManifest_AppResourceUcSecurableSpec_UcSecurableType = "FUNCTION"
	AppManifest_AppResourceUcSecurableSpec_UcSecurableType_Connection  AppManifest_AppResourceUcSecurableSpec_UcSecurableType = "CONNECTION"
)

type AppResourceApp_AppPermission string

const (
	AppResourceApp_AppPermission_Unspecified AppResourceApp_AppPermission = ""
	AppResourceApp_AppPermission_CanUse      AppResourceApp_AppPermission = "CAN_USE"
)

type AppResourceDatabase_DatabasePermission string

const (
	AppResourceDatabase_DatabasePermission_Unspecified         AppResourceDatabase_DatabasePermission = ""
	AppResourceDatabase_DatabasePermission_CanConnectAndCreate AppResourceDatabase_DatabasePermission = "CAN_CONNECT_AND_CREATE"
)

type AppResourceExperiment_ExperimentPermission string

const (
	AppResourceExperiment_ExperimentPermission_Unspecified AppResourceExperiment_ExperimentPermission = ""
	AppResourceExperiment_ExperimentPermission_CanManage   AppResourceExperiment_ExperimentPermission = "CAN_MANAGE"
	AppResourceExperiment_ExperimentPermission_CanEdit     AppResourceExperiment_ExperimentPermission = "CAN_EDIT"
	AppResourceExperiment_ExperimentPermission_CanRead     AppResourceExperiment_ExperimentPermission = "CAN_READ"
)

type AppResourceGenieSpace_GenieSpacePermission string

const (
	AppResourceGenieSpace_GenieSpacePermission_Unspecified AppResourceGenieSpace_GenieSpacePermission = ""
	AppResourceGenieSpace_GenieSpacePermission_CanManage   AppResourceGenieSpace_GenieSpacePermission = "CAN_MANAGE"
	AppResourceGenieSpace_GenieSpacePermission_CanEdit     AppResourceGenieSpace_GenieSpacePermission = "CAN_EDIT"
	AppResourceGenieSpace_GenieSpacePermission_CanRun      AppResourceGenieSpace_GenieSpacePermission = "CAN_RUN"
	AppResourceGenieSpace_GenieSpacePermission_CanView     AppResourceGenieSpace_GenieSpacePermission = "CAN_VIEW"
)

type AppResourceJob_JobPermission string

const (
	AppResourceJob_JobPermission_Unspecified  AppResourceJob_JobPermission = ""
	AppResourceJob_JobPermission_CanManage    AppResourceJob_JobPermission = "CAN_MANAGE"
	AppResourceJob_JobPermission_IsOwner      AppResourceJob_JobPermission = "IS_OWNER"
	AppResourceJob_JobPermission_CanManageRun AppResourceJob_JobPermission = "CAN_MANAGE_RUN"
	AppResourceJob_JobPermission_CanView      AppResourceJob_JobPermission = "CAN_VIEW"
)

type AppResourcePostgres_PostgresPermission string

const (
	AppResourcePostgres_PostgresPermission_Unspecified         AppResourcePostgres_PostgresPermission = ""
	AppResourcePostgres_PostgresPermission_CanConnectAndCreate AppResourcePostgres_PostgresPermission = "CAN_CONNECT_AND_CREATE"
)

// Permission to grant on the secret scope. Supported permissions are: "READ",
// "WRITE", "MANAGE".
type AppResourceSecret_SecretPermission string

const (
	AppResourceSecret_SecretPermission_Unspecified AppResourceSecret_SecretPermission = ""
	AppResourceSecret_SecretPermission_Read        AppResourceSecret_SecretPermission = "READ"
	AppResourceSecret_SecretPermission_Write       AppResourceSecret_SecretPermission = "WRITE"
	AppResourceSecret_SecretPermission_Manage      AppResourceSecret_SecretPermission = "MANAGE"
)

type AppResourceServingEndpoint_ServingEndpointPermission string

const (
	AppResourceServingEndpoint_ServingEndpointPermission_Unspecified AppResourceServingEndpoint_ServingEndpointPermission = ""
	AppResourceServingEndpoint_ServingEndpointPermission_CanManage   AppResourceServingEndpoint_ServingEndpointPermission = "CAN_MANAGE"
	AppResourceServingEndpoint_ServingEndpointPermission_CanQuery    AppResourceServingEndpoint_ServingEndpointPermission = "CAN_QUERY"
	AppResourceServingEndpoint_ServingEndpointPermission_CanView     AppResourceServingEndpoint_ServingEndpointPermission = "CAN_VIEW"
)

type AppResourceSqlWarehouse_SqlWarehousePermission string

const (
	AppResourceSqlWarehouse_SqlWarehousePermission_Unspecified AppResourceSqlWarehouse_SqlWarehousePermission = ""
	AppResourceSqlWarehouse_SqlWarehousePermission_CanManage   AppResourceSqlWarehouse_SqlWarehousePermission = "CAN_MANAGE"
	AppResourceSqlWarehouse_SqlWarehousePermission_CanUse      AppResourceSqlWarehouse_SqlWarehousePermission = "CAN_USE"
	AppResourceSqlWarehouse_SqlWarehousePermission_IsOwner     AppResourceSqlWarehouse_SqlWarehousePermission = "IS_OWNER"
)

type AppResourceUcSecurable_UcSecurablePermission string

const (
	AppResourceUcSecurable_UcSecurablePermission_Unspecified   AppResourceUcSecurable_UcSecurablePermission = ""
	AppResourceUcSecurable_UcSecurablePermission_ReadVolume    AppResourceUcSecurable_UcSecurablePermission = "READ_VOLUME"
	AppResourceUcSecurable_UcSecurablePermission_WriteVolume   AppResourceUcSecurable_UcSecurablePermission = "WRITE_VOLUME"
	AppResourceUcSecurable_UcSecurablePermission_Select        AppResourceUcSecurable_UcSecurablePermission = "SELECT"
	AppResourceUcSecurable_UcSecurablePermission_Execute       AppResourceUcSecurable_UcSecurablePermission = "EXECUTE"
	AppResourceUcSecurable_UcSecurablePermission_UseConnection AppResourceUcSecurable_UcSecurablePermission = "USE_CONNECTION"
	AppResourceUcSecurable_UcSecurablePermission_Modify        AppResourceUcSecurable_UcSecurablePermission = "MODIFY"
)

type AppResourceUcSecurable_UcSecurableType string

const (
	AppResourceUcSecurable_UcSecurableType_Unspecified AppResourceUcSecurable_UcSecurableType = ""
	AppResourceUcSecurable_UcSecurableType_Volume      AppResourceUcSecurable_UcSecurableType = "VOLUME"
	AppResourceUcSecurable_UcSecurableType_Table       AppResourceUcSecurable_UcSecurableType = "TABLE"
	AppResourceUcSecurable_UcSecurableType_Function    AppResourceUcSecurable_UcSecurableType = "FUNCTION"
	AppResourceUcSecurable_UcSecurableType_Connection  AppResourceUcSecurable_UcSecurableType = "CONNECTION"
)

type AppUpdate_UpdateStatus_UpdateState string

const (
	AppUpdate_UpdateStatus_UpdateState_Unspecified AppUpdate_UpdateStatus_UpdateState = ""
	AppUpdate_UpdateStatus_UpdateState_NotUpdated  AppUpdate_UpdateStatus_UpdateState = "NOT_UPDATED"
	AppUpdate_UpdateStatus_UpdateState_InProgress  AppUpdate_UpdateStatus_UpdateState = "IN_PROGRESS"
	AppUpdate_UpdateStatus_UpdateState_Succeeded   AppUpdate_UpdateStatus_UpdateState = "SUCCEEDED"
	AppUpdate_UpdateStatus_UpdateState_Failed      AppUpdate_UpdateStatus_UpdateState = "FAILED"
)

type ApplicationStatus_ApplicationState string

const (
	ApplicationStatus_ApplicationState_Unspecified ApplicationStatus_ApplicationState = ""
	ApplicationStatus_ApplicationState_Deploying   ApplicationStatus_ApplicationState = "DEPLOYING"
	ApplicationStatus_ApplicationState_Running     ApplicationStatus_ApplicationState = "RUNNING"
	ApplicationStatus_ApplicationState_Crashed     ApplicationStatus_ApplicationState = "CRASHED"
	ApplicationStatus_ApplicationState_Unavailable ApplicationStatus_ApplicationState = "UNAVAILABLE"
)

type ComputeStatus_ComputeState string

const (
	ComputeStatus_ComputeState_Unspecified ComputeStatus_ComputeState = ""
	ComputeStatus_ComputeState_Error       ComputeStatus_ComputeState = "ERROR"
	ComputeStatus_ComputeState_Deleting    ComputeStatus_ComputeState = "DELETING"
	ComputeStatus_ComputeState_Starting    ComputeStatus_ComputeState = "STARTING"
	ComputeStatus_ComputeState_Stopping    ComputeStatus_ComputeState = "STOPPING"
	ComputeStatus_ComputeState_Updating    ComputeStatus_ComputeState = "UPDATING"
	ComputeStatus_ComputeState_Stopped     ComputeStatus_ComputeState = "STOPPED"
	ComputeStatus_ComputeState_Active      ComputeStatus_ComputeState = "ACTIVE"
)

type SpaceStatus_SpaceState string

const (
	SpaceStatus_SpaceState_Unspecified   SpaceStatus_SpaceState = ""
	SpaceStatus_SpaceState_SpaceCreating SpaceStatus_SpaceState = "SPACE_CREATING"
	SpaceStatus_SpaceState_SpaceActive   SpaceStatus_SpaceState = "SPACE_ACTIVE"
	SpaceStatus_SpaceState_SpaceError    SpaceStatus_SpaceState = "SPACE_ERROR"
	SpaceStatus_SpaceState_SpaceDeleting SpaceStatus_SpaceState = "SPACE_DELETING"
	SpaceStatus_SpaceState_SpaceDeleted  SpaceStatus_SpaceState = "SPACE_DELETED"
	SpaceStatus_SpaceState_SpaceUpdating SpaceStatus_SpaceState = "SPACE_UPDATING"
)

// Databricks Error that is returned by all Databricks APIs..
type ApiError struct {
	ErrorCode  ErrorCode
	Message    *string
	StackTrace *string
	Details    []json.RawMessage
}

type App struct {
	// The name of the app. The name must contain only lowercase alphanumeric
	// characters and hyphens. It must be unique within the workspace.
	Name *string `fieldmask:"name"`
	// The description of the app.
	Description   *string            `fieldmask:"description"`
	ComputeStatus *ComputeStatus     `fieldmask:"compute_status"`
	AppStatus     *ApplicationStatus `fieldmask:"app_status"`
	// The URL of the app once it is deployed.
	Url *string `fieldmask:"url"`
	// The active deployment of the app. A deployment is considered active when it
	// has been deployed to the app compute.
	ActiveDeployment *AppDeployment `fieldmask:"active_deployment"`
	// The creation time of the app. Formatted timestamp in ISO 6801.
	CreateTime *types.Time `fieldmask:"create_time"`
	// The email of the user that created the app.
	Creator *string `fieldmask:"creator"`
	// The update time of the app. Formatted timestamp in ISO 6801.
	UpdateTime *types.Time `fieldmask:"update_time"`
	// The email of the user that last updated the app.
	Updater *string `fieldmask:"updater"`
	// The pending deployment of the app. A deployment is considered pending when it
	// is being prepared for deployment to the app compute.
	PendingDeployment *AppDeployment `fieldmask:"pending_deployment"`
	// Resources for the app.
	Resources            []AppResource `fieldmask:"resources"`
	ServicePrincipalId   *int64        `fieldmask:"service_principal_id"`
	ServicePrincipalName *string       `fieldmask:"service_principal_name"`
	// The default workspace file system path of the source code from which app
	// deployment are created. This field tracks the workspace source code path of
	// the last active deployment.
	DefaultSourceCodePath *string `fieldmask:"default_source_code_path"`
	// The Git source of the app's most recent active deployment, including the
	// repository configuration and the resolved reference. Populated by the system
	// after a Git-based deployment and used as the default reference when automatic
	// deployments are enabled.
	DefaultGitSource         *GitSource `fieldmask:"default_git_source"`
	BudgetPolicyId           *string    `fieldmask:"budget_policy_id"`
	EffectiveBudgetPolicyId  *string    `fieldmask:"effective_budget_policy_id"`
	ServicePrincipalClientId *string    `fieldmask:"service_principal_client_id"`
	UserApiScopes            []string   `fieldmask:"user_api_scopes"`
	// The unique identifier of the app.
	Id *string `fieldmask:"id"`
	// The effective api scopes granted to the user access token.
	EffectiveUserApiScopes []string    `fieldmask:"effective_user_api_scopes"`
	Oauth2AppIntegrationId *string     `fieldmask:"oauth2_app_integration_id"`
	Oauth2AppClientId      *string     `fieldmask:"oauth2_app_client_id"`
	ComputeSize            ComputeSize `fieldmask:"compute_size"`
	UsagePolicyId          *string     `fieldmask:"usage_policy_id"`
	EffectiveUsagePolicyId *string     `fieldmask:"effective_usage_policy_id"`
	// Minimum number of app instances. Must be set together with
	// `compute_max_instances`.
	ComputeMinInstances *int `fieldmask:"compute_min_instances"`
	// Maximum number of app instances. Must be set together with
	// `compute_min_instances`.
	ComputeMaxInstances *int `fieldmask:"compute_max_instances"`
	// Git repository configuration for app deployments. When specified, deployments
	// can reference code from this repository by providing only the git reference
	// (branch, tag, or commit).
	GitRepository               *GitRepository               `fieldmask:"git_repository"`
	TelemetryExportDestinations []TelemetryExportDestination `fieldmask:"telemetry_export_destinations"`
	// The URL of the thumbnail image for the app.
	ThumbnailUrl *string `fieldmask:"thumbnail_url"`
	// Name of the space this app belongs to.
	Space            *string `fieldmask:"space"`
	DeploymentSource isApp_DeploymentSource
	// Forward the user's access token to the app. Requires stopping and starting
	// app compute to take effect.
	ForwardUserAccessToken *bool                                   `fieldmask:"forward_user_access_token"`
	_                      [0]appDeploymentSourceFieldMaskMetadata `fieldmask_oneof:"DeploymentSource"`
}

type isApp_DeploymentSource interface {
	isApp_DeploymentSource()
}

// App_DeploymentSource_SourceCodePath selects SourceCodePath for App.DeploymentSource.
type App_DeploymentSource_SourceCodePath struct {
	SourceCodePath string `fieldmask:"source_code_path"`
}

func (*App_DeploymentSource_SourceCodePath) isApp_DeploymentSource() {}

// App_DeploymentSource_GitSource selects GitSource for App.DeploymentSource.
// The Git source to deploy from, specifying the reference to check out (branch,
// tag, or commit) and an optional path to the app source code within the
// repository configured in git_repository.
type App_DeploymentSource_GitSource struct {
	GitSource GitSource `fieldmask:"git_source"`
}

func (*App_DeploymentSource_GitSource) isApp_DeploymentSource() {}

type appDeploymentSourceFieldMaskMetadata struct {
	*App_DeploymentSource_SourceCodePath
	*App_DeploymentSource_GitSource
}

type AppDeployment struct {
	// The unique id of the deployment.
	DeploymentId *string `fieldmask:"deployment_id"`
	// The workspace file system path of the source code used to create the app
	// deployment. This is different from `deployment_artifacts.source_code_path`,
	// which is the path used by the deployed app. The former refers to the original
	// source code location of the app in the workspace during deployment creation,
	// whereas the latter provides a system generated stable snapshotted source code
	// path used by the deployment.
	SourceCodePath *string `fieldmask:"source_code_path"`
	// Git repository to use as the source for the app deployment.
	GitSource *GitSource `fieldmask:"git_source"`
	// The mode of which the deployment will manage the source code.
	Mode AppDeployment_Mode `fieldmask:"mode"`
	// The deployment artifacts for an app.
	DeploymentArtifacts *AppDeploymentArtifacts `fieldmask:"deployment_artifacts"`
	// Status and status message of the deployment
	Status *AppDeploymentStatus `fieldmask:"status"`
	// The creation time of the deployment. Formatted timestamp in ISO 6801.
	CreateTime *types.Time `fieldmask:"create_time"`
	// The email of the user creates the deployment.
	Creator *string `fieldmask:"creator"`
	// The update time of the deployment. Formatted timestamp in ISO 6801.
	UpdateTime *types.Time `fieldmask:"update_time"`
	// The command with which to run the app. This will override the command
	// specified in the app.yaml file.
	Command []string `fieldmask:"command"`
	// The environment variables to set in the app runtime environment. This will
	// override the environment variables specified in the app.yaml file.
	EnvVars []EnvVar `fieldmask:"env_vars"`
}

type AppDeploymentArtifacts struct {
	// The snapshotted workspace file system path of the source code loaded by the
	// deployed app.
	SourceCodePath *string `fieldmask:"source_code_path"`
}

type AppDeploymentStatus struct {
	// State of the deployment.
	State AppDeployment_State `fieldmask:"state"`
	// Message corresponding with the deployment state.
	Message *string `fieldmask:"message"`
}

// App manifest definition.
type AppManifest struct {
	// The manifest schema version, for now only 1 is allowed
	Version *int
	// Name of the app defined by manifest author / publisher
	Name *string
	// Description of the app defined by manifest author / publisher
	Description   *string
	ResourceSpecs []AppManifest_AppResourceSpec
}

type AppManifest_AppResourceExperimentSpec struct {
	Permission AppManifest_AppResourceExperimentSpec_ExperimentPermission
}

type AppManifest_AppResourceJobSpec struct {
	// Permissions to grant on the Job. Supported permissions are: "CAN_MANAGE",
	// "IS_OWNER", "CAN_MANAGE_RUN", "CAN_VIEW".
	Permission AppManifest_AppResourceJobSpec_JobPermission
}

type AppManifest_AppResourceSecretSpec struct {
	// Permission to grant on the secret scope. For secrets, only one permission is
	// allowed. Permission must be one of: "READ", "WRITE", "MANAGE".
	Permission AppManifest_AppResourceSecretSpec_SecretPermission
}

type AppManifest_AppResourceServingEndpointSpec struct {
	// Permission to grant on the serving endpoint. Supported permissions are:
	// "CAN_MANAGE", "CAN_QUERY", "CAN_VIEW".
	Permission AppManifest_AppResourceServingEndpointSpec_ServingEndpointPermission
}

// AppResource related fields are copied from app.proto but excludes resource
// identifiers (e.g. name, id, key, scope, etc.).
type AppManifest_AppResourceSpec struct {
	// Name of the App Resource.
	Name *string
	// Description of the App Resource.
	Description *string
	Resource    isAppManifest_AppResourceSpec_Resource
}

type isAppManifest_AppResourceSpec_Resource interface {
	isAppManifest_AppResourceSpec_Resource()
}

// AppManifest_AppResourceSpec_Resource_SecretSpec selects SecretSpec for AppManifest_AppResourceSpec.Resource.
type AppManifest_AppResourceSpec_Resource_SecretSpec struct {
	SecretSpec AppManifest_AppResourceSecretSpec
}

func (*AppManifest_AppResourceSpec_Resource_SecretSpec) isAppManifest_AppResourceSpec_Resource() {}

// AppManifest_AppResourceSpec_Resource_SqlWarehouseSpec selects SqlWarehouseSpec for AppManifest_AppResourceSpec.Resource.
type AppManifest_AppResourceSpec_Resource_SqlWarehouseSpec struct {
	SqlWarehouseSpec AppManifest_AppResourceSqlWarehouseSpec
}

func (*AppManifest_AppResourceSpec_Resource_SqlWarehouseSpec) isAppManifest_AppResourceSpec_Resource() {
}

// AppManifest_AppResourceSpec_Resource_ServingEndpointSpec selects ServingEndpointSpec for AppManifest_AppResourceSpec.Resource.
type AppManifest_AppResourceSpec_Resource_ServingEndpointSpec struct {
	ServingEndpointSpec AppManifest_AppResourceServingEndpointSpec
}

func (*AppManifest_AppResourceSpec_Resource_ServingEndpointSpec) isAppManifest_AppResourceSpec_Resource() {
}

// AppManifest_AppResourceSpec_Resource_JobSpec selects JobSpec for AppManifest_AppResourceSpec.Resource.
type AppManifest_AppResourceSpec_Resource_JobSpec struct {
	JobSpec AppManifest_AppResourceJobSpec
}

func (*AppManifest_AppResourceSpec_Resource_JobSpec) isAppManifest_AppResourceSpec_Resource() {}

// AppManifest_AppResourceSpec_Resource_UcSecurableSpec selects UcSecurableSpec for AppManifest_AppResourceSpec.Resource.
type AppManifest_AppResourceSpec_Resource_UcSecurableSpec struct {
	UcSecurableSpec AppManifest_AppResourceUcSecurableSpec
}

func (*AppManifest_AppResourceSpec_Resource_UcSecurableSpec) isAppManifest_AppResourceSpec_Resource() {
}

// AppManifest_AppResourceSpec_Resource_ExperimentSpec selects ExperimentSpec for AppManifest_AppResourceSpec.Resource.
type AppManifest_AppResourceSpec_Resource_ExperimentSpec struct {
	ExperimentSpec AppManifest_AppResourceExperimentSpec
}

func (*AppManifest_AppResourceSpec_Resource_ExperimentSpec) isAppManifest_AppResourceSpec_Resource() {
}

type AppManifest_AppResourceSqlWarehouseSpec struct {
	// Permission to grant on the SQL warehouse. Supported permissions are:
	// "CAN_MANAGE", "CAN_USE", "IS_OWNER".
	Permission AppManifest_AppResourceSqlWarehouseSpec_SqlWarehousePermission
}

type AppManifest_AppResourceUcSecurableSpec struct {
	SecurableType AppManifest_AppResourceUcSecurableSpec_UcSecurableType
	Permission    AppManifest_AppResourceUcSecurableSpec_UcSecurablePermission
}

type AppResource struct {
	// Name of the App Resource.
	Name *string
	// Description of the App Resource.
	Description *string
	Resource    isAppResource_Resource
}

type isAppResource_Resource interface {
	isAppResource_Resource()
}

// AppResource_Resource_Secret selects Secret for AppResource.Resource.
type AppResource_Resource_Secret struct {
	Secret AppResourceSecret
}

func (*AppResource_Resource_Secret) isAppResource_Resource() {}

// AppResource_Resource_SqlWarehouse selects SqlWarehouse for AppResource.Resource.
type AppResource_Resource_SqlWarehouse struct {
	SqlWarehouse AppResourceSqlWarehouse
}

func (*AppResource_Resource_SqlWarehouse) isAppResource_Resource() {}

// AppResource_Resource_ServingEndpoint selects ServingEndpoint for AppResource.Resource.
type AppResource_Resource_ServingEndpoint struct {
	ServingEndpoint AppResourceServingEndpoint
}

func (*AppResource_Resource_ServingEndpoint) isAppResource_Resource() {}

// AppResource_Resource_Job selects Job for AppResource.Resource.
type AppResource_Resource_Job struct {
	Job AppResourceJob
}

func (*AppResource_Resource_Job) isAppResource_Resource() {}

// AppResource_Resource_UcSecurable selects UcSecurable for AppResource.Resource.
type AppResource_Resource_UcSecurable struct {
	UcSecurable AppResourceUcSecurable
}

func (*AppResource_Resource_UcSecurable) isAppResource_Resource() {}

// AppResource_Resource_Database selects Database for AppResource.Resource.
type AppResource_Resource_Database struct {
	Database AppResourceDatabase
}

func (*AppResource_Resource_Database) isAppResource_Resource() {}

// AppResource_Resource_GenieSpace selects GenieSpace for AppResource.Resource.
type AppResource_Resource_GenieSpace struct {
	GenieSpace AppResourceGenieSpace
}

func (*AppResource_Resource_GenieSpace) isAppResource_Resource() {}

// AppResource_Resource_Experiment selects Experiment for AppResource.Resource.
type AppResource_Resource_Experiment struct {
	Experiment AppResourceExperiment
}

func (*AppResource_Resource_Experiment) isAppResource_Resource() {}

// AppResource_Resource_App selects App for AppResource.Resource.
type AppResource_Resource_App struct {
	App AppResourceApp
}

func (*AppResource_Resource_App) isAppResource_Resource() {}

// AppResource_Resource_Postgres selects Postgres for AppResource.Resource.
type AppResource_Resource_Postgres struct {
	Postgres AppResourcePostgres
}

func (*AppResource_Resource_Postgres) isAppResource_Resource() {}

type AppResourceApp struct {
	Name       *string
	Permission AppResourceApp_AppPermission
}

type AppResourceDatabase struct {
	InstanceName *string
	DatabaseName *string
	Permission   AppResourceDatabase_DatabasePermission
}

type AppResourceExperiment struct {
	ExperimentId *string
	Permission   AppResourceExperiment_ExperimentPermission
}

type AppResourceGenieSpace struct {
	Name       *string
	SpaceId    *string
	Permission AppResourceGenieSpace_GenieSpacePermission
}

type AppResourceJob struct {
	// Id of the job to grant permission on.
	Id *string
	// Permissions to grant on the Job. Supported permissions are: "CAN_MANAGE",
	// "IS_OWNER", "CAN_MANAGE_RUN", "CAN_VIEW".
	Permission AppResourceJob_JobPermission
}

type AppResourcePostgres struct {
	Branch     *string
	Database   *string
	Permission AppResourcePostgres_PostgresPermission
}

type AppResourceSecret struct {
	// Scope of the secret to grant permission on.
	Scope *string
	// Key of the secret to grant permission on.
	Key *string
	// Permission to grant on the secret scope. For secrets, only one permission is
	// allowed. Permission must be one of: "READ", "WRITE", "MANAGE".
	Permission AppResourceSecret_SecretPermission
}

type AppResourceServingEndpoint struct {
	// Name of the serving endpoint to grant permission on.
	Name *string
	// Permission to grant on the serving endpoint. Supported permissions are:
	// "CAN_MANAGE", "CAN_QUERY", "CAN_VIEW".
	Permission AppResourceServingEndpoint_ServingEndpointPermission
}

type AppResourceSqlWarehouse struct {
	// Id of the SQL warehouse to grant permission on.
	Id *string
	// Permission to grant on the SQL warehouse. Supported permissions are:
	// "CAN_MANAGE", "CAN_USE", "IS_OWNER".
	Permission AppResourceSqlWarehouse_SqlWarehousePermission
}

type AppResourceUcSecurable struct {
	SecurableFullName *string
	SecurableType     AppResourceUcSecurable_UcSecurableType
	Permission        AppResourceUcSecurable_UcSecurablePermission
	// The securable kind from Unity Catalog. See
	// https://docs.databricks.com/api/workspace/tables/get#securable_kind_manifest-securable_kind.
	SecurableKind *string
}

// The thumbnail for an app..
type AppThumbnail struct {
	// The thumbnail image bytes.
	Thumbnail []byte
}

type AppUpdate struct {
	Status         *AppUpdate_UpdateStatus
	Description    *string
	BudgetPolicyId *string
	Resources      []AppResource
	UserApiScopes  []string
	ComputeSize    ComputeSize
	UsagePolicyId  *string
	// Minimum number of app instances. Must be set together with
	// `compute_max_instances`.
	ComputeMinInstances *int
	// Maximum number of app instances. Must be set together with
	// `compute_min_instances`.
	ComputeMaxInstances *int
	GitRepository       *GitRepository
	// Forward the user's access token to the app. Requires stopping and starting
	// app compute to take effect.
	ForwardUserAccessToken *bool
}

type AppUpdate_UpdateStatus struct {
	State   AppUpdate_UpdateStatus_UpdateState
	Message *string
}

type ApplicationStatus struct {
	// State of the application.
	State ApplicationStatus_ApplicationState `fieldmask:"state"`
	// Application status message
	Message *string `fieldmask:"message"`
	// The number of running instances of this application.
	RunningInstances *int `fieldmask:"running_instances"`
}

type AsyncUpdateAppRequest struct {
	App        *App
	UpdateMask *types.FieldMask[App]
	AppName    *string
}

type ComputeStatus struct {
	// State of the app compute.
	State ComputeStatus_ComputeState `fieldmask:"state"`
	// Compute status message
	Message *string `fieldmask:"message"`
	// The number of compute instances currently serving requests for this
	// application. An instance is considered active if it is reachable and ready to
	// handle requests.
	ActiveInstances *int `fieldmask:"active_instances"`
}

type CreateAppDeploymentRequest struct {
	// The name of the app.
	AppName *string
	// The app deployment configuration.
	AppDeployment *AppDeployment
}

type CreateAppRequest struct {
	App *App
	// If true, the app will not be started after creation.
	NoCompute *bool
}

type CreateCustomTemplateRequest struct {
	Template *CustomTemplate
}

type CreateSpaceRequest struct {
	Space *Space
}

type CustomTemplate struct {
	// The name of the template. It must contain only alphanumeric characters,
	// hyphens, underscores, and whitespaces. It must be unique within the
	// workspace.
	Name *string
	// The description of the template.
	Description *string
	// The Git repository URL that the template resides in.
	GitRepo *string
	// The path to the template within the Git repository.
	Path *string
	// The manifest of the template. It defines fields and default values when
	// installing the template.
	Manifest *AppManifest
	// The Git provider of the template.
	GitProvider *string
	Creator     *string
}

type DeleteAppRequest struct {
	// The name of the app.
	Name *string
}

type DeleteAppThumbnailRequest struct {
	// The name of the app.
	Name *string
}

type DeleteCustomTemplateRequest struct {
	// The name of the custom template.
	Name *string
}

type DeleteSpaceRequest struct {
	// The name of the app space.
	Name *string
}

type EnvVar struct {
	// The name of the environment variable.
	Name   *string
	Source isEnvVar_Source
}

type isEnvVar_Source interface {
	isEnvVar_Source()
}

// EnvVar_Source_Value selects Value for EnvVar.Source.
// The value for the environment variable.
type EnvVar_Source_Value struct {
	Value string
}

func (*EnvVar_Source_Value) isEnvVar_Source() {}

// EnvVar_Source_ValueFrom selects ValueFrom for EnvVar.Source.
// The name of an external <Databricks> resource that contains the value, such
// as a secret or a database table.
type EnvVar_Source_ValueFrom struct {
	ValueFrom string
}

func (*EnvVar_Source_ValueFrom) isEnvVar_Source() {}

type GetAppDeploymentRequest struct {
	// The name of the app.
	AppName *string
	// The unique id of the deployment.
	DeploymentId *string
}

type GetAppRequest struct {
	// The name of the app.
	Name *string
}

type GetAppUpdateRequest struct {
	// The name of the app.
	AppName *string
}

type GetCustomTemplateRequest struct {
	// The name of the custom template.
	Name *string
}

// The request message for `GetOperation` method..
type GetOperationRequest struct {
	// The name of the operation resource.
	Name *string
}

type GetSpaceRequest struct {
	// The name of the app space.
	Name *string
}

// Git repository configuration specifying the location of the repository..
type GitRepository struct {
	// URL of the Git repository.
	Url *string `fieldmask:"url"`
	// Git provider. Case insensitive. Supported values: gitHub, gitHubEnterprise,
	// bitbucketCloud, bitbucketServer, azureDevOpsServices, gitLab,
	// gitLabEnterpriseEdition, awsCodeCommit.
	Provider *string `fieldmask:"provider"`
	// When true, automatically deploys the app on push events to the branch
	// configured in the app's deployment_source.git_source.
	AutoDeploy *bool `fieldmask:"auto_deploy"`
	// ID of a personal access token Git credential owned by the caller, used to
	// grant the app's service principal access to this repository.
	CallerCredentialId *int64 `fieldmask:"caller_credential_id"`
}

// Complete git source specification including repository location and
// reference..
type GitSource struct {
	// Git repository configuration. Populated from the app's git_repository
	// configuration.
	GitRepository *GitRepository `fieldmask:"git_repository"`
	// Git reference to checkout. Mutually exclusive: branch, tag, or commit.
	Reference isGitSource_Reference
	// Relative path to the app source code within the Git repository. If not
	// specified, the root of the repository is used.
	SourceCodePath *string `fieldmask:"source_code_path"`
	// The resolved commit SHA that was actually used for the deployment. This is
	// populated by the system after resolving the reference (branch, tag, or
	// commit). If commit is specified directly, this will match commit. If a branch
	// or tag is specified, this contains the commit SHA that the branch or tag
	// pointed to at deployment time.
	ResolvedCommit *string                                `fieldmask:"resolved_commit"`
	_              [0]gitSourceReferenceFieldMaskMetadata `fieldmask_oneof:"Reference"`
}

type isGitSource_Reference interface {
	isGitSource_Reference()
}

// GitSource_Reference_Branch selects Branch for GitSource.Reference.
// Git branch to checkout.
type GitSource_Reference_Branch struct {
	Branch string `fieldmask:"branch"`
}

func (*GitSource_Reference_Branch) isGitSource_Reference() {}

// GitSource_Reference_Tag selects Tag for GitSource.Reference.
// Git tag to checkout.
type GitSource_Reference_Tag struct {
	Tag string `fieldmask:"tag"`
}

func (*GitSource_Reference_Tag) isGitSource_Reference() {}

// GitSource_Reference_Commit selects Commit for GitSource.Reference.
// Git commit SHA to checkout.
type GitSource_Reference_Commit struct {
	Commit string `fieldmask:"commit"`
}

func (*GitSource_Reference_Commit) isGitSource_Reference() {}

type gitSourceReferenceFieldMaskMetadata struct {
	*GitSource_Reference_Branch
	*GitSource_Reference_Tag
	*GitSource_Reference_Commit
}

type ListAppDeploymentsRequest struct {
	// The name of the app.
	AppName *string
	// Pagination token to go to the next page of apps. Requests first page if
	// absent.
	PageToken *string
	// Upper bound for items returned.
	PageSize *int
}

type ListAppDeploymentsResponse struct {
	// Deployment history of the app.
	AppDeployments []AppDeployment
	// Pagination token to request the next page of apps.
	NextPageToken *string
}

// Request to list all apps deployed in the workspace.
type ListAppsRequest struct {
	// Pagination token to go to the next page of apps. Requests first page if
	// absent.
	PageToken *string
	// Upper bound for items returned.
	PageSize *int
	// Filter apps by app space name. When specified, only apps belonging to this
	// space are returned.
	Space *string
}

type ListAppsResponse struct {
	Apps []App
	// Pagination token to request the next page of apps.
	NextPageToken *string
}

type ListCustomTemplatesRequest struct {
	// Pagination token to go to the next page of custom templates. Requests first
	// page if absent.
	PageToken *string
	// Upper bound for items returned.
	PageSize *int
}

type ListCustomTemplatesResponse struct {
	Templates []CustomTemplate
	// Pagination token to request the next page of custom templates.
	NextPageToken *string
}

type ListSpacesRequest struct {
	// Pagination token to go to the next page of app spaces. Requests first page if
	// absent.
	PageToken *string
	// Upper bound for items returned.
	PageSize *int
}

type ListSpacesResponse struct {
	Spaces []Space
	// Pagination token to request the next page of app spaces.
	NextPageToken *string
}

// This resource represents a long-running operation that is the result of a
// network API call..
type Operation struct {
	// The server-assigned name, which is only unique within the same service that
	// originally returns it. If you use the default HTTP mapping, the `name` should
	// be a resource name ending with `operations/{unique_id}`.
	Name *string
	// Service-specific metadata associated with the operation. It typically
	// contains progress information and common metadata such as create time. Some
	// services might not provide such metadata.
	Metadata json.RawMessage
	// If the value is `false`, it means the operation is still in progress. If
	// `true`, the operation is completed, and either `error` or `response` is
	// available.
	Done *bool
	// The operation result, which can be either an `error` or a valid `response`.
	// If `done` == `false`, neither `error` nor `response` is set. If `done` ==
	// `true`, exactly one of `error` or `response` can be set. Some services might
	// not provide the result.
	Result isOperation_Result
}

type isOperation_Result interface {
	isOperation_Result()
}

// Operation_Result_Error selects Error for Operation.Result.
// The error result of the operation in case of failure or cancellation.
type Operation_Result_Error struct {
	Error ApiError
}

func (*Operation_Result_Error) isOperation_Result() {}

// Operation_Result_Response selects Response for Operation.Result.
// The normal, successful response of the operation.
type Operation_Result_Response struct {
	Response json.RawMessage
}

func (*Operation_Result_Response) isOperation_Result() {}

type Space struct {
	// The name of the app space. The name must contain only lowercase alphanumeric
	// characters and hyphens. It must be unique within the workspace.
	Name *string `fieldmask:"name"`
	// The description of the app space.
	Description *string `fieldmask:"description"`
	// The status of the app space.
	Status *SpaceStatus `fieldmask:"status"`
	// The unique identifier of the app space.
	Id *string `fieldmask:"id"`
	// The creation time of the app space. Formatted timestamp in ISO 6801.
	CreateTime *types.Time `fieldmask:"create_time"`
	// The email of the user that created the app space.
	Creator *string `fieldmask:"creator"`
	// The update time of the app space. Formatted timestamp in ISO 6801.
	UpdateTime *types.Time `fieldmask:"update_time"`
	// The email of the user that last updated the app space.
	Updater *string `fieldmask:"updater"`
	// Resources for the app space. Resources configured at the space level are
	// available to all apps in the space.
	Resources []AppResource `fieldmask:"resources"`
	// OAuth scopes for apps in the space.
	UserApiScopes []string `fieldmask:"user_api_scopes"`
	// The effective api scopes granted to the user access token.
	EffectiveUserApiScopes []string `fieldmask:"effective_user_api_scopes"`
	// The service principal ID for the app space.
	ServicePrincipalId *int64 `fieldmask:"service_principal_id"`
	// The service principal name for the app space.
	ServicePrincipalName *string `fieldmask:"service_principal_name"`
	// The service principal client ID for the app space.
	ServicePrincipalClientId *string `fieldmask:"service_principal_client_id"`
	// The usage policy ID for managing cost at the space level.
	UsagePolicyId *string `fieldmask:"usage_policy_id"`
	// The effective usage policy ID used by apps in the space.
	EffectiveUsagePolicyId *string `fieldmask:"effective_usage_policy_id"`
	// The group whose permissions users assume via Role Authorization for apps in
	// this space. When set, user tokens assume the role of this group instead of
	// doing regular obo token downscoping. Set only at space creation.
	AssumeGroupId *string `fieldmask:"assume_group_id"`
}

type SpaceStatus struct {
	// The state of the app space.
	State SpaceStatus_SpaceState `fieldmask:"state"`
	// Message providing context about the current state.
	Message *string `fieldmask:"message"`
}

// Tracks app space update information..
type SpaceUpdate struct {
	Status        *SpaceUpdateStatus
	Description   *string
	Resources     []AppResource
	UserApiScopes []string
	UsagePolicyId *string
}

// Status of an app space update operation.
type SpaceUpdateStatus struct {
	State   SpaceUpdateState
	Message *string
}

type StartAppRequest struct {
	// The name of the app.
	Name *string
}

type StopAppRequest struct {
	// The name of the app.
	Name *string
}

// A single telemetry export destination with its configuration and status..
type TelemetryExportDestination struct {
	// Destination type and configuration (writable).
	Destination isTelemetryExportDestination_Destination
}

type isTelemetryExportDestination_Destination interface {
	isTelemetryExportDestination_Destination()
}

// TelemetryExportDestination_Destination_UnityCatalog selects UnityCatalog for TelemetryExportDestination.Destination.
type TelemetryExportDestination_Destination_UnityCatalog struct {
	UnityCatalog UnityCatalog
}

func (*TelemetryExportDestination_Destination_UnityCatalog) isTelemetryExportDestination_Destination() {
}

// Unity Catalog Destinations for OTEL telemetry export..
type UnityCatalog struct {
	// Unity Catalog table for OTEL logs.
	LogsTable *string
	// Unity Catalog table for OTEL metrics.
	MetricsTable *string
	// Unity Catalog table for OTEL traces (spans).
	TracesTable *string
}

type UpdateAppRequest struct {
	App *App
}

type UpdateAppThumbnailRequest struct {
	// The name of the app.
	Name *string
	// The app thumbnail to set.
	AppThumbnail *AppThumbnail
}

type UpdateCustomTemplateRequest struct {
	Template *CustomTemplate
}

type UpdateSpaceRequest struct {
	Space      *Space
	UpdateMask *types.FieldMask[Space]
}

// Error returns the LRO error code and message.
func (e *ApiError) Error() string {
	message := "unknown error"
	if e.Message != nil && *e.Message != "" {
		message = *e.Message
	}
	if e.ErrorCode != "" {
		return fmt.Sprintf("[%v] %s", e.ErrorCode, message)
	}
	return message
}
