// Code generated by Databricks SDK Generator. DO NOT EDIT.

package workspaces

import (
	"bytes"
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"net/url"
	"sync"

	"github.com/databricks/sdk-go/auth"
	"github.com/databricks/sdk-go/core/clientinfo"
	"github.com/databricks/sdk-go/options/call"
	"github.com/databricks/sdk-go/options/client"
	"github.com/databricks/sdk-go/options/internaloptions"
	"github.com/databricks/sdk-go/workspaces/internal"
)

type Client struct {
	internalClient

	// extensions is a per-client store for hand-written mixins to attach
	// lazily-built state. Keys should be unexported types private to the
	// mixin, following the context.Value convention, to avoid collisions.
	// The zero value is ready to use; it is safe for concurrent use.
	extensions sync.Map
}

type internalClient struct {
	httpClient  *http.Client
	credentials auth.Credentials
	logger      *slog.Logger
	userAgent   string
	host        string
	workspaceID string
	accountID   string
}

func NewClient(ctx context.Context, opts ...client.Option) (*Client, error) {
	cfg := internaloptions.ClientOptions{}
	for _, opt := range opts {
		if err := opt(&cfg); err != nil {
			return nil, err
		}
	}
	if err := cfg.Resolve(); err != nil {
		return nil, err
	}
	info, err := clientinfo.Default().With(
		internal.ModuleName, internal.Version,
		"auth", cfg.Credentials.Name(),
	)
	if err != nil {
		return nil, err
	}

	return &Client{
		internalClient: internalClient{
			httpClient:  cfg.HTTPClient,
			credentials: cfg.Credentials,
			logger:      cfg.Logger,
			userAgent:   info.String(),
			host:        cfg.Host,
			workspaceID: cfg.WorkspaceID,
			accountID:   cfg.AccountID,
		},
	}, nil
}

// Creates a new workspace using a credential configuration and a storage
// configuration, an optional network configuration (if using a customer-managed
// VPC), an optional managed services key configuration (if using
// customer-managed keys for managed services), and an optional storage key
// configuration (if using customer-managed keys for storage). The key
// configurations used for managed services and storage encryption can be the
// same or different.
//
// Important: This operation is asynchronous. A response with HTTP status code
// 200 means the request has been accepted and is in progress, but does not mean
// that the workspace deployed successfully and is running. The initial
// workspace status is typically PROVISIONING. Use the workspace ID
// (workspace_id) field in the response to identify the new workspace and make
// repeated GET requests with the workspace ID and check its status. The
// workspace becomes available when the status changes to RUNNING.
//
// You can share one customer-managed VPC with multiple workspaces in a single
// account. It is not required to create a new VPC for each workspace. However,
// you cannot reuse subnets or Security Groups between workspaces. If you plan
// to share one VPC with multiple workspaces, make sure you size your VPC and
// subnets accordingly. Because a Databricks Account API network configuration
// encapsulates this information, you cannot reuse a Databricks Account API
// network configuration across workspaces.
//
// For information about how to create a new workspace with this API including
// error handling, see [Create a new workspace using the Account API].
//
// Important: Customer-managed VPCs, PrivateLink, and customer-managed keys are
// supported on a limited set of deployment and subscription types. If you have
// questions about availability, contact your <Databricks> representative.
//
// This operation is available only if your account is on the E2 version of the
// platform or on a select custom plan that allows multiple workspaces per
// account.
//
// [Create a new workspace using the Account API]: http://docs.databricks.com/administration-guide/account-api/new-workspace.html
// Account-level method. Uses the Client's accountID, overridable per call via req.AccountId.
func (c *internalClient) CreateWorkspacePublic(ctx context.Context, req *CreateWorkspaceRequest, opts ...call.Option) (*Workspace, error) {
	body, err := json.Marshal(createWorkspaceRequestToWire(req))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	accountID := c.accountID
	if req.AccountId != nil && *req.AccountId != "" {
		accountID = *req.AccountId
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/accounts/")
	pb.singleSegment(accountID)
	pb.literal("/workspaces")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *Workspace

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp workspaceWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = workspaceFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Deletes a <Databricks> workspace, both specified by ID.
// Account-level method. Uses the Client's accountID, overridable per call via req.AccountId.
func (c *internalClient) DeleteWorkspacePublic(ctx context.Context, req *DeleteWorkspaceRequest, opts ...call.Option) (*Workspace, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	accountID := c.accountID
	if req.AccountId != nil && *req.AccountId != "" {
		accountID = *req.AccountId
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/accounts/")
	pb.singleSegment(accountID)
	pb.literal("/workspaces/")
	pb.singleSegment(*req.WorkspaceId)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *Workspace

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp workspaceWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = workspaceFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Gets information including status for a <Databricks> workspace, specified by
// ID. In the response, the `workspace_status` field indicates the current
// status. After initial workspace creation (which is asynchronous), make
// repeated `GET` requests with the workspace ID and check its status. The
// workspace becomes available when the status changes to `RUNNING`. For
// information about how to create a new workspace with this API **including
// error handling**, see [Create a new workspace using the Account API].
//
// [Create a new workspace using the Account API]: http://docs.databricks.com/administration-guide/account-api/new-workspace.html
// Account-level method. Uses the Client's accountID, overridable per call via req.AccountId.
func (c *internalClient) GetWorkspacePublic(ctx context.Context, req *GetWorkspaceRequest, opts ...call.Option) (*Workspace, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	accountID := c.accountID
	if req.AccountId != nil && *req.AccountId != "" {
		accountID = *req.AccountId
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/accounts/")
	pb.singleSegment(accountID)
	pb.literal("/workspaces/")
	pb.singleSegment(*req.WorkspaceId)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *Workspace

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp workspaceWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = workspaceFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Lists <Databricks> workspaces for an account.
// Account-level method. Uses the Client's accountID, overridable per call via req.AccountId.
func (c *internalClient) ListWorkspacesPublic(ctx context.Context, req *ListWorkspacesRequest, opts ...call.Option) (*ListWorkspacesResponse, error) {

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	accountID := c.accountID
	if req.AccountId != nil && *req.AccountId != "" {
		accountID = *req.AccountId
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/accounts/")
	pb.singleSegment(accountID)
	pb.literal("/workspaces")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListWorkspacesResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listWorkspacesResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = listWorkspacesResponseFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Updates a workspace.
// Account-level method. Uses the Client's accountID, overridable per call via req.AccountId.
func (c *internalClient) UpdateWorkspacePublic(ctx context.Context, req *UpdateWorkspaceRequest, opts ...call.Option) (*Workspace, error) {
	body, err := json.Marshal(workspaceToWire(req.CustomerFacingWorkspace))
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	if c.userAgent != "" {
		headers.Set("User-Agent", c.userAgent)
	}
	headers.Set("Content-Type", "application/json")

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	accountID := c.accountID
	pb := pathBuilder{}
	pb.literal("/api/2.0/accounts/")
	pb.singleSegment(accountID)
	pb.literal("/workspaces/")
	pb.singleSegment(*req.CustomerFacingWorkspace.WorkspaceId)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "update_mask", req.UpdateMask); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *Workspace

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PATCH",
			URL:         urlStr,
			Credentials: c.credentials,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp workspaceWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp = workspaceFromWire(&wireResp)
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}
