// Code generated by Databricks SDK Generator. DO NOT EDIT.

package modelserving

import (
	"io"
)

type Behavior string

const (
	Behavior_Unspecified Behavior = ""
	Behavior_None        Behavior = "NONE"
	Behavior_Block       Behavior = "BLOCK"
	Behavior_Mask        Behavior = "MASK"
)

type ServedModelDeploymentState string

const (
	ServedModelDeploymentState_Unspecified          ServedModelDeploymentState = ""
	ServedModelDeploymentState_DeploymentCreating   ServedModelDeploymentState = "DEPLOYMENT_CREATING"
	ServedModelDeploymentState_DeploymentRecovering ServedModelDeploymentState = "DEPLOYMENT_RECOVERING"
	ServedModelDeploymentState_DeploymentReady      ServedModelDeploymentState = "DEPLOYMENT_READY"
	ServedModelDeploymentState_DeploymentFailed     ServedModelDeploymentState = "DEPLOYMENT_FAILED"
	ServedModelDeploymentState_DeploymentAborted    ServedModelDeploymentState = "DEPLOYMENT_ABORTED"
	ServedModelDeploymentState_DeploymentStopped    ServedModelDeploymentState = "DEPLOYMENT_STOPPED"
)

type ServingEndpointDetailedPermissionLevel string

const (
	ServingEndpointDetailedPermissionLevel_Unspecified ServingEndpointDetailedPermissionLevel = ""
	ServingEndpointDetailedPermissionLevel_CanQuery    ServingEndpointDetailedPermissionLevel = "CAN_QUERY"
	ServingEndpointDetailedPermissionLevel_CanView     ServingEndpointDetailedPermissionLevel = "CAN_VIEW"
)

type ExternalFunctionRequest_HttpMethod string

const (
	ExternalFunctionRequest_HttpMethod_Unspecified ExternalFunctionRequest_HttpMethod = ""
	ExternalFunctionRequest_HttpMethod_Get         ExternalFunctionRequest_HttpMethod = "GET"
	ExternalFunctionRequest_HttpMethod_Post        ExternalFunctionRequest_HttpMethod = "POST"
	ExternalFunctionRequest_HttpMethod_Put         ExternalFunctionRequest_HttpMethod = "PUT"
	ExternalFunctionRequest_HttpMethod_Delete      ExternalFunctionRequest_HttpMethod = "DELETE"
	ExternalFunctionRequest_HttpMethod_Patch       ExternalFunctionRequest_HttpMethod = "PATCH"
)

type InferenceEndpointState_ConfigUpdateState string

const (
	InferenceEndpointState_ConfigUpdateState_Unspecified    InferenceEndpointState_ConfigUpdateState = ""
	InferenceEndpointState_ConfigUpdateState_NotUpdating    InferenceEndpointState_ConfigUpdateState = "NOT_UPDATING"
	InferenceEndpointState_ConfigUpdateState_InProgress     InferenceEndpointState_ConfigUpdateState = "IN_PROGRESS"
	InferenceEndpointState_ConfigUpdateState_UpdateFailed   InferenceEndpointState_ConfigUpdateState = "UPDATE_FAILED"
	InferenceEndpointState_ConfigUpdateState_UpdateCanceled InferenceEndpointState_ConfigUpdateState = "UPDATE_CANCELED"
)

type InferenceEndpointState_ReadyState string

const (
	InferenceEndpointState_ReadyState_Unspecified InferenceEndpointState_ReadyState = ""
	InferenceEndpointState_ReadyState_Ready       InferenceEndpointState_ReadyState = "READY"
	InferenceEndpointState_ReadyState_NotReady    InferenceEndpointState_ReadyState = "NOT_READY"
)

type Ai21LabsConfig struct {
	Ai21labsApiKey          *string
	Ai21labsApiKeyPlaintext *string
}

type AiGatewayConfig struct {
	UsageTrackingConfig  *UsageTrackingConfig
	InferenceTableConfig *InferenceTableConfig
	RateLimits           []AiGatewayRateLimit
	Guardrails           *AiGuardrails
	FallbackConfig       *FallbackConfig
}

type AiGatewayRateLimit struct {
	Calls         *int64
	Key           *string
	RenewalPeriod *string
	Principal     *string
	Tokens        *int64
}

type AiGuardrailParameters struct {
	Safety          *bool
	Pii             *PiiSettings
	ValidTopics     []string
	InvalidKeywords []string
}

type AiGuardrails struct {
	Input  *AiGuardrailParameters
	Output *AiGuardrailParameters
}

type AmazonBedrockConfig struct {
	AwsRegion                   *string
	AwsAccessKeyId              *string
	AwsSecretAccessKey          *string
	BedrockProvider             *string
	AwsAccessKeyIdPlaintext     *string
	AwsSecretAccessKeyPlaintext *string
	InstanceProfileArn          *string
}

type AnthropicConfig struct {
	AnthropicApiKey          *string
	AnthropicApiKeyPlaintext *string
}

type ApiKeyAuth struct {
	Key            *string
	Value          *string
	ValuePlaintext *string
}

// Deprecated: legacy inference table configuration. Please use AI Gateway
// inference tables instead. See
// https://docs.databricks.com/aws/en/ai-gateway/inference-tables..
type AutoCaptureConfig struct {
	CatalogName     *string
	SchemaName      *string
	TableNamePrefix *string
	State           *AutoCaptureState
	Enabled         *bool
}

type AutoCaptureState struct {
	PayloadTable *PayloadTable
}

type BearerTokenAuth struct {
	Token          *string
	TokenPlaintext *string
}

type CohereConfig struct {
	CohereApiKey          *string
	CohereApiKeyPlaintext *string
	CohereApiBase         *string
}

type CreateInferenceEndpointRequest struct {
	Name               *string
	Config             *EndpointCoreConfig
	Tags               []EndpointTag
	RouteOptimized     *bool
	RateLimits         []RateLimit
	AiGateway          *AiGatewayConfig
	BudgetPolicyId     *string
	EmailNotifications *EmailNotifications
	Description        *string
	TelemetryConfig    *TelemetryConfig
}

type CreatePtEndpointRequest struct {
	Name               *string
	Config             *PtEndpointCoreConfig
	Tags               []EndpointTag
	AiGateway          *AiGatewayConfig
	BudgetPolicyId     *string
	EmailNotifications *EmailNotifications
}

// Configs needed to create a custom provider model route..
type CustomProviderConfig struct {
	CustomProviderUrl *string
	BearerTokenAuth   *BearerTokenAuth
	ApiKeyAuth        *ApiKeyAuth
}

// Details necessary to query this object's API through the DataPlane APIs..
type DataPlaneInfo struct {
	EndpointUrl          *string
	AuthorizationDetails *string
}

type DatabricksModelServingConfig struct {
	DatabricksApiToken          *string
	DatabricksWorkspaceUrl      *string
	DatabricksApiTokenPlaintext *string
}

type DeleteInferenceEndpointRequest struct {
	Name *string
}

type DeleteInferenceEndpointResponse struct {
}

type EmailNotifications struct {
	OnUpdateSuccess []string
	OnUpdateFailure []string
}

type EndpointCoreConfig struct {
	ServedEntities    []ServedModel
	ServedModels      []ServedModel
	TrafficConfig     *TrafficConfig
	AutoCaptureConfig *AutoCaptureConfig
}

type EndpointCoreConfigOutput struct {
	ConfigVersion     *int64
	ServedEntities    []ServedModel
	ServedModels      []ServedModel
	TrafficConfig     *TrafficConfig
	AutoCaptureConfig *AutoCaptureConfig
}

type EndpointCoreConfigSummary struct {
	ServedEntities []ServedModelLite
	ServedModels   []ServedModelLite
}

type EndpointTag struct {
	Key   *string
	Value *string
}

// * Proto version of com.databricks.rpc.HttpOverRpcResponse.
//
// This message can be specially handled in UnaryRpcService with JettyRPC when
// the advanced feature CustomHandlingForHttpOverRpcProtoResponse is enabled -
// bypass the RPC serializer and populate HTTP status, response headers and
// response body from the proto message directly.
//
// Don't add/modify the fields before being aware of the implications..
type ExportMetricsResponse struct {
	Contents io.ReadCloser
}

// Simple Proto message for testing.
type ExternalFunctionRequest struct {
	ConnectionName *string
	Method         ExternalFunctionRequest_HttpMethod
	Path           *string
	Json           *string
	Headers        *string
	Params         *string
	SubDomain      *string
}

type ExternalFunctionResponse struct {
	Contents io.ReadCloser
}

type ExternalModel struct {
	Provider                     *string
	Name                         *string
	Task                         *string
	Ai21labsConfig               *Ai21LabsConfig
	AnthropicConfig              *AnthropicConfig
	AmazonBedrockConfig          *AmazonBedrockConfig
	CohereConfig                 *CohereConfig
	GoogleCloudVertexAiConfig    *GoogleCloudVertexAiConfig
	DatabricksModelServingConfig *DatabricksModelServingConfig
	OpenaiConfig                 *OpenAiConfig
	PalmConfig                   *PaLmConfig
	CustomProviderConfig         *CustomProviderConfig
}

type FallbackConfig struct {
	Enabled *bool
}

// All fields are not sensitive as they are hard-coded in the system and made
// available to customers..
type FoundationModel struct {
	Name        *string
	DisplayName *string
	Docs        *string
	Description *string
}

type GetExportEndpointMetricsRequest struct {
	Name *string
}

type GetInferenceEndpointRequest struct {
	Name *string
}

type GetInferenceEndpointSchemaRequest struct {
	Name *string
}

// The top level proto message that represents an OpenAPI 3.0 document..
type GetOpenApiResponse struct {
	Contents io.ReadCloser
}

type GetServedModelBuildLogsRequest struct {
	Name            *string
	ServedModelName *string
}

type GetServedModelBuildLogsResponse struct {
	Logs *string
}

type GetServedModelLogsRequest struct {
	Name            *string
	ServedModelName *string
}

type GetServedModelLogsResponse struct {
	Logs *string
}

type GoogleCloudVertexAiConfig struct {
	PrivateKey          *string
	ProjectId           *string
	Region              *string
	PrivateKeyPlaintext *string
}

type InferenceEndpoint struct {
	Name                 *string
	Creator              *string
	CreationTimestamp    *int64
	LastUpdatedTimestamp *int64
	State                *InferenceEndpointState
	Config               *EndpointCoreConfigSummary
	Tags                 []EndpointTag
	Id                   *string
	Task                 *string
	AiGateway            *AiGatewayConfig
	BudgetPolicyId       *string
	Description          *string
	UsagePolicyId        *string
	TelemetryConfig      *TelemetryConfig
}

type InferenceEndpointDetailed struct {
	Name                 *string
	Creator              *string
	CreationTimestamp    *int64
	LastUpdatedTimestamp *int64
	State                *InferenceEndpointState
	Config               *EndpointCoreConfigOutput
	PendingConfig        *PendingConfig
	Id                   *string
	PermissionLevel      ServingEndpointDetailedPermissionLevel
	Tags                 []EndpointTag
	Task                 *string
	RouteOptimized       *bool
	EndpointUrl          *string
	DataPlaneInfo        *ModelDataPlaneInfo
	AiGateway            *AiGatewayConfig
	BudgetPolicyId       *string
	EmailNotifications   *EmailNotifications
	Description          *string
	TelemetryConfig      *TelemetryConfig
}

type InferenceEndpointState struct {
	Ready        InferenceEndpointState_ReadyState
	ConfigUpdate InferenceEndpointState_ConfigUpdateState
}

type InferenceTableConfig struct {
	CatalogName     *string
	SchemaName      *string
	TableNamePrefix *string
	Enabled         *bool
}

type ListInferenceEndpointsRequest struct {
}

type ListInferenceEndpointsResponse struct {
	Endpoints []InferenceEndpoint
}

// A representation of all DataPlaneInfo for operations that can be done on a
// model through Data Plane APIs..
type ModelDataPlaneInfo struct {
	QueryInfo *DataPlaneInfo
}

// Configs needed to create an OpenAI model route..
type OpenAiConfig struct {
	OpenaiApiKey                        *string
	OpenaiApiType                       *string
	OpenaiApiBase                       *string
	OpenaiApiVersion                    *string
	OpenaiDeploymentName                *string
	OpenaiOrganization                  *string
	MicrosoftEntraTenantId              *string
	MicrosoftEntraClientId              *string
	MicrosoftEntraClientSecret          *string
	OpenaiApiKeyPlaintext               *string
	MicrosoftEntraClientSecretPlaintext *string
}

type PaLmConfig struct {
	PalmApiKey          *string
	PalmApiKeyPlaintext *string
}

type PatchInferenceEndpointTagsRequest struct {
	Name       *string
	AddTags    []EndpointTag
	DeleteTags []string
}

type PatchInferenceEndpointTagsResponse struct {
	Tags []EndpointTag
}

// Updates the telemetry configuration of a serving endpoint..
type PatchInferenceEndpointTelemetryConfigRequest struct {
	Name            *string
	TelemetryConfig *TelemetryConfig
}

type PayloadTable struct {
	Name          *string
	Status        *string
	StatusMessage *string
}

type PendingConfig struct {
	ServedEntities    []ServedModel
	ServedModels      []ServedModel
	TrafficConfig     *TrafficConfig
	ConfigVersion     *int
	StartTime         *int64
	AutoCaptureConfig *AutoCaptureConfig
}

type PiiSettings struct {
	Behavior Behavior
}

type PtEndpointCoreConfig struct {
	ServedEntities []PtServedModel
	TrafficConfig  *TrafficConfig
}

type PtServedModel struct {
	Name                  *string
	EntityName            *string
	EntityVersion         *string
	ProvisionedModelUnits *int64
	BurstScalingEnabled   *bool
}

type PutInferenceEndpointAiGatewayRequest struct {
	Name                 *string
	UsageTrackingConfig  *UsageTrackingConfig
	InferenceTableConfig *InferenceTableConfig
	RateLimits           []AiGatewayRateLimit
	Guardrails           *AiGuardrails
	FallbackConfig       *FallbackConfig
}

type PutInferenceEndpointAiGatewayResponse struct {
	UsageTrackingConfig  *UsageTrackingConfig
	InferenceTableConfig *InferenceTableConfig
	RateLimits           []AiGatewayRateLimit
	Guardrails           *AiGuardrails
	FallbackConfig       *FallbackConfig
}

type PutInferenceEndpointConfigRequest struct {
	Name              *string
	ServedEntities    []ServedModel
	ServedModels      []ServedModel
	TrafficConfig     *TrafficConfig
	AutoCaptureConfig *AutoCaptureConfig
}

type PutInferenceEndpointRateLimitsRequest struct {
	Name       *string
	RateLimits []RateLimit
}

type PutInferenceEndpointRateLimitsResponse struct {
	RateLimits []RateLimit
}

type PutPtEndpointConfigRequest struct {
	Name   *string
	Config *PtEndpointCoreConfig
}

type RateLimit struct {
	Calls         *int64
	Key           *string
	RenewalPeriod *string
}

type Route struct {
	ServedModelName   *string
	TrafficPercentage *int
	ServedEntityName  *string
}

type ServedModel struct {
	Name                      *string
	ExternalModel             *ExternalModel
	EntityName                *string
	EntityVersion             *string
	MinProvisionedThroughput  *int
	MaxProvisionedThroughput  *int
	MinProvisionedConcurrency *int
	MaxProvisionedConcurrency *int
	WorkloadSize              *string
	ProvisionedModelUnits     *int64
	BurstScalingEnabled       *bool
	ScaleToZeroEnabled        *bool
	ModelName                 *string
	ModelVersion              *string
	EnvironmentVars           map[string]string
	InstanceProfileArn        *string
	FoundationModel           *FoundationModel
	State                     *ServedModelState
	Creator                   *string
	CreationTimestamp         *int64
}

type ServedModelLite struct {
	Name            *string
	ModelName       *string
	EntityName      *string
	ModelVersion    *string
	EntityVersion   *string
	ExternalModel   *ExternalModel
	FoundationModel *FoundationModel
}

type ServedModelState struct {
	Deployment             ServedModelDeploymentState
	DeploymentStateMessage *string
}

type TelemetryConfig struct {
	TelemetryProfileId   *string
	TableNames           *UnityCatalogTableNames
	InferenceTableConfig *TelemetryInferenceTableConfig
}

// Inference table payload logging configuration.
type TelemetryInferenceTableConfig struct {
	SamplingFraction *float64
	Name             *string
}

type TrafficConfig struct {
	Routes []Route
}

type UnityCatalogTableNames struct {
	LogsTable        *string
	MetricsTable     *string
	TracesTable      *string
	AnnotationsTable *string
}

type UpdateInferenceEndpointNotificationsRequest struct {
	Name               *string
	EmailNotifications *EmailNotifications
}

type UpdateInferenceEndpointNotificationsResponse struct {
	Name               *string
	EmailNotifications *EmailNotifications
}

type UsageTrackingConfig struct {
	Enabled *bool
}
