// Code generated by Databricks SDK Generator. DO NOT EDIT.

package warehouses

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"log/slog"
	"net/http"
	"net/url"
	"sync"

	"github.com/databricks/sdk-go/auth"
	"github.com/databricks/sdk-go/core/clientinfo"
	"github.com/databricks/sdk-go/options/call"
	"github.com/databricks/sdk-go/options/client"
	"github.com/databricks/sdk-go/options/internaloptions"
	"github.com/databricks/sdk-go/options/lro"
	"github.com/databricks/sdk-go/warehouses/internal"
)

type Client struct {
	internalClient

	// extensions is a per-client store for hand-written mixins to attach
	// lazily-built state. Keys should be unexported types private to the
	// mixin, following the context.Value convention, to avoid collisions.
	// The zero value is ready to use; it is safe for concurrent use.
	extensions sync.Map
}

type internalClient struct {
	httpClient  *http.Client
	credentials auth.Credentials
	logger      *slog.Logger
	userAgent   func() (string, error)
	host        string
	workspaceID string
	accountID   string
}

func NewClient(ctx context.Context, opts ...client.Option) (*Client, error) {
	cfg := internaloptions.ClientOptions{}
	for _, opt := range opts {
		if err := opt(&cfg); err != nil {
			return nil, err
		}
	}
	if err := cfg.Resolve(); err != nil {
		return nil, err
	}
	userAgent := func() (string, error) {
		info, err := clientinfo.Default().With(
			internal.ModuleName, internal.Version,
			"auth", cfg.Credentials.Name(),
		)
		if err != nil {
			return "", err
		}
		return info.String(), nil
	}

	return &Client{
		internalClient: internalClient{
			httpClient:  cfg.HTTPClient,
			credentials: cfg.Credentials,
			logger:      cfg.Logger,
			userAgent:   userAgent,
			host:        cfg.Host,
			workspaceID: cfg.WorkspaceID,
			accountID:   cfg.AccountID,
		},
	}, nil
}

// Creates a new default warehouse override for a user. Users can create their
// own override. Admins can create overrides for any user.
func (c *internalClient) CreateDefaultWarehouseOverride(ctx context.Context, req *CreateDefaultWarehouseOverrideRequest, opts ...call.Option) (*DefaultWarehouseOverride, error) {
	wireReq, err := createDefaultWarehouseOverrideRequestToWire(req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq.DefaultWarehouseOverride)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/warehouses/v1/default-warehouse-overrides"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "default_warehouse_override_id", wireReq.DefaultWarehouseOverrideId); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DefaultWarehouseOverride

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp defaultWarehouseOverrideWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = defaultWarehouseOverrideFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Creates a new SQL warehouse.
func (c *internalClient) createWarehouseBase(ctx context.Context, req *CreateWarehouseRequest, opts ...call.Option) (*CreateWarehouseResponse, error) {
	wireReq, err := createWarehouseRequestToWire(req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/sql/warehouses"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *CreateWarehouseResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp createWarehouseResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = createWarehouseResponseFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Creates a new SQL warehouse.
func (c *internalClient) CreateWarehouse(ctx context.Context, req *CreateWarehouseRequest, opts ...call.Option) (*CreateWarehouseWaiter, error) {
	resp, err := c.createWarehouseBase(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if resp.Id == nil {
		return nil, fmt.Errorf("response field %q required for polling is missing", "Id")
	}
	return &CreateWarehouseWaiter{
		poll: c.GetWarehouse,
		id:   *resp.Id,
	}, nil
}

// CreateWarehouseWaiter tracks the state of the operation started by CreateWarehouse.
type CreateWarehouseWaiter struct {
	poll func(context.Context, *GetWarehouseRequest, ...call.Option) (*GetWarehouseResponse, error)
	id   string
}

// Done polls once and reports whether the operation has reached a terminal state.
func (w *CreateWarehouseWaiter) Done(ctx context.Context, opts ...call.Option) (bool, error) {
	pollResp, err := w.poll(ctx, &GetWarehouseRequest{
		Id: &w.id,
	}, opts...)
	if err != nil {
		return false, err
	}
	if pollResp == nil {
		return false, fmt.Errorf("response is missing")
	}
	status := pollResp.State
	if status == "" {
		return false, fmt.Errorf("response missing required status field")
	}
	switch status {
	case EndpointState_Running, EndpointState_Stopped, EndpointState_Deleted:
		return true, nil
	default:
		return false, nil
	}
}

// Wait polls until the operation reaches a terminal state.
func (w *CreateWarehouseWaiter) Wait(ctx context.Context, opts ...lro.Option) (*GetWarehouseResponse, error) {
	var result *GetWarehouseResponse
	poll := func(ctx context.Context) error {
		pollResp, err := w.poll(ctx, &GetWarehouseRequest{
			Id: &w.id,
		})
		if err != nil {
			return err
		}
		if pollResp == nil {
			return fmt.Errorf("response is missing")
		}
		status := pollResp.State
		if status == "" {
			return fmt.Errorf("response missing required status field")
		}
		switch status {
		case EndpointState_Running:
			result = pollResp
			return nil
		case EndpointState_Stopped, EndpointState_Deleted:
			message := "(no message)"
			if pollResp.Health != nil && pollResp.Health.Summary != nil {
				message = fmt.Sprintf("%v", *pollResp.Health.Summary)
			}
			return fmt.Errorf("terminal state %s: %s", status, message)
		default:
			return errOperationStillRunning
		}
	}
	if err := executeWait(ctx, poll, opts...); err != nil {
		return nil, err
	}
	return result, nil
}

// Deletes the default warehouse override for a user. Users can delete their own
// override. Admins can delete overrides for any user. After deletion, the
// workspace default warehouse will be used.
func (c *internalClient) DeleteDefaultWarehouseOverride(ctx context.Context, req *DeleteDefaultWarehouseOverrideRequest, opts ...call.Option) error {

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return err
	}
	pb := pathBuilder{}
	pb.literal("/api/warehouses/v1/")
	pb.singleSegment(*req.Name)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return err
	}
	return nil
}

// Deletes a SQL warehouse.
func (c *internalClient) DeleteWarehouse(ctx context.Context, req *DeleteWarehouseRequest, opts ...call.Option) (*DeleteWarehouseResponse, error) {

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/sql/warehouses/")
	pb.singleSegment(*req.Id)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DeleteWarehouseResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "DELETE",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &DeleteWarehouseResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Updates the configuration for a SQL warehouse.
func (c *internalClient) editWarehouseBase(ctx context.Context, req *EditWarehouseRequest, opts ...call.Option) (*EditWarehouseResponse, error) {
	wireReq, err := editWarehouseRequestToWire(req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/sql/warehouses/")
	pb.singleSegment(*req.Id)
	pb.literal("/edit")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *EditWarehouseResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &EditWarehouseResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Updates the configuration for a SQL warehouse.
func (c *internalClient) EditWarehouse(ctx context.Context, req *EditWarehouseRequest, opts ...call.Option) (*EditWarehouseWaiter, error) {
	if req.Id == nil {
		return nil, fmt.Errorf("request field %q required for polling is missing", "Id")
	}
	capturedId := *req.Id
	_, err := c.editWarehouseBase(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &EditWarehouseWaiter{
		poll: c.GetWarehouse,
		id:   capturedId,
	}, nil
}

// EditWarehouseWaiter tracks the state of the operation started by EditWarehouse.
type EditWarehouseWaiter struct {
	poll func(context.Context, *GetWarehouseRequest, ...call.Option) (*GetWarehouseResponse, error)
	id   string
}

// Done polls once and reports whether the operation has reached a terminal state.
func (w *EditWarehouseWaiter) Done(ctx context.Context, opts ...call.Option) (bool, error) {
	pollResp, err := w.poll(ctx, &GetWarehouseRequest{
		Id: &w.id,
	}, opts...)
	if err != nil {
		return false, err
	}
	if pollResp == nil {
		return false, fmt.Errorf("response is missing")
	}
	status := pollResp.State
	if status == "" {
		return false, fmt.Errorf("response missing required status field")
	}
	switch status {
	case EndpointState_Running, EndpointState_Stopped, EndpointState_Deleted:
		return true, nil
	default:
		return false, nil
	}
}

// Wait polls until the operation reaches a terminal state.
func (w *EditWarehouseWaiter) Wait(ctx context.Context, opts ...lro.Option) (*GetWarehouseResponse, error) {
	var result *GetWarehouseResponse
	poll := func(ctx context.Context) error {
		pollResp, err := w.poll(ctx, &GetWarehouseRequest{
			Id: &w.id,
		})
		if err != nil {
			return err
		}
		if pollResp == nil {
			return fmt.Errorf("response is missing")
		}
		status := pollResp.State
		if status == "" {
			return fmt.Errorf("response missing required status field")
		}
		switch status {
		case EndpointState_Running:
			result = pollResp
			return nil
		case EndpointState_Stopped, EndpointState_Deleted:
			message := "(no message)"
			if pollResp.Health != nil && pollResp.Health.Summary != nil {
				message = fmt.Sprintf("%v", *pollResp.Health.Summary)
			}
			return fmt.Errorf("terminal state %s: %s", status, message)
		default:
			return errOperationStillRunning
		}
	}
	if err := executeWait(ctx, poll, opts...); err != nil {
		return nil, err
	}
	return result, nil
}

// Returns the default warehouse override for a user. Users can fetch their own
// override. Admins can fetch overrides for any user. If no override exists, the
// UI will fallback to the workspace default warehouse.
func (c *internalClient) GetDefaultWarehouseOverride(ctx context.Context, req *GetDefaultWarehouseOverrideRequest, opts ...call.Option) (*DefaultWarehouseOverride, error) {

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/warehouses/v1/")
	pb.singleSegment(*req.Name)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DefaultWarehouseOverride

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp defaultWarehouseOverrideWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = defaultWarehouseOverrideFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Gets the information for a single SQL warehouse.
func (c *internalClient) GetWarehouse(ctx context.Context, req *GetWarehouseRequest, opts ...call.Option) (*GetWarehouseResponse, error) {

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/sql/warehouses/")
	pb.singleSegment(*req.Id)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *GetWarehouseResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp getWarehouseResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = getWarehouseResponseFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Gets the workspace level configuration that is shared by all SQL warehouses
// in a workspace.
func (c *internalClient) GetWorkspaceWarehouseConfig(ctx context.Context, req *GetWorkspaceWarehouseConfigRequest, opts ...call.Option) (*GetWorkspaceWarehouseConfigResponse, error) {

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/sql/config/warehouses"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *GetWorkspaceWarehouseConfigResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp getWorkspaceWarehouseConfigResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = getWorkspaceWarehouseConfigResponseFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Lists all default warehouse overrides in the workspace. Only workspace
// administrators can list all overrides.
func (c *internalClient) ListDefaultWarehouseOverrides(ctx context.Context, req *ListDefaultWarehouseOverridesRequest, opts ...call.Option) (*ListDefaultWarehouseOverridesResponse, error) {
	wireReq, err := listDefaultWarehouseOverridesRequestToWire(req)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/warehouses/v1/default-warehouse-overrides"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "page_size", wireReq.PageSize); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "page_token", wireReq.PageToken); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListDefaultWarehouseOverridesResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listDefaultWarehouseOverridesResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = listDefaultWarehouseOverridesResponseFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// ListDefaultWarehouseOverridesIter returns an iterator that iterates
// over the results of ListDefaultWarehouseOverrides.
//
// For example:
//
//	for item, err := range c.ListDefaultWarehouseOverridesIter(ctx, &ListDefaultWarehouseOverridesRequest{}) {
//	  if err != nil {
//	    return err
//	  }
//	  fmt.Println(item)
//	}
//
// Options opts are passed to each ListDefaultWarehouseOverrides call
// made by the iterator under the hood.
//
// Callers who need custom pagination logic should use
// ListDefaultWarehouseOverrides directly.
func (c *internalClient) ListDefaultWarehouseOverridesIter(ctx context.Context, req *ListDefaultWarehouseOverridesRequest, opts ...call.Option) iter.Seq2[*DefaultWarehouseOverride, error] {
	return func(yield func(*DefaultWarehouseOverride, error) bool) {
		// Copy the request so advancing the pagination field does not mutate the
		// caller's struct. Other reference-bearing fields are shared and must remain read-only.
		pageReq := ListDefaultWarehouseOverridesRequest{}
		if req != nil {
			pageReq = *req
		}
		for {
			resp, err := c.ListDefaultWarehouseOverrides(ctx, &pageReq, opts...)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range resp.DefaultWarehouseOverrides {
				if !yield(&resp.DefaultWarehouseOverrides[i], nil) {
					return
				}
			}
			if resp.NextPageToken == nil || *resp.NextPageToken == "" {
				return
			}
			pageReq.PageToken = resp.NextPageToken
		}
	}
}

// Lists all SQL warehouses that a user has access to.
func (c *internalClient) ListWarehouses(ctx context.Context, req *ListWarehousesRequest, opts ...call.Option) (*ListWarehousesResponse, error) {
	wireReq, err := listWarehousesRequestToWire(req)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/sql/warehouses"
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "run_as_user_id", wireReq.RunAsUserId); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "page_size", wireReq.PageSize); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "page_token", wireReq.PageToken); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *ListWarehousesResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "GET",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp listWarehousesResponseWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = listWarehousesResponseFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// ListWarehousesIter returns an iterator that iterates
// over the results of ListWarehouses.
//
// For example:
//
//	for item, err := range c.ListWarehousesIter(ctx, &ListWarehousesRequest{}) {
//	  if err != nil {
//	    return err
//	  }
//	  fmt.Println(item)
//	}
//
// Options opts are passed to each ListWarehouses call
// made by the iterator under the hood.
//
// Callers who need custom pagination logic should use
// ListWarehouses directly.
func (c *internalClient) ListWarehousesIter(ctx context.Context, req *ListWarehousesRequest, opts ...call.Option) iter.Seq2[*EndpointInfo, error] {
	return func(yield func(*EndpointInfo, error) bool) {
		// Copy the request so advancing the pagination field does not mutate the
		// caller's struct. Other reference-bearing fields are shared and must remain read-only.
		pageReq := ListWarehousesRequest{}
		if req != nil {
			pageReq = *req
		}
		for {
			resp, err := c.ListWarehouses(ctx, &pageReq, opts...)
			if err != nil {
				yield(nil, err)
				return
			}
			for i := range resp.Warehouses {
				if !yield(&resp.Warehouses[i], nil) {
					return
				}
			}
			if resp.NextPageToken == nil || *resp.NextPageToken == "" {
				return
			}
			pageReq.PageToken = resp.NextPageToken
		}
	}
}

// Sets the workspace level configuration that is shared by all SQL warehouses
// in a workspace.
func (c *internalClient) SetWorkspaceWarehouseConfig(ctx context.Context, req *SetWorkspaceWarehouseConfigRequest, opts ...call.Option) (*SetWorkspaceWarehouseConfigResponse, error) {
	wireReq, err := setWorkspaceWarehouseConfigRequestToWire(req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	baseURL.Path = "/api/2.0/sql/config/warehouses"
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *SetWorkspaceWarehouseConfigResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PUT",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &SetWorkspaceWarehouseConfigResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Starts a SQL warehouse.
func (c *internalClient) startWarehouseBase(ctx context.Context, req *StartRequest, opts ...call.Option) (*StartResponse, error) {
	wireReq, err := startRequestToWire(req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/sql/warehouses/")
	pb.singleSegment(*req.Id)
	pb.literal("/start")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *StartResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &StartResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Starts a SQL warehouse.
func (c *internalClient) StartWarehouse(ctx context.Context, req *StartRequest, opts ...call.Option) (*StartWarehouseWaiter, error) {
	if req.Id == nil {
		return nil, fmt.Errorf("request field %q required for polling is missing", "Id")
	}
	capturedId := *req.Id
	_, err := c.startWarehouseBase(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &StartWarehouseWaiter{
		poll: c.GetWarehouse,
		id:   capturedId,
	}, nil
}

// StartWarehouseWaiter tracks the state of the operation started by StartWarehouse.
type StartWarehouseWaiter struct {
	poll func(context.Context, *GetWarehouseRequest, ...call.Option) (*GetWarehouseResponse, error)
	id   string
}

// Done polls once and reports whether the operation has reached a terminal state.
func (w *StartWarehouseWaiter) Done(ctx context.Context, opts ...call.Option) (bool, error) {
	pollResp, err := w.poll(ctx, &GetWarehouseRequest{
		Id: &w.id,
	}, opts...)
	if err != nil {
		return false, err
	}
	if pollResp == nil {
		return false, fmt.Errorf("response is missing")
	}
	status := pollResp.State
	if status == "" {
		return false, fmt.Errorf("response missing required status field")
	}
	switch status {
	case EndpointState_Running, EndpointState_Stopped, EndpointState_Deleted:
		return true, nil
	default:
		return false, nil
	}
}

// Wait polls until the operation reaches a terminal state.
func (w *StartWarehouseWaiter) Wait(ctx context.Context, opts ...lro.Option) (*GetWarehouseResponse, error) {
	var result *GetWarehouseResponse
	poll := func(ctx context.Context) error {
		pollResp, err := w.poll(ctx, &GetWarehouseRequest{
			Id: &w.id,
		})
		if err != nil {
			return err
		}
		if pollResp == nil {
			return fmt.Errorf("response is missing")
		}
		status := pollResp.State
		if status == "" {
			return fmt.Errorf("response missing required status field")
		}
		switch status {
		case EndpointState_Running:
			result = pollResp
			return nil
		case EndpointState_Stopped, EndpointState_Deleted:
			message := "(no message)"
			if pollResp.Health != nil && pollResp.Health.Summary != nil {
				message = fmt.Sprintf("%v", *pollResp.Health.Summary)
			}
			return fmt.Errorf("terminal state %s: %s", status, message)
		default:
			return errOperationStillRunning
		}
	}
	if err := executeWait(ctx, poll, opts...); err != nil {
		return nil, err
	}
	return result, nil
}

// Stops a SQL warehouse.
func (c *internalClient) stopWarehouseBase(ctx context.Context, req *StopRequest, opts ...call.Option) (*StopResponse, error) {
	wireReq, err := stopRequestToWire(req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/2.0/sql/warehouses/")
	pb.singleSegment(*req.Id)
	pb.literal("/stop")
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *StopResponse

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "POST",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		_ = respBody
		resp = &StopResponse{}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}

// Stops a SQL warehouse.
func (c *internalClient) StopWarehouse(ctx context.Context, req *StopRequest, opts ...call.Option) (*StopWarehouseWaiter, error) {
	if req.Id == nil {
		return nil, fmt.Errorf("request field %q required for polling is missing", "Id")
	}
	capturedId := *req.Id
	_, err := c.stopWarehouseBase(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &StopWarehouseWaiter{
		poll: c.GetWarehouse,
		id:   capturedId,
	}, nil
}

// StopWarehouseWaiter tracks the state of the operation started by StopWarehouse.
type StopWarehouseWaiter struct {
	poll func(context.Context, *GetWarehouseRequest, ...call.Option) (*GetWarehouseResponse, error)
	id   string
}

// Done polls once and reports whether the operation has reached a terminal state.
func (w *StopWarehouseWaiter) Done(ctx context.Context, opts ...call.Option) (bool, error) {
	pollResp, err := w.poll(ctx, &GetWarehouseRequest{
		Id: &w.id,
	}, opts...)
	if err != nil {
		return false, err
	}
	if pollResp == nil {
		return false, fmt.Errorf("response is missing")
	}
	status := pollResp.State
	if status == "" {
		return false, fmt.Errorf("response missing required status field")
	}
	switch status {
	case EndpointState_Stopped:
		return true, nil
	default:
		return false, nil
	}
}

// Wait polls until the operation reaches a terminal state.
func (w *StopWarehouseWaiter) Wait(ctx context.Context, opts ...lro.Option) (*GetWarehouseResponse, error) {
	var result *GetWarehouseResponse
	poll := func(ctx context.Context) error {
		pollResp, err := w.poll(ctx, &GetWarehouseRequest{
			Id: &w.id,
		})
		if err != nil {
			return err
		}
		if pollResp == nil {
			return fmt.Errorf("response is missing")
		}
		status := pollResp.State
		if status == "" {
			return fmt.Errorf("response missing required status field")
		}
		switch status {
		case EndpointState_Stopped:
			result = pollResp
			return nil
		default:
			return errOperationStillRunning
		}
	}
	if err := executeWait(ctx, poll, opts...); err != nil {
		return nil, err
	}
	return result, nil
}

// Updates an existing default warehouse override for a user. Users can update
// their own override. Admins can update overrides for any user.
func (c *internalClient) UpdateDefaultWarehouseOverride(ctx context.Context, req *UpdateDefaultWarehouseOverrideRequest, opts ...call.Option) (*DefaultWarehouseOverride, error) {
	wireReq, err := updateDefaultWarehouseOverrideRequestToWire(req)
	if err != nil {
		return nil, err
	}
	body, err := json.Marshal(wireReq.DefaultWarehouseOverride)
	if err != nil {
		return nil, err
	}

	headers := http.Header{}
	headers.Set("Content-Type", "application/json")
	if c.workspaceID != "" {
		headers.Set("X-Databricks-Workspace-Id", c.workspaceID)
	}

	baseURL, err := url.Parse(c.host)
	if err != nil {
		return nil, err
	}
	pb := pathBuilder{}
	pb.literal("/api/warehouses/v1/")
	pb.singleSegment(*req.DefaultWarehouseOverride.Name)
	baseURL.Path, baseURL.RawPath = pb.build()
	queryParams := url.Values{}
	if err := addQueryValue(queryParams, "update_mask", wireReq.UpdateMask); err != nil {
		return nil, err
	}
	if err := addQueryValue(queryParams, "allow_missing", wireReq.AllowMissing); err != nil {
		return nil, err
	}
	baseURL.RawQuery = queryParams.Encode()
	urlStr := baseURL.String()

	var resp *DefaultWarehouseOverride

	call := func(ctx context.Context) error {
		httpReq, err := newHTTPRequest(ctx, httpRequestOptions{
			Method:      "PATCH",
			URL:         urlStr,
			Credentials: c.credentials,
			UserAgent:   c.userAgent,
			Headers:     headers,
			Body:        bytes.NewBuffer(body),
		})
		if err != nil {
			return err
		}

		respBody, _, err := executeHTTPCall(httpCallOptions{
			req:    httpReq,
			client: c.httpClient,
			logger: c.logger,
		})
		if err != nil {
			return err
		}
		var wireResp defaultWarehouseOverrideWire
		if err := json.Unmarshal(respBody, &wireResp); err != nil {
			return err
		}
		resp, err = defaultWarehouseOverrideFromWire(&wireResp)
		if err != nil {
			return err
		}
		return nil
	}

	if err := executeCall(ctx, call, opts); err != nil {
		return nil, err
	}
	return resp, nil
}
