// Code generated by Databricks SDK Generator. DO NOT EDIT.

package credentials

type accountsCreateStorageCredentialRequestWire struct {
	AccountId      *string                              `json:"account_id,omitempty"`
	MetastoreId    *string                              `json:"metastore_id,omitempty"`
	CredentialInfo *createAccountsStorageCredentialWire `json:"credential_info,omitempty"`
	SkipValidation *bool                                `json:"skip_validation,omitempty"`
}

func accountsCreateStorageCredentialRequestToWire(v *AccountsCreateStorageCredentialRequest) *accountsCreateStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &accountsCreateStorageCredentialRequestWire{
		AccountId:      v.AccountId,
		MetastoreId:    v.MetastoreId,
		CredentialInfo: createAccountsStorageCredentialToWire(v.CredentialInfo),
		SkipValidation: v.SkipValidation,
	}
}

func accountsCreateStorageCredentialRequestFromWire(w *accountsCreateStorageCredentialRequestWire) *AccountsCreateStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &AccountsCreateStorageCredentialRequest{
		AccountId:      w.AccountId,
		MetastoreId:    w.MetastoreId,
		CredentialInfo: createAccountsStorageCredentialFromWire(w.CredentialInfo),
		SkipValidation: w.SkipValidation,
	}
}

type accountsCreateStorageCredentialResponseWire struct {
	CredentialInfo *storageCredentialInfoWire `json:"credential_info,omitempty"`
}

func accountsCreateStorageCredentialResponseToWire(v *AccountsCreateStorageCredentialResponse) *accountsCreateStorageCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &accountsCreateStorageCredentialResponseWire{
		CredentialInfo: storageCredentialInfoToWire(v.CredentialInfo),
	}
}

func accountsCreateStorageCredentialResponseFromWire(w *accountsCreateStorageCredentialResponseWire) *AccountsCreateStorageCredentialResponse {
	if w == nil {
		return nil
	}
	return &AccountsCreateStorageCredentialResponse{
		CredentialInfo: storageCredentialInfoFromWire(w.CredentialInfo),
	}
}

type accountsDeleteStorageCredentialRequestWire struct {
	AccountId   *string `json:"account_id,omitempty"`
	MetastoreId *string `json:"metastore_id,omitempty"`
	NameArg     *string `json:"name_arg,omitempty"`
	Force       *bool   `json:"force,omitempty"`
}

func accountsDeleteStorageCredentialRequestToWire(v *AccountsDeleteStorageCredentialRequest) *accountsDeleteStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &accountsDeleteStorageCredentialRequestWire{
		AccountId:   v.AccountId,
		MetastoreId: v.MetastoreId,
		NameArg:     v.NameArg,
		Force:       v.Force,
	}
}

func accountsDeleteStorageCredentialRequestFromWire(w *accountsDeleteStorageCredentialRequestWire) *AccountsDeleteStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &AccountsDeleteStorageCredentialRequest{
		AccountId:   w.AccountId,
		MetastoreId: w.MetastoreId,
		NameArg:     w.NameArg,
		Force:       w.Force,
	}
}

type accountsDeleteStorageCredentialResponseWire struct {
}

func accountsDeleteStorageCredentialResponseToWire(v *AccountsDeleteStorageCredentialResponse) *accountsDeleteStorageCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &accountsDeleteStorageCredentialResponseWire{}
}

func accountsDeleteStorageCredentialResponseFromWire(w *accountsDeleteStorageCredentialResponseWire) *AccountsDeleteStorageCredentialResponse {
	if w == nil {
		return nil
	}
	return &AccountsDeleteStorageCredentialResponse{}
}

type accountsGetStorageCredentialRequestWire struct {
	AccountId   *string `json:"account_id,omitempty"`
	MetastoreId *string `json:"metastore_id,omitempty"`
	NameArg     *string `json:"name_arg,omitempty"`
}

func accountsGetStorageCredentialRequestToWire(v *AccountsGetStorageCredentialRequest) *accountsGetStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &accountsGetStorageCredentialRequestWire{
		AccountId:   v.AccountId,
		MetastoreId: v.MetastoreId,
		NameArg:     v.NameArg,
	}
}

func accountsGetStorageCredentialRequestFromWire(w *accountsGetStorageCredentialRequestWire) *AccountsGetStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &AccountsGetStorageCredentialRequest{
		AccountId:   w.AccountId,
		MetastoreId: w.MetastoreId,
		NameArg:     w.NameArg,
	}
}

type accountsGetStorageCredentialResponseWire struct {
	CredentialInfo *storageCredentialInfoWire `json:"credential_info,omitempty"`
}

func accountsGetStorageCredentialResponseToWire(v *AccountsGetStorageCredentialResponse) *accountsGetStorageCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &accountsGetStorageCredentialResponseWire{
		CredentialInfo: storageCredentialInfoToWire(v.CredentialInfo),
	}
}

func accountsGetStorageCredentialResponseFromWire(w *accountsGetStorageCredentialResponseWire) *AccountsGetStorageCredentialResponse {
	if w == nil {
		return nil
	}
	return &AccountsGetStorageCredentialResponse{
		CredentialInfo: storageCredentialInfoFromWire(w.CredentialInfo),
	}
}

type accountsListStorageCredentialsRequestWire struct {
	AccountId   *string `json:"account_id,omitempty"`
	MetastoreId *string `json:"metastore_id,omitempty"`
}

func accountsListStorageCredentialsRequestToWire(v *AccountsListStorageCredentialsRequest) *accountsListStorageCredentialsRequestWire {
	if v == nil {
		return nil
	}
	return &accountsListStorageCredentialsRequestWire{
		AccountId:   v.AccountId,
		MetastoreId: v.MetastoreId,
	}
}

func accountsListStorageCredentialsRequestFromWire(w *accountsListStorageCredentialsRequestWire) *AccountsListStorageCredentialsRequest {
	if w == nil {
		return nil
	}
	return &AccountsListStorageCredentialsRequest{
		AccountId:   w.AccountId,
		MetastoreId: w.MetastoreId,
	}
}

type accountsListStorageCredentialsResponseWire struct {
	StorageCredentials []storageCredentialInfoWire `json:"storage_credentials,omitempty"`
}

func accountsListStorageCredentialsResponseToWire(v *AccountsListStorageCredentialsResponse) *accountsListStorageCredentialsResponseWire {
	if v == nil {
		return nil
	}
	return &accountsListStorageCredentialsResponseWire{
		StorageCredentials: convertSlice(v.StorageCredentials, storageCredentialInfoToWire),
	}
}

func accountsListStorageCredentialsResponseFromWire(w *accountsListStorageCredentialsResponseWire) *AccountsListStorageCredentialsResponse {
	if w == nil {
		return nil
	}
	return &AccountsListStorageCredentialsResponse{
		StorageCredentials: convertSlice(w.StorageCredentials, storageCredentialInfoFromWire),
	}
}

type accountsUpdateStorageCredentialRequestWire struct {
	AccountId      *string                              `json:"account_id,omitempty"`
	MetastoreId    *string                              `json:"metastore_id,omitempty"`
	NameArg        *string                              `json:"name_arg,omitempty"`
	CredentialInfo *updateAccountsStorageCredentialWire `json:"credential_info,omitempty"`
	SkipValidation *bool                                `json:"skip_validation,omitempty"`
}

func accountsUpdateStorageCredentialRequestToWire(v *AccountsUpdateStorageCredentialRequest) *accountsUpdateStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &accountsUpdateStorageCredentialRequestWire{
		AccountId:      v.AccountId,
		MetastoreId:    v.MetastoreId,
		NameArg:        v.NameArg,
		CredentialInfo: updateAccountsStorageCredentialToWire(v.CredentialInfo),
		SkipValidation: v.SkipValidation,
	}
}

func accountsUpdateStorageCredentialRequestFromWire(w *accountsUpdateStorageCredentialRequestWire) *AccountsUpdateStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &AccountsUpdateStorageCredentialRequest{
		AccountId:      w.AccountId,
		MetastoreId:    w.MetastoreId,
		NameArg:        w.NameArg,
		CredentialInfo: updateAccountsStorageCredentialFromWire(w.CredentialInfo),
		SkipValidation: w.SkipValidation,
	}
}

type accountsUpdateStorageCredentialResponseWire struct {
	CredentialInfo *storageCredentialInfoWire `json:"credential_info,omitempty"`
}

func accountsUpdateStorageCredentialResponseToWire(v *AccountsUpdateStorageCredentialResponse) *accountsUpdateStorageCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &accountsUpdateStorageCredentialResponseWire{
		CredentialInfo: storageCredentialInfoToWire(v.CredentialInfo),
	}
}

func accountsUpdateStorageCredentialResponseFromWire(w *accountsUpdateStorageCredentialResponseWire) *AccountsUpdateStorageCredentialResponse {
	if w == nil {
		return nil
	}
	return &AccountsUpdateStorageCredentialResponse{
		CredentialInfo: storageCredentialInfoFromWire(w.CredentialInfo),
	}
}

type awsCredentialsWire struct {
	StsRole *awsCredentials_StsRoleWire `json:"sts_role,omitempty"`
}

func awsCredentialsToWire(v *AwsCredentials) *awsCredentialsWire {
	if v == nil {
		return nil
	}
	return &awsCredentialsWire{
		StsRole: awsCredentials_StsRoleToWire(v.StsRole),
	}
}

func awsCredentialsFromWire(w *awsCredentialsWire) *AwsCredentials {
	if w == nil {
		return nil
	}
	return &AwsCredentials{
		StsRole: awsCredentials_StsRoleFromWire(w.StsRole),
	}
}

type awsCredentials_StsRoleWire struct {
	RoleArn *string `json:"role_arn,omitempty"`
}

func awsCredentials_StsRoleToWire(v *AwsCredentials_StsRole) *awsCredentials_StsRoleWire {
	if v == nil {
		return nil
	}
	return &awsCredentials_StsRoleWire{
		RoleArn: v.RoleArn,
	}
}

func awsCredentials_StsRoleFromWire(w *awsCredentials_StsRoleWire) *AwsCredentials_StsRole {
	if w == nil {
		return nil
	}
	return &AwsCredentials_StsRole{
		RoleArn: w.RoleArn,
	}
}

type awsIamRoleWire struct {
	RoleArn            *string `json:"role_arn,omitempty"`
	UnityCatalogIamArn *string `json:"unity_catalog_iam_arn,omitempty"`
	ExternalId         *string `json:"external_id,omitempty"`
}

func awsIamRoleToWire(v *AwsIamRole) *awsIamRoleWire {
	if v == nil {
		return nil
	}
	return &awsIamRoleWire{
		RoleArn:            v.RoleArn,
		UnityCatalogIamArn: v.UnityCatalogIamArn,
		ExternalId:         v.ExternalId,
	}
}

func awsIamRoleFromWire(w *awsIamRoleWire) *AwsIamRole {
	if w == nil {
		return nil
	}
	return &AwsIamRole{
		RoleArn:            w.RoleArn,
		UnityCatalogIamArn: w.UnityCatalogIamArn,
		ExternalId:         w.ExternalId,
	}
}

type azureActiveDirectoryTokenWire struct {
	AadToken *string `json:"aad_token,omitempty"`
}

func azureActiveDirectoryTokenToWire(v *AzureActiveDirectoryToken) *azureActiveDirectoryTokenWire {
	if v == nil {
		return nil
	}
	return &azureActiveDirectoryTokenWire{
		AadToken: v.AadToken,
	}
}

func azureActiveDirectoryTokenFromWire(w *azureActiveDirectoryTokenWire) *AzureActiveDirectoryToken {
	if w == nil {
		return nil
	}
	return &AzureActiveDirectoryToken{
		AadToken: w.AadToken,
	}
}

type azureManagedIdentityWire struct {
	AccessConnectorId *string `json:"access_connector_id,omitempty"`
	ManagedIdentityId *string `json:"managed_identity_id,omitempty"`
	CredentialId      *string `json:"credential_id,omitempty"`
}

func azureManagedIdentityToWire(v *AzureManagedIdentity) *azureManagedIdentityWire {
	if v == nil {
		return nil
	}
	return &azureManagedIdentityWire{
		AccessConnectorId: v.AccessConnectorId,
		ManagedIdentityId: v.ManagedIdentityId,
		CredentialId:      v.CredentialId,
	}
}

func azureManagedIdentityFromWire(w *azureManagedIdentityWire) *AzureManagedIdentity {
	if w == nil {
		return nil
	}
	return &AzureManagedIdentity{
		AccessConnectorId: w.AccessConnectorId,
		ManagedIdentityId: w.ManagedIdentityId,
		CredentialId:      w.CredentialId,
	}
}

type azureServicePrincipalWire struct {
	DirectoryId   *string `json:"directory_id,omitempty"`
	ApplicationId *string `json:"application_id,omitempty"`
	ClientSecret  *string `json:"client_secret,omitempty"`
}

func azureServicePrincipalToWire(v *AzureServicePrincipal) *azureServicePrincipalWire {
	if v == nil {
		return nil
	}
	return &azureServicePrincipalWire{
		DirectoryId:   v.DirectoryId,
		ApplicationId: v.ApplicationId,
		ClientSecret:  v.ClientSecret,
	}
}

func azureServicePrincipalFromWire(w *azureServicePrincipalWire) *AzureServicePrincipal {
	if w == nil {
		return nil
	}
	return &AzureServicePrincipal{
		DirectoryId:   w.DirectoryId,
		ApplicationId: w.ApplicationId,
		ClientSecret:  w.ClientSecret,
	}
}

type azureUserDelegationSasWire struct {
	SasToken *string `json:"sas_token,omitempty"`
}

func azureUserDelegationSasToWire(v *AzureUserDelegationSas) *azureUserDelegationSasWire {
	if v == nil {
		return nil
	}
	return &azureUserDelegationSasWire{
		SasToken: v.SasToken,
	}
}

func azureUserDelegationSasFromWire(w *azureUserDelegationSasWire) *AzureUserDelegationSas {
	if w == nil {
		return nil
	}
	return &AzureUserDelegationSas{
		SasToken: w.SasToken,
	}
}

type cloudflareApiTokenWire struct {
	AccessKeyId     *string `json:"access_key_id,omitempty"`
	SecretAccessKey *string `json:"secret_access_key,omitempty"`
	AccountId       *string `json:"account_id,omitempty"`
}

func cloudflareApiTokenToWire(v *CloudflareApiToken) *cloudflareApiTokenWire {
	if v == nil {
		return nil
	}
	return &cloudflareApiTokenWire{
		AccessKeyId:     v.AccessKeyId,
		SecretAccessKey: v.SecretAccessKey,
		AccountId:       v.AccountId,
	}
}

func cloudflareApiTokenFromWire(w *cloudflareApiTokenWire) *CloudflareApiToken {
	if w == nil {
		return nil
	}
	return &CloudflareApiToken{
		AccessKeyId:     w.AccessKeyId,
		SecretAccessKey: w.SecretAccessKey,
		AccountId:       w.AccountId,
	}
}

type createAccountsStorageCredentialWire struct {
	Name                        *string                          `json:"name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	GcpServiceAccountKey        *gcpServiceAccountKeyWire        `json:"gcp_service_account_key,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	Comment                     *string                          `json:"comment,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
	Owner                       *string                          `json:"owner,omitempty"`
	Id                          *string                          `json:"id,omitempty"`
	MetastoreId                 *string                          `json:"metastore_id,omitempty"`
	CreatedAt                   *int64                           `json:"created_at,omitempty"`
	CreatedBy                   *string                          `json:"created_by,omitempty"`
	UpdatedAt                   *int64                           `json:"updated_at,omitempty"`
	UpdatedBy                   *string                          `json:"updated_by,omitempty"`
	UsedForManagedStorage       *bool                            `json:"used_for_managed_storage,omitempty"`
	FullName                    *string                          `json:"full_name,omitempty"`
	IsolationMode               IsolationMode                    `json:"isolation_mode,omitempty"`
}

func createAccountsStorageCredentialToWire(v *CreateAccountsStorageCredential) *createAccountsStorageCredentialWire {
	if v == nil {
		return nil
	}
	return &createAccountsStorageCredentialWire{
		Name:                        v.Name,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyToWire(v.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		Comment:                     v.Comment,
		ReadOnly:                    v.ReadOnly,
		Owner:                       v.Owner,
		Id:                          v.Id,
		MetastoreId:                 v.MetastoreId,
		CreatedAt:                   v.CreatedAt,
		CreatedBy:                   v.CreatedBy,
		UpdatedAt:                   v.UpdatedAt,
		UpdatedBy:                   v.UpdatedBy,
		UsedForManagedStorage:       v.UsedForManagedStorage,
		FullName:                    v.FullName,
		IsolationMode:               v.IsolationMode,
	}
}

func createAccountsStorageCredentialFromWire(w *createAccountsStorageCredentialWire) *CreateAccountsStorageCredential {
	if w == nil {
		return nil
	}
	return &CreateAccountsStorageCredential{
		Name:                        w.Name,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyFromWire(w.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		Comment:                     w.Comment,
		ReadOnly:                    w.ReadOnly,
		Owner:                       w.Owner,
		Id:                          w.Id,
		MetastoreId:                 w.MetastoreId,
		CreatedAt:                   w.CreatedAt,
		CreatedBy:                   w.CreatedBy,
		UpdatedAt:                   w.UpdatedAt,
		UpdatedBy:                   w.UpdatedBy,
		UsedForManagedStorage:       w.UsedForManagedStorage,
		FullName:                    w.FullName,
		IsolationMode:               w.IsolationMode,
	}
}

type createCredentialAwsCredentialsWire struct {
	StsRole *awsCredentials_StsRoleWire `json:"sts_role,omitempty"`
}

func createCredentialAwsCredentialsToWire(v *CreateCredentialAwsCredentials) *createCredentialAwsCredentialsWire {
	if v == nil {
		return nil
	}
	return &createCredentialAwsCredentialsWire{
		StsRole: awsCredentials_StsRoleToWire(v.StsRole),
	}
}

func createCredentialAwsCredentialsFromWire(w *createCredentialAwsCredentialsWire) *CreateCredentialAwsCredentials {
	if w == nil {
		return nil
	}
	return &CreateCredentialAwsCredentials{
		StsRole: awsCredentials_StsRoleFromWire(w.StsRole),
	}
}

type createCredentialRequestWire struct {
	SkipValidation              *bool                            `json:"skip_validation,omitempty"`
	Name                        *string                          `json:"name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	GcpServiceAccountKey        *gcpServiceAccountKeyWire        `json:"gcp_service_account_key,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	Comment                     *string                          `json:"comment,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
	Owner                       *string                          `json:"owner,omitempty"`
	Id                          *string                          `json:"id,omitempty"`
	MetastoreId                 *string                          `json:"metastore_id,omitempty"`
	CreatedAt                   *int64                           `json:"created_at,omitempty"`
	CreatedBy                   *string                          `json:"created_by,omitempty"`
	UpdatedAt                   *int64                           `json:"updated_at,omitempty"`
	UpdatedBy                   *string                          `json:"updated_by,omitempty"`
	UsedForManagedStorage       *bool                            `json:"used_for_managed_storage,omitempty"`
	FullName                    *string                          `json:"full_name,omitempty"`
	IsolationMode               IsolationMode                    `json:"isolation_mode,omitempty"`
}

func createCredentialRequestToWire(v *CreateCredentialRequest) *createCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &createCredentialRequestWire{
		SkipValidation:              v.SkipValidation,
		Name:                        v.Name,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyToWire(v.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		Comment:                     v.Comment,
		ReadOnly:                    v.ReadOnly,
		Owner:                       v.Owner,
		Id:                          v.Id,
		MetastoreId:                 v.MetastoreId,
		CreatedAt:                   v.CreatedAt,
		CreatedBy:                   v.CreatedBy,
		UpdatedAt:                   v.UpdatedAt,
		UpdatedBy:                   v.UpdatedBy,
		UsedForManagedStorage:       v.UsedForManagedStorage,
		FullName:                    v.FullName,
		IsolationMode:               v.IsolationMode,
	}
}

func createCredentialRequestFromWire(w *createCredentialRequestWire) *CreateCredentialRequest {
	if w == nil {
		return nil
	}
	return &CreateCredentialRequest{
		SkipValidation:              w.SkipValidation,
		Name:                        w.Name,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyFromWire(w.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		Comment:                     w.Comment,
		ReadOnly:                    w.ReadOnly,
		Owner:                       w.Owner,
		Id:                          w.Id,
		MetastoreId:                 w.MetastoreId,
		CreatedAt:                   w.CreatedAt,
		CreatedBy:                   w.CreatedBy,
		UpdatedAt:                   w.UpdatedAt,
		UpdatedBy:                   w.UpdatedBy,
		UsedForManagedStorage:       w.UsedForManagedStorage,
		FullName:                    w.FullName,
		IsolationMode:               w.IsolationMode,
	}
}

type createCredentialsRequestWire struct {
	AccountId       *string                             `json:"account_id,omitempty"`
	CredentialsName *string                             `json:"credentials_name,omitempty"`
	AwsCredentials  *createCredentialAwsCredentialsWire `json:"aws_credentials,omitempty"`
}

func createCredentialsRequestToWire(v *CreateCredentialsRequest) *createCredentialsRequestWire {
	if v == nil {
		return nil
	}
	return &createCredentialsRequestWire{
		AccountId:       v.AccountId,
		CredentialsName: v.CredentialsName,
		AwsCredentials:  createCredentialAwsCredentialsToWire(v.AwsCredentials),
	}
}

func createCredentialsRequestFromWire(w *createCredentialsRequestWire) *CreateCredentialsRequest {
	if w == nil {
		return nil
	}
	return &CreateCredentialsRequest{
		AccountId:       w.AccountId,
		CredentialsName: w.CredentialsName,
		AwsCredentials:  createCredentialAwsCredentialsFromWire(w.AwsCredentials),
	}
}

type createStorageCredentialRequestWire struct {
	SkipValidation              *bool                            `json:"skip_validation,omitempty"`
	Name                        *string                          `json:"name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	GcpServiceAccountKey        *gcpServiceAccountKeyWire        `json:"gcp_service_account_key,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	Comment                     *string                          `json:"comment,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
	Owner                       *string                          `json:"owner,omitempty"`
	Id                          *string                          `json:"id,omitempty"`
	MetastoreId                 *string                          `json:"metastore_id,omitempty"`
	CreatedAt                   *int64                           `json:"created_at,omitempty"`
	CreatedBy                   *string                          `json:"created_by,omitempty"`
	UpdatedAt                   *int64                           `json:"updated_at,omitempty"`
	UpdatedBy                   *string                          `json:"updated_by,omitempty"`
	UsedForManagedStorage       *bool                            `json:"used_for_managed_storage,omitempty"`
	FullName                    *string                          `json:"full_name,omitempty"`
	IsolationMode               IsolationMode                    `json:"isolation_mode,omitempty"`
}

func createStorageCredentialRequestToWire(v *CreateStorageCredentialRequest) *createStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &createStorageCredentialRequestWire{
		SkipValidation:              v.SkipValidation,
		Name:                        v.Name,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyToWire(v.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		Comment:                     v.Comment,
		ReadOnly:                    v.ReadOnly,
		Owner:                       v.Owner,
		Id:                          v.Id,
		MetastoreId:                 v.MetastoreId,
		CreatedAt:                   v.CreatedAt,
		CreatedBy:                   v.CreatedBy,
		UpdatedAt:                   v.UpdatedAt,
		UpdatedBy:                   v.UpdatedBy,
		UsedForManagedStorage:       v.UsedForManagedStorage,
		FullName:                    v.FullName,
		IsolationMode:               v.IsolationMode,
	}
}

func createStorageCredentialRequestFromWire(w *createStorageCredentialRequestWire) *CreateStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &CreateStorageCredentialRequest{
		SkipValidation:              w.SkipValidation,
		Name:                        w.Name,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyFromWire(w.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		Comment:                     w.Comment,
		ReadOnly:                    w.ReadOnly,
		Owner:                       w.Owner,
		Id:                          w.Id,
		MetastoreId:                 w.MetastoreId,
		CreatedAt:                   w.CreatedAt,
		CreatedBy:                   w.CreatedBy,
		UpdatedAt:                   w.UpdatedAt,
		UpdatedBy:                   w.UpdatedBy,
		UsedForManagedStorage:       w.UsedForManagedStorage,
		FullName:                    w.FullName,
		IsolationMode:               w.IsolationMode,
	}
}

type credentialInfoWire struct {
	Name                        *string                          `json:"name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	GcpServiceAccountKey        *gcpServiceAccountKeyWire        `json:"gcp_service_account_key,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	Comment                     *string                          `json:"comment,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
	Owner                       *string                          `json:"owner,omitempty"`
	Id                          *string                          `json:"id,omitempty"`
	MetastoreId                 *string                          `json:"metastore_id,omitempty"`
	CreatedAt                   *int64                           `json:"created_at,omitempty"`
	CreatedBy                   *string                          `json:"created_by,omitempty"`
	UpdatedAt                   *int64                           `json:"updated_at,omitempty"`
	UpdatedBy                   *string                          `json:"updated_by,omitempty"`
	UsedForManagedStorage       *bool                            `json:"used_for_managed_storage,omitempty"`
	FullName                    *string                          `json:"full_name,omitempty"`
	IsolationMode               IsolationMode                    `json:"isolation_mode,omitempty"`
}

func credentialInfoToWire(v *CredentialInfo) *credentialInfoWire {
	if v == nil {
		return nil
	}
	return &credentialInfoWire{
		Name:                        v.Name,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyToWire(v.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		Comment:                     v.Comment,
		ReadOnly:                    v.ReadOnly,
		Owner:                       v.Owner,
		Id:                          v.Id,
		MetastoreId:                 v.MetastoreId,
		CreatedAt:                   v.CreatedAt,
		CreatedBy:                   v.CreatedBy,
		UpdatedAt:                   v.UpdatedAt,
		UpdatedBy:                   v.UpdatedBy,
		UsedForManagedStorage:       v.UsedForManagedStorage,
		FullName:                    v.FullName,
		IsolationMode:               v.IsolationMode,
	}
}

func credentialInfoFromWire(w *credentialInfoWire) *CredentialInfo {
	if w == nil {
		return nil
	}
	return &CredentialInfo{
		Name:                        w.Name,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyFromWire(w.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		Comment:                     w.Comment,
		ReadOnly:                    w.ReadOnly,
		Owner:                       w.Owner,
		Id:                          w.Id,
		MetastoreId:                 w.MetastoreId,
		CreatedAt:                   w.CreatedAt,
		CreatedBy:                   w.CreatedBy,
		UpdatedAt:                   w.UpdatedAt,
		UpdatedBy:                   w.UpdatedBy,
		UsedForManagedStorage:       w.UsedForManagedStorage,
		FullName:                    w.FullName,
		IsolationMode:               w.IsolationMode,
	}
}

type credentialsWire struct {
	CredentialsId   *string             `json:"credentials_id,omitempty"`
	AccountId       *string             `json:"account_id,omitempty"`
	AwsCredentials  *awsCredentialsWire `json:"aws_credentials,omitempty"`
	CredentialsName *string             `json:"credentials_name,omitempty"`
	CreationTime    *int64              `json:"creation_time,omitempty"`
}

func credentialsToWire(v *Credentials) *credentialsWire {
	if v == nil {
		return nil
	}
	return &credentialsWire{
		CredentialsId:   v.CredentialsId,
		AccountId:       v.AccountId,
		AwsCredentials:  awsCredentialsToWire(v.AwsCredentials),
		CredentialsName: v.CredentialsName,
		CreationTime:    v.CreationTime,
	}
}

func credentialsFromWire(w *credentialsWire) *Credentials {
	if w == nil {
		return nil
	}
	return &Credentials{
		CredentialsId:   w.CredentialsId,
		AccountId:       w.AccountId,
		AwsCredentials:  awsCredentialsFromWire(w.AwsCredentials),
		CredentialsName: w.CredentialsName,
		CreationTime:    w.CreationTime,
	}
}

type databricksGcpServiceAccountWire struct {
	Email        *string `json:"email,omitempty"`
	PrivateKeyId *string `json:"private_key_id,omitempty"`
	CredentialId *string `json:"credential_id,omitempty"`
}

func databricksGcpServiceAccountToWire(v *DatabricksGcpServiceAccount) *databricksGcpServiceAccountWire {
	if v == nil {
		return nil
	}
	return &databricksGcpServiceAccountWire{
		Email:        v.Email,
		PrivateKeyId: v.PrivateKeyId,
		CredentialId: v.CredentialId,
	}
}

func databricksGcpServiceAccountFromWire(w *databricksGcpServiceAccountWire) *DatabricksGcpServiceAccount {
	if w == nil {
		return nil
	}
	return &DatabricksGcpServiceAccount{
		Email:        w.Email,
		PrivateKeyId: w.PrivateKeyId,
		CredentialId: w.CredentialId,
	}
}

type deleteCredentialRequestWire struct {
	NameArg *string `json:"name_arg,omitempty"`
	Force   *bool   `json:"force,omitempty"`
}

func deleteCredentialRequestToWire(v *DeleteCredentialRequest) *deleteCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &deleteCredentialRequestWire{
		NameArg: v.NameArg,
		Force:   v.Force,
	}
}

func deleteCredentialRequestFromWire(w *deleteCredentialRequestWire) *DeleteCredentialRequest {
	if w == nil {
		return nil
	}
	return &DeleteCredentialRequest{
		NameArg: w.NameArg,
		Force:   w.Force,
	}
}

type deleteCredentialResponseWire struct {
}

func deleteCredentialResponseToWire(v *DeleteCredentialResponse) *deleteCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &deleteCredentialResponseWire{}
}

func deleteCredentialResponseFromWire(w *deleteCredentialResponseWire) *DeleteCredentialResponse {
	if w == nil {
		return nil
	}
	return &DeleteCredentialResponse{}
}

type deleteCredentialsRequestWire struct {
	CredentialsId *string `json:"credentials_id,omitempty"`
	AccountId     *string `json:"account_id,omitempty"`
}

func deleteCredentialsRequestToWire(v *DeleteCredentialsRequest) *deleteCredentialsRequestWire {
	if v == nil {
		return nil
	}
	return &deleteCredentialsRequestWire{
		CredentialsId: v.CredentialsId,
		AccountId:     v.AccountId,
	}
}

func deleteCredentialsRequestFromWire(w *deleteCredentialsRequestWire) *DeleteCredentialsRequest {
	if w == nil {
		return nil
	}
	return &DeleteCredentialsRequest{
		CredentialsId: w.CredentialsId,
		AccountId:     w.AccountId,
	}
}

type deleteStorageCredentialRequestWire struct {
	NameArg *string `json:"name_arg,omitempty"`
	Force   *bool   `json:"force,omitempty"`
}

func deleteStorageCredentialRequestToWire(v *DeleteStorageCredentialRequest) *deleteStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &deleteStorageCredentialRequestWire{
		NameArg: v.NameArg,
		Force:   v.Force,
	}
}

func deleteStorageCredentialRequestFromWire(w *deleteStorageCredentialRequestWire) *DeleteStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &DeleteStorageCredentialRequest{
		NameArg: w.NameArg,
		Force:   w.Force,
	}
}

type deleteStorageCredentialResponseWire struct {
}

func deleteStorageCredentialResponseToWire(v *DeleteStorageCredentialResponse) *deleteStorageCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &deleteStorageCredentialResponseWire{}
}

func deleteStorageCredentialResponseFromWire(w *deleteStorageCredentialResponseWire) *DeleteStorageCredentialResponse {
	if w == nil {
		return nil
	}
	return &DeleteStorageCredentialResponse{}
}

type gcpOauthTokenWire struct {
	OauthToken *string `json:"oauth_token,omitempty"`
}

func gcpOauthTokenToWire(v *GcpOauthToken) *gcpOauthTokenWire {
	if v == nil {
		return nil
	}
	return &gcpOauthTokenWire{
		OauthToken: v.OauthToken,
	}
}

func gcpOauthTokenFromWire(w *gcpOauthTokenWire) *GcpOauthToken {
	if w == nil {
		return nil
	}
	return &GcpOauthToken{
		OauthToken: w.OauthToken,
	}
}

type gcpServiceAccountKeyWire struct {
	Email        *string `json:"email,omitempty"`
	PrivateKeyId *string `json:"private_key_id,omitempty"`
	PrivateKey   *string `json:"private_key,omitempty"`
}

func gcpServiceAccountKeyToWire(v *GcpServiceAccountKey) *gcpServiceAccountKeyWire {
	if v == nil {
		return nil
	}
	return &gcpServiceAccountKeyWire{
		Email:        v.Email,
		PrivateKeyId: v.PrivateKeyId,
		PrivateKey:   v.PrivateKey,
	}
}

func gcpServiceAccountKeyFromWire(w *gcpServiceAccountKeyWire) *GcpServiceAccountKey {
	if w == nil {
		return nil
	}
	return &GcpServiceAccountKey{
		Email:        w.Email,
		PrivateKeyId: w.PrivateKeyId,
		PrivateKey:   w.PrivateKey,
	}
}

type generateTemporaryPathCredentialRequestWire struct {
	Url       *string       `json:"url,omitempty"`
	Operation PathOperation `json:"operation,omitempty"`
	DryRun    *bool         `json:"dry_run,omitempty"`
}

func generateTemporaryPathCredentialRequestToWire(v *GenerateTemporaryPathCredentialRequest) *generateTemporaryPathCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryPathCredentialRequestWire{
		Url:       v.Url,
		Operation: v.Operation,
		DryRun:    v.DryRun,
	}
}

func generateTemporaryPathCredentialRequestFromWire(w *generateTemporaryPathCredentialRequestWire) *GenerateTemporaryPathCredentialRequest {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryPathCredentialRequest{
		Url:       w.Url,
		Operation: w.Operation,
		DryRun:    w.DryRun,
	}
}

type generateTemporaryPathCredentialResponseWire struct {
	AwsTempCredentials     *temporaryAwsCredentialsWire   `json:"aws_temp_credentials,omitempty"`
	AzureUserDelegationSas *azureUserDelegationSasWire    `json:"azure_user_delegation_sas,omitempty"`
	GcpOauthToken          *gcpOauthTokenWire             `json:"gcp_oauth_token,omitempty"`
	AzureAad               *azureActiveDirectoryTokenWire `json:"azure_aad,omitempty"`
	R2TempCredentials      *r2CredentialsWire             `json:"r2_temp_credentials,omitempty"`
	ExpirationTime         *int64                         `json:"expiration_time,omitempty"`
	Url                    *string                        `json:"url,omitempty"`
}

func generateTemporaryPathCredentialResponseToWire(v *GenerateTemporaryPathCredentialResponse) *generateTemporaryPathCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryPathCredentialResponseWire{
		AwsTempCredentials:     temporaryAwsCredentialsToWire(v.AwsTempCredentials),
		AzureUserDelegationSas: azureUserDelegationSasToWire(v.AzureUserDelegationSas),
		GcpOauthToken:          gcpOauthTokenToWire(v.GcpOauthToken),
		AzureAad:               azureActiveDirectoryTokenToWire(v.AzureAad),
		R2TempCredentials:      r2CredentialsToWire(v.R2TempCredentials),
		ExpirationTime:         v.ExpirationTime,
		Url:                    v.Url,
	}
}

func generateTemporaryPathCredentialResponseFromWire(w *generateTemporaryPathCredentialResponseWire) *GenerateTemporaryPathCredentialResponse {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryPathCredentialResponse{
		AwsTempCredentials:     temporaryAwsCredentialsFromWire(w.AwsTempCredentials),
		AzureUserDelegationSas: azureUserDelegationSasFromWire(w.AzureUserDelegationSas),
		GcpOauthToken:          gcpOauthTokenFromWire(w.GcpOauthToken),
		AzureAad:               azureActiveDirectoryTokenFromWire(w.AzureAad),
		R2TempCredentials:      r2CredentialsFromWire(w.R2TempCredentials),
		ExpirationTime:         w.ExpirationTime,
		Url:                    w.Url,
	}
}

type generateTemporaryServiceCredentialRequestWire struct {
	CredentialName *string                                                     `json:"credential_name,omitempty"`
	AzureOptions   *generateTemporaryServiceCredentialRequest_AzureOptionsWire `json:"azure_options,omitempty"`
	GcpOptions     *generateTemporaryServiceCredentialRequest_GcpOptionsWire   `json:"gcp_options,omitempty"`
}

func generateTemporaryServiceCredentialRequestToWire(v *GenerateTemporaryServiceCredentialRequest) *generateTemporaryServiceCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryServiceCredentialRequestWire{
		CredentialName: v.CredentialName,
		AzureOptions:   generateTemporaryServiceCredentialRequest_AzureOptionsToWire(v.AzureOptions),
		GcpOptions:     generateTemporaryServiceCredentialRequest_GcpOptionsToWire(v.GcpOptions),
	}
}

func generateTemporaryServiceCredentialRequestFromWire(w *generateTemporaryServiceCredentialRequestWire) *GenerateTemporaryServiceCredentialRequest {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryServiceCredentialRequest{
		CredentialName: w.CredentialName,
		AzureOptions:   generateTemporaryServiceCredentialRequest_AzureOptionsFromWire(w.AzureOptions),
		GcpOptions:     generateTemporaryServiceCredentialRequest_GcpOptionsFromWire(w.GcpOptions),
	}
}

type generateTemporaryServiceCredentialRequest_AzureOptionsWire struct {
	Resources []string `json:"resources,omitempty"`
}

func generateTemporaryServiceCredentialRequest_AzureOptionsToWire(v *GenerateTemporaryServiceCredentialRequest_AzureOptions) *generateTemporaryServiceCredentialRequest_AzureOptionsWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryServiceCredentialRequest_AzureOptionsWire{
		Resources: v.Resources,
	}
}

func generateTemporaryServiceCredentialRequest_AzureOptionsFromWire(w *generateTemporaryServiceCredentialRequest_AzureOptionsWire) *GenerateTemporaryServiceCredentialRequest_AzureOptions {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryServiceCredentialRequest_AzureOptions{
		Resources: w.Resources,
	}
}

type generateTemporaryServiceCredentialRequest_GcpOptionsWire struct {
	Scopes []string `json:"scopes,omitempty"`
}

func generateTemporaryServiceCredentialRequest_GcpOptionsToWire(v *GenerateTemporaryServiceCredentialRequest_GcpOptions) *generateTemporaryServiceCredentialRequest_GcpOptionsWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryServiceCredentialRequest_GcpOptionsWire{
		Scopes: v.Scopes,
	}
}

func generateTemporaryServiceCredentialRequest_GcpOptionsFromWire(w *generateTemporaryServiceCredentialRequest_GcpOptionsWire) *GenerateTemporaryServiceCredentialRequest_GcpOptions {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryServiceCredentialRequest_GcpOptions{
		Scopes: w.Scopes,
	}
}

type generateTemporaryTableCredentialRequestWire struct {
	TableId   *string        `json:"table_id,omitempty"`
	Operation TableOperation `json:"operation,omitempty"`
}

func generateTemporaryTableCredentialRequestToWire(v *GenerateTemporaryTableCredentialRequest) *generateTemporaryTableCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryTableCredentialRequestWire{
		TableId:   v.TableId,
		Operation: v.Operation,
	}
}

func generateTemporaryTableCredentialRequestFromWire(w *generateTemporaryTableCredentialRequestWire) *GenerateTemporaryTableCredentialRequest {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryTableCredentialRequest{
		TableId:   w.TableId,
		Operation: w.Operation,
	}
}

type generateTemporaryTableCredentialResponseWire struct {
	AwsTempCredentials     *temporaryAwsCredentialsWire   `json:"aws_temp_credentials,omitempty"`
	AzureUserDelegationSas *azureUserDelegationSasWire    `json:"azure_user_delegation_sas,omitempty"`
	GcpOauthToken          *gcpOauthTokenWire             `json:"gcp_oauth_token,omitempty"`
	AzureAad               *azureActiveDirectoryTokenWire `json:"azure_aad,omitempty"`
	R2TempCredentials      *r2CredentialsWire             `json:"r2_temp_credentials,omitempty"`
	ExpirationTime         *int64                         `json:"expiration_time,omitempty"`
	Url                    *string                        `json:"url,omitempty"`
}

func generateTemporaryTableCredentialResponseToWire(v *GenerateTemporaryTableCredentialResponse) *generateTemporaryTableCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryTableCredentialResponseWire{
		AwsTempCredentials:     temporaryAwsCredentialsToWire(v.AwsTempCredentials),
		AzureUserDelegationSas: azureUserDelegationSasToWire(v.AzureUserDelegationSas),
		GcpOauthToken:          gcpOauthTokenToWire(v.GcpOauthToken),
		AzureAad:               azureActiveDirectoryTokenToWire(v.AzureAad),
		R2TempCredentials:      r2CredentialsToWire(v.R2TempCredentials),
		ExpirationTime:         v.ExpirationTime,
		Url:                    v.Url,
	}
}

func generateTemporaryTableCredentialResponseFromWire(w *generateTemporaryTableCredentialResponseWire) *GenerateTemporaryTableCredentialResponse {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryTableCredentialResponse{
		AwsTempCredentials:     temporaryAwsCredentialsFromWire(w.AwsTempCredentials),
		AzureUserDelegationSas: azureUserDelegationSasFromWire(w.AzureUserDelegationSas),
		GcpOauthToken:          gcpOauthTokenFromWire(w.GcpOauthToken),
		AzureAad:               azureActiveDirectoryTokenFromWire(w.AzureAad),
		R2TempCredentials:      r2CredentialsFromWire(w.R2TempCredentials),
		ExpirationTime:         w.ExpirationTime,
		Url:                    w.Url,
	}
}

type generateTemporaryVolumeCredentialRequestWire struct {
	VolumeId  *string         `json:"volume_id,omitempty"`
	Operation VolumeOperation `json:"operation,omitempty"`
}

func generateTemporaryVolumeCredentialRequestToWire(v *GenerateTemporaryVolumeCredentialRequest) *generateTemporaryVolumeCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryVolumeCredentialRequestWire{
		VolumeId:  v.VolumeId,
		Operation: v.Operation,
	}
}

func generateTemporaryVolumeCredentialRequestFromWire(w *generateTemporaryVolumeCredentialRequestWire) *GenerateTemporaryVolumeCredentialRequest {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryVolumeCredentialRequest{
		VolumeId:  w.VolumeId,
		Operation: w.Operation,
	}
}

type generateTemporaryVolumeCredentialResponseWire struct {
	AwsTempCredentials     *temporaryAwsCredentialsWire   `json:"aws_temp_credentials,omitempty"`
	AzureUserDelegationSas *azureUserDelegationSasWire    `json:"azure_user_delegation_sas,omitempty"`
	GcpOauthToken          *gcpOauthTokenWire             `json:"gcp_oauth_token,omitempty"`
	AzureAad               *azureActiveDirectoryTokenWire `json:"azure_aad,omitempty"`
	R2TempCredentials      *r2CredentialsWire             `json:"r2_temp_credentials,omitempty"`
	ExpirationTime         *int64                         `json:"expiration_time,omitempty"`
	Url                    *string                        `json:"url,omitempty"`
}

func generateTemporaryVolumeCredentialResponseToWire(v *GenerateTemporaryVolumeCredentialResponse) *generateTemporaryVolumeCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &generateTemporaryVolumeCredentialResponseWire{
		AwsTempCredentials:     temporaryAwsCredentialsToWire(v.AwsTempCredentials),
		AzureUserDelegationSas: azureUserDelegationSasToWire(v.AzureUserDelegationSas),
		GcpOauthToken:          gcpOauthTokenToWire(v.GcpOauthToken),
		AzureAad:               azureActiveDirectoryTokenToWire(v.AzureAad),
		R2TempCredentials:      r2CredentialsToWire(v.R2TempCredentials),
		ExpirationTime:         v.ExpirationTime,
		Url:                    v.Url,
	}
}

func generateTemporaryVolumeCredentialResponseFromWire(w *generateTemporaryVolumeCredentialResponseWire) *GenerateTemporaryVolumeCredentialResponse {
	if w == nil {
		return nil
	}
	return &GenerateTemporaryVolumeCredentialResponse{
		AwsTempCredentials:     temporaryAwsCredentialsFromWire(w.AwsTempCredentials),
		AzureUserDelegationSas: azureUserDelegationSasFromWire(w.AzureUserDelegationSas),
		GcpOauthToken:          gcpOauthTokenFromWire(w.GcpOauthToken),
		AzureAad:               azureActiveDirectoryTokenFromWire(w.AzureAad),
		R2TempCredentials:      r2CredentialsFromWire(w.R2TempCredentials),
		ExpirationTime:         w.ExpirationTime,
		Url:                    w.Url,
	}
}

type getCredentialRequestWire struct {
	NameArg *string `json:"name_arg,omitempty"`
}

func getCredentialRequestToWire(v *GetCredentialRequest) *getCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &getCredentialRequestWire{
		NameArg: v.NameArg,
	}
}

func getCredentialRequestFromWire(w *getCredentialRequestWire) *GetCredentialRequest {
	if w == nil {
		return nil
	}
	return &GetCredentialRequest{
		NameArg: w.NameArg,
	}
}

type getCredentialsRequestWire struct {
	CredentialsId *string `json:"credentials_id,omitempty"`
	AccountId     *string `json:"account_id,omitempty"`
}

func getCredentialsRequestToWire(v *GetCredentialsRequest) *getCredentialsRequestWire {
	if v == nil {
		return nil
	}
	return &getCredentialsRequestWire{
		CredentialsId: v.CredentialsId,
		AccountId:     v.AccountId,
	}
}

func getCredentialsRequestFromWire(w *getCredentialsRequestWire) *GetCredentialsRequest {
	if w == nil {
		return nil
	}
	return &GetCredentialsRequest{
		CredentialsId: w.CredentialsId,
		AccountId:     w.AccountId,
	}
}

type getStorageCredentialRequestWire struct {
	NameArg *string `json:"name_arg,omitempty"`
}

func getStorageCredentialRequestToWire(v *GetStorageCredentialRequest) *getStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &getStorageCredentialRequestWire{
		NameArg: v.NameArg,
	}
}

func getStorageCredentialRequestFromWire(w *getStorageCredentialRequestWire) *GetStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &GetStorageCredentialRequest{
		NameArg: w.NameArg,
	}
}

type listCredentialsPublicRequestWire struct {
	AccountId *string `json:"account_id,omitempty"`
}

func listCredentialsPublicRequestToWire(v *ListCredentialsPublicRequest) *listCredentialsPublicRequestWire {
	if v == nil {
		return nil
	}
	return &listCredentialsPublicRequestWire{
		AccountId: v.AccountId,
	}
}

func listCredentialsPublicRequestFromWire(w *listCredentialsPublicRequestWire) *ListCredentialsPublicRequest {
	if w == nil {
		return nil
	}
	return &ListCredentialsPublicRequest{
		AccountId: w.AccountId,
	}
}

type listCredentialsRequestWire struct {
	IncludeUnbound *bool   `json:"include_unbound,omitempty"`
	MaxResults     *int    `json:"max_results,omitempty"`
	PageToken      *string `json:"page_token,omitempty"`
}

func listCredentialsRequestToWire(v *ListCredentialsRequest) *listCredentialsRequestWire {
	if v == nil {
		return nil
	}
	return &listCredentialsRequestWire{
		IncludeUnbound: v.IncludeUnbound,
		MaxResults:     v.MaxResults,
		PageToken:      v.PageToken,
	}
}

func listCredentialsRequestFromWire(w *listCredentialsRequestWire) *ListCredentialsRequest {
	if w == nil {
		return nil
	}
	return &ListCredentialsRequest{
		IncludeUnbound: w.IncludeUnbound,
		MaxResults:     w.MaxResults,
		PageToken:      w.PageToken,
	}
}

type listCredentialsRequest_ResponseWire struct {
	Credentials   []credentialInfoWire `json:"credentials,omitempty"`
	NextPageToken *string              `json:"next_page_token,omitempty"`
}

func listCredentialsRequest_ResponseToWire(v *ListCredentialsRequest_Response) *listCredentialsRequest_ResponseWire {
	if v == nil {
		return nil
	}
	return &listCredentialsRequest_ResponseWire{
		Credentials:   convertSlice(v.Credentials, credentialInfoToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listCredentialsRequest_ResponseFromWire(w *listCredentialsRequest_ResponseWire) *ListCredentialsRequest_Response {
	if w == nil {
		return nil
	}
	return &ListCredentialsRequest_Response{
		Credentials:   convertSlice(w.Credentials, credentialInfoFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type listCredentialsResponseWire struct {
	Credentials []credentialsWire `json:"credentials,omitempty"`
}

func listCredentialsResponseToWire(v *ListCredentialsResponse) *listCredentialsResponseWire {
	if v == nil {
		return nil
	}
	return &listCredentialsResponseWire{
		Credentials: convertSlice(v.Credentials, credentialsToWire),
	}
}

func listCredentialsResponseFromWire(w *listCredentialsResponseWire) *ListCredentialsResponse {
	if w == nil {
		return nil
	}
	return &ListCredentialsResponse{
		Credentials: convertSlice(w.Credentials, credentialsFromWire),
	}
}

type listStorageCredentialsRequestWire struct {
	IncludeUnbound *bool   `json:"include_unbound,omitempty"`
	MaxResults     *int    `json:"max_results,omitempty"`
	PageToken      *string `json:"page_token,omitempty"`
}

func listStorageCredentialsRequestToWire(v *ListStorageCredentialsRequest) *listStorageCredentialsRequestWire {
	if v == nil {
		return nil
	}
	return &listStorageCredentialsRequestWire{
		IncludeUnbound: v.IncludeUnbound,
		MaxResults:     v.MaxResults,
		PageToken:      v.PageToken,
	}
}

func listStorageCredentialsRequestFromWire(w *listStorageCredentialsRequestWire) *ListStorageCredentialsRequest {
	if w == nil {
		return nil
	}
	return &ListStorageCredentialsRequest{
		IncludeUnbound: w.IncludeUnbound,
		MaxResults:     w.MaxResults,
		PageToken:      w.PageToken,
	}
}

type listStorageCredentialsResponseWire struct {
	StorageCredentials []storageCredentialInfoWire `json:"storage_credentials,omitempty"`
	NextPageToken      *string                     `json:"next_page_token,omitempty"`
}

func listStorageCredentialsResponseToWire(v *ListStorageCredentialsResponse) *listStorageCredentialsResponseWire {
	if v == nil {
		return nil
	}
	return &listStorageCredentialsResponseWire{
		StorageCredentials: convertSlice(v.StorageCredentials, storageCredentialInfoToWire),
		NextPageToken:      v.NextPageToken,
	}
}

func listStorageCredentialsResponseFromWire(w *listStorageCredentialsResponseWire) *ListStorageCredentialsResponse {
	if w == nil {
		return nil
	}
	return &ListStorageCredentialsResponse{
		StorageCredentials: convertSlice(w.StorageCredentials, storageCredentialInfoFromWire),
		NextPageToken:      w.NextPageToken,
	}
}

type r2CredentialsWire struct {
	AccessKeyId     *string `json:"access_key_id,omitempty"`
	SecretAccessKey *string `json:"secret_access_key,omitempty"`
	SessionToken    *string `json:"session_token,omitempty"`
}

func r2CredentialsToWire(v *R2Credentials) *r2CredentialsWire {
	if v == nil {
		return nil
	}
	return &r2CredentialsWire{
		AccessKeyId:     v.AccessKeyId,
		SecretAccessKey: v.SecretAccessKey,
		SessionToken:    v.SessionToken,
	}
}

func r2CredentialsFromWire(w *r2CredentialsWire) *R2Credentials {
	if w == nil {
		return nil
	}
	return &R2Credentials{
		AccessKeyId:     w.AccessKeyId,
		SecretAccessKey: w.SecretAccessKey,
		SessionToken:    w.SessionToken,
	}
}

type storageCredentialInfoWire struct {
	Name                        *string                          `json:"name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	GcpServiceAccountKey        *gcpServiceAccountKeyWire        `json:"gcp_service_account_key,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	Comment                     *string                          `json:"comment,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
	Owner                       *string                          `json:"owner,omitempty"`
	Id                          *string                          `json:"id,omitempty"`
	MetastoreId                 *string                          `json:"metastore_id,omitempty"`
	CreatedAt                   *int64                           `json:"created_at,omitempty"`
	CreatedBy                   *string                          `json:"created_by,omitempty"`
	UpdatedAt                   *int64                           `json:"updated_at,omitempty"`
	UpdatedBy                   *string                          `json:"updated_by,omitempty"`
	UsedForManagedStorage       *bool                            `json:"used_for_managed_storage,omitempty"`
	FullName                    *string                          `json:"full_name,omitempty"`
	IsolationMode               IsolationMode                    `json:"isolation_mode,omitempty"`
}

func storageCredentialInfoToWire(v *StorageCredentialInfo) *storageCredentialInfoWire {
	if v == nil {
		return nil
	}
	return &storageCredentialInfoWire{
		Name:                        v.Name,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyToWire(v.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		Comment:                     v.Comment,
		ReadOnly:                    v.ReadOnly,
		Owner:                       v.Owner,
		Id:                          v.Id,
		MetastoreId:                 v.MetastoreId,
		CreatedAt:                   v.CreatedAt,
		CreatedBy:                   v.CreatedBy,
		UpdatedAt:                   v.UpdatedAt,
		UpdatedBy:                   v.UpdatedBy,
		UsedForManagedStorage:       v.UsedForManagedStorage,
		FullName:                    v.FullName,
		IsolationMode:               v.IsolationMode,
	}
}

func storageCredentialInfoFromWire(w *storageCredentialInfoWire) *StorageCredentialInfo {
	if w == nil {
		return nil
	}
	return &StorageCredentialInfo{
		Name:                        w.Name,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyFromWire(w.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		Comment:                     w.Comment,
		ReadOnly:                    w.ReadOnly,
		Owner:                       w.Owner,
		Id:                          w.Id,
		MetastoreId:                 w.MetastoreId,
		CreatedAt:                   w.CreatedAt,
		CreatedBy:                   w.CreatedBy,
		UpdatedAt:                   w.UpdatedAt,
		UpdatedBy:                   w.UpdatedBy,
		UsedForManagedStorage:       w.UsedForManagedStorage,
		FullName:                    w.FullName,
		IsolationMode:               w.IsolationMode,
	}
}

type temporaryAwsCredentialsWire struct {
	AccessKeyId     *string `json:"access_key_id,omitempty"`
	SecretAccessKey *string `json:"secret_access_key,omitempty"`
	SessionToken    *string `json:"session_token,omitempty"`
	AccessPoint     *string `json:"access_point,omitempty"`
}

func temporaryAwsCredentialsToWire(v *TemporaryAwsCredentials) *temporaryAwsCredentialsWire {
	if v == nil {
		return nil
	}
	return &temporaryAwsCredentialsWire{
		AccessKeyId:     v.AccessKeyId,
		SecretAccessKey: v.SecretAccessKey,
		SessionToken:    v.SessionToken,
		AccessPoint:     v.AccessPoint,
	}
}

func temporaryAwsCredentialsFromWire(w *temporaryAwsCredentialsWire) *TemporaryAwsCredentials {
	if w == nil {
		return nil
	}
	return &TemporaryAwsCredentials{
		AccessKeyId:     w.AccessKeyId,
		SecretAccessKey: w.SecretAccessKey,
		SessionToken:    w.SessionToken,
		AccessPoint:     w.AccessPoint,
	}
}

type temporaryCredentialsWire struct {
	AwsTempCredentials     *temporaryAwsCredentialsWire   `json:"aws_temp_credentials,omitempty"`
	AzureUserDelegationSas *azureUserDelegationSasWire    `json:"azure_user_delegation_sas,omitempty"`
	GcpOauthToken          *gcpOauthTokenWire             `json:"gcp_oauth_token,omitempty"`
	AzureAad               *azureActiveDirectoryTokenWire `json:"azure_aad,omitempty"`
	R2TempCredentials      *r2CredentialsWire             `json:"r2_temp_credentials,omitempty"`
	ExpirationTime         *int64                         `json:"expiration_time,omitempty"`
	Url                    *string                        `json:"url,omitempty"`
}

func temporaryCredentialsToWire(v *TemporaryCredentials) *temporaryCredentialsWire {
	if v == nil {
		return nil
	}
	return &temporaryCredentialsWire{
		AwsTempCredentials:     temporaryAwsCredentialsToWire(v.AwsTempCredentials),
		AzureUserDelegationSas: azureUserDelegationSasToWire(v.AzureUserDelegationSas),
		GcpOauthToken:          gcpOauthTokenToWire(v.GcpOauthToken),
		AzureAad:               azureActiveDirectoryTokenToWire(v.AzureAad),
		R2TempCredentials:      r2CredentialsToWire(v.R2TempCredentials),
		ExpirationTime:         v.ExpirationTime,
		Url:                    v.Url,
	}
}

func temporaryCredentialsFromWire(w *temporaryCredentialsWire) *TemporaryCredentials {
	if w == nil {
		return nil
	}
	return &TemporaryCredentials{
		AwsTempCredentials:     temporaryAwsCredentialsFromWire(w.AwsTempCredentials),
		AzureUserDelegationSas: azureUserDelegationSasFromWire(w.AzureUserDelegationSas),
		GcpOauthToken:          gcpOauthTokenFromWire(w.GcpOauthToken),
		AzureAad:               azureActiveDirectoryTokenFromWire(w.AzureAad),
		R2TempCredentials:      r2CredentialsFromWire(w.R2TempCredentials),
		ExpirationTime:         w.ExpirationTime,
		Url:                    w.Url,
	}
}

type updateAccountsStorageCredentialWire struct {
	Name                        *string                          `json:"name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	GcpServiceAccountKey        *gcpServiceAccountKeyWire        `json:"gcp_service_account_key,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	Comment                     *string                          `json:"comment,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
	Owner                       *string                          `json:"owner,omitempty"`
	Id                          *string                          `json:"id,omitempty"`
	MetastoreId                 *string                          `json:"metastore_id,omitempty"`
	CreatedAt                   *int64                           `json:"created_at,omitempty"`
	CreatedBy                   *string                          `json:"created_by,omitempty"`
	UpdatedAt                   *int64                           `json:"updated_at,omitempty"`
	UpdatedBy                   *string                          `json:"updated_by,omitempty"`
	UsedForManagedStorage       *bool                            `json:"used_for_managed_storage,omitempty"`
	FullName                    *string                          `json:"full_name,omitempty"`
	IsolationMode               IsolationMode                    `json:"isolation_mode,omitempty"`
}

func updateAccountsStorageCredentialToWire(v *UpdateAccountsStorageCredential) *updateAccountsStorageCredentialWire {
	if v == nil {
		return nil
	}
	return &updateAccountsStorageCredentialWire{
		Name:                        v.Name,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyToWire(v.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		Comment:                     v.Comment,
		ReadOnly:                    v.ReadOnly,
		Owner:                       v.Owner,
		Id:                          v.Id,
		MetastoreId:                 v.MetastoreId,
		CreatedAt:                   v.CreatedAt,
		CreatedBy:                   v.CreatedBy,
		UpdatedAt:                   v.UpdatedAt,
		UpdatedBy:                   v.UpdatedBy,
		UsedForManagedStorage:       v.UsedForManagedStorage,
		FullName:                    v.FullName,
		IsolationMode:               v.IsolationMode,
	}
}

func updateAccountsStorageCredentialFromWire(w *updateAccountsStorageCredentialWire) *UpdateAccountsStorageCredential {
	if w == nil {
		return nil
	}
	return &UpdateAccountsStorageCredential{
		Name:                        w.Name,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyFromWire(w.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		Comment:                     w.Comment,
		ReadOnly:                    w.ReadOnly,
		Owner:                       w.Owner,
		Id:                          w.Id,
		MetastoreId:                 w.MetastoreId,
		CreatedAt:                   w.CreatedAt,
		CreatedBy:                   w.CreatedBy,
		UpdatedAt:                   w.UpdatedAt,
		UpdatedBy:                   w.UpdatedBy,
		UsedForManagedStorage:       w.UsedForManagedStorage,
		FullName:                    w.FullName,
		IsolationMode:               w.IsolationMode,
	}
}

type updateCredentialRequestWire struct {
	NameArg                     *string                          `json:"name_arg,omitempty"`
	NewName                     *string                          `json:"new_name,omitempty"`
	SkipValidation              *bool                            `json:"skip_validation,omitempty"`
	Force                       *bool                            `json:"force,omitempty"`
	Name                        *string                          `json:"name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	GcpServiceAccountKey        *gcpServiceAccountKeyWire        `json:"gcp_service_account_key,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	Comment                     *string                          `json:"comment,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
	Owner                       *string                          `json:"owner,omitempty"`
	Id                          *string                          `json:"id,omitempty"`
	MetastoreId                 *string                          `json:"metastore_id,omitempty"`
	CreatedAt                   *int64                           `json:"created_at,omitempty"`
	CreatedBy                   *string                          `json:"created_by,omitempty"`
	UpdatedAt                   *int64                           `json:"updated_at,omitempty"`
	UpdatedBy                   *string                          `json:"updated_by,omitempty"`
	UsedForManagedStorage       *bool                            `json:"used_for_managed_storage,omitempty"`
	FullName                    *string                          `json:"full_name,omitempty"`
	IsolationMode               IsolationMode                    `json:"isolation_mode,omitempty"`
}

func updateCredentialRequestToWire(v *UpdateCredentialRequest) *updateCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &updateCredentialRequestWire{
		NameArg:                     v.NameArg,
		NewName:                     v.NewName,
		SkipValidation:              v.SkipValidation,
		Force:                       v.Force,
		Name:                        v.Name,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyToWire(v.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		Comment:                     v.Comment,
		ReadOnly:                    v.ReadOnly,
		Owner:                       v.Owner,
		Id:                          v.Id,
		MetastoreId:                 v.MetastoreId,
		CreatedAt:                   v.CreatedAt,
		CreatedBy:                   v.CreatedBy,
		UpdatedAt:                   v.UpdatedAt,
		UpdatedBy:                   v.UpdatedBy,
		UsedForManagedStorage:       v.UsedForManagedStorage,
		FullName:                    v.FullName,
		IsolationMode:               v.IsolationMode,
	}
}

func updateCredentialRequestFromWire(w *updateCredentialRequestWire) *UpdateCredentialRequest {
	if w == nil {
		return nil
	}
	return &UpdateCredentialRequest{
		NameArg:                     w.NameArg,
		NewName:                     w.NewName,
		SkipValidation:              w.SkipValidation,
		Force:                       w.Force,
		Name:                        w.Name,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyFromWire(w.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		Comment:                     w.Comment,
		ReadOnly:                    w.ReadOnly,
		Owner:                       w.Owner,
		Id:                          w.Id,
		MetastoreId:                 w.MetastoreId,
		CreatedAt:                   w.CreatedAt,
		CreatedBy:                   w.CreatedBy,
		UpdatedAt:                   w.UpdatedAt,
		UpdatedBy:                   w.UpdatedBy,
		UsedForManagedStorage:       w.UsedForManagedStorage,
		FullName:                    w.FullName,
		IsolationMode:               w.IsolationMode,
	}
}

type updateStorageCredentialRequestWire struct {
	NameArg                     *string                          `json:"name_arg,omitempty"`
	NewName                     *string                          `json:"new_name,omitempty"`
	SkipValidation              *bool                            `json:"skip_validation,omitempty"`
	Force                       *bool                            `json:"force,omitempty"`
	Name                        *string                          `json:"name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	GcpServiceAccountKey        *gcpServiceAccountKeyWire        `json:"gcp_service_account_key,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	Comment                     *string                          `json:"comment,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
	Owner                       *string                          `json:"owner,omitempty"`
	Id                          *string                          `json:"id,omitempty"`
	MetastoreId                 *string                          `json:"metastore_id,omitempty"`
	CreatedAt                   *int64                           `json:"created_at,omitempty"`
	CreatedBy                   *string                          `json:"created_by,omitempty"`
	UpdatedAt                   *int64                           `json:"updated_at,omitempty"`
	UpdatedBy                   *string                          `json:"updated_by,omitempty"`
	UsedForManagedStorage       *bool                            `json:"used_for_managed_storage,omitempty"`
	FullName                    *string                          `json:"full_name,omitempty"`
	IsolationMode               IsolationMode                    `json:"isolation_mode,omitempty"`
}

func updateStorageCredentialRequestToWire(v *UpdateStorageCredentialRequest) *updateStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &updateStorageCredentialRequestWire{
		NameArg:                     v.NameArg,
		NewName:                     v.NewName,
		SkipValidation:              v.SkipValidation,
		Force:                       v.Force,
		Name:                        v.Name,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyToWire(v.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		Comment:                     v.Comment,
		ReadOnly:                    v.ReadOnly,
		Owner:                       v.Owner,
		Id:                          v.Id,
		MetastoreId:                 v.MetastoreId,
		CreatedAt:                   v.CreatedAt,
		CreatedBy:                   v.CreatedBy,
		UpdatedAt:                   v.UpdatedAt,
		UpdatedBy:                   v.UpdatedBy,
		UsedForManagedStorage:       v.UsedForManagedStorage,
		FullName:                    v.FullName,
		IsolationMode:               v.IsolationMode,
	}
}

func updateStorageCredentialRequestFromWire(w *updateStorageCredentialRequestWire) *UpdateStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &UpdateStorageCredentialRequest{
		NameArg:                     w.NameArg,
		NewName:                     w.NewName,
		SkipValidation:              w.SkipValidation,
		Force:                       w.Force,
		Name:                        w.Name,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		GcpServiceAccountKey:        gcpServiceAccountKeyFromWire(w.GcpServiceAccountKey),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		Comment:                     w.Comment,
		ReadOnly:                    w.ReadOnly,
		Owner:                       w.Owner,
		Id:                          w.Id,
		MetastoreId:                 w.MetastoreId,
		CreatedAt:                   w.CreatedAt,
		CreatedBy:                   w.CreatedBy,
		UpdatedAt:                   w.UpdatedAt,
		UpdatedBy:                   w.UpdatedBy,
		UsedForManagedStorage:       w.UsedForManagedStorage,
		FullName:                    w.FullName,
		IsolationMode:               w.IsolationMode,
	}
}

type validateCredentialRequestWire struct {
	CredentialName              *string                          `json:"credential_name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	ExternalLocationName        *string                          `json:"external_location_name,omitempty"`
	Url                         *string                          `json:"url,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
}

func validateCredentialRequestToWire(v *ValidateCredentialRequest) *validateCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &validateCredentialRequestWire{
		CredentialName:              v.CredentialName,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		ExternalLocationName:        v.ExternalLocationName,
		Url:                         v.Url,
		ReadOnly:                    v.ReadOnly,
	}
}

func validateCredentialRequestFromWire(w *validateCredentialRequestWire) *ValidateCredentialRequest {
	if w == nil {
		return nil
	}
	return &ValidateCredentialRequest{
		CredentialName:              w.CredentialName,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		ExternalLocationName:        w.ExternalLocationName,
		Url:                         w.Url,
		ReadOnly:                    w.ReadOnly,
	}
}

type validateCredentialRequest_ValidationResultWire struct {
	Result  ValidateCredentialRequest_Result `json:"result,omitempty"`
	Message *string                          `json:"message,omitempty"`
}

func validateCredentialRequest_ValidationResultToWire(v *ValidateCredentialRequest_ValidationResult) *validateCredentialRequest_ValidationResultWire {
	if v == nil {
		return nil
	}
	return &validateCredentialRequest_ValidationResultWire{
		Result:  v.Result,
		Message: v.Message,
	}
}

func validateCredentialRequest_ValidationResultFromWire(w *validateCredentialRequest_ValidationResultWire) *ValidateCredentialRequest_ValidationResult {
	if w == nil {
		return nil
	}
	return &ValidateCredentialRequest_ValidationResult{
		Result:  w.Result,
		Message: w.Message,
	}
}

type validateCredentialResponseWire struct {
	Results []validateCredentialRequest_ValidationResultWire `json:"results,omitempty"`
	IsDir   *bool                                            `json:"isDir,omitempty"`
}

func validateCredentialResponseToWire(v *ValidateCredentialResponse) *validateCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &validateCredentialResponseWire{
		Results: convertSlice(v.Results, validateCredentialRequest_ValidationResultToWire),
		IsDir:   v.IsDir,
	}
}

func validateCredentialResponseFromWire(w *validateCredentialResponseWire) *ValidateCredentialResponse {
	if w == nil {
		return nil
	}
	return &ValidateCredentialResponse{
		Results: convertSlice(w.Results, validateCredentialRequest_ValidationResultFromWire),
		IsDir:   w.IsDir,
	}
}

type validateStorageCredentialRequestWire struct {
	StorageCredentialName       *string                          `json:"storage_credential_name,omitempty"`
	AwsIamRole                  *awsIamRoleWire                  `json:"aws_iam_role,omitempty"`
	AzureServicePrincipal       *azureServicePrincipalWire       `json:"azure_service_principal,omitempty"`
	AzureManagedIdentity        *azureManagedIdentityWire        `json:"azure_managed_identity,omitempty"`
	DatabricksGcpServiceAccount *databricksGcpServiceAccountWire `json:"databricks_gcp_service_account,omitempty"`
	CloudflareApiToken          *cloudflareApiTokenWire          `json:"cloudflare_api_token,omitempty"`
	ExternalLocationName        *string                          `json:"external_location_name,omitempty"`
	Url                         *string                          `json:"url,omitempty"`
	ReadOnly                    *bool                            `json:"read_only,omitempty"`
}

func validateStorageCredentialRequestToWire(v *ValidateStorageCredentialRequest) *validateStorageCredentialRequestWire {
	if v == nil {
		return nil
	}
	return &validateStorageCredentialRequestWire{
		StorageCredentialName:       v.StorageCredentialName,
		AwsIamRole:                  awsIamRoleToWire(v.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalToWire(v.AzureServicePrincipal),
		AzureManagedIdentity:        azureManagedIdentityToWire(v.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountToWire(v.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenToWire(v.CloudflareApiToken),
		ExternalLocationName:        v.ExternalLocationName,
		Url:                         v.Url,
		ReadOnly:                    v.ReadOnly,
	}
}

func validateStorageCredentialRequestFromWire(w *validateStorageCredentialRequestWire) *ValidateStorageCredentialRequest {
	if w == nil {
		return nil
	}
	return &ValidateStorageCredentialRequest{
		StorageCredentialName:       w.StorageCredentialName,
		AwsIamRole:                  awsIamRoleFromWire(w.AwsIamRole),
		AzureServicePrincipal:       azureServicePrincipalFromWire(w.AzureServicePrincipal),
		AzureManagedIdentity:        azureManagedIdentityFromWire(w.AzureManagedIdentity),
		DatabricksGcpServiceAccount: databricksGcpServiceAccountFromWire(w.DatabricksGcpServiceAccount),
		CloudflareApiToken:          cloudflareApiTokenFromWire(w.CloudflareApiToken),
		ExternalLocationName:        w.ExternalLocationName,
		Url:                         w.Url,
		ReadOnly:                    w.ReadOnly,
	}
}

type validateStorageCredentialRequest_ValidationResultWire struct {
	Operation ValidateStorageCredentialRequest_FileOperation `json:"operation,omitempty"`
	Result    ValidateStorageCredentialRequest_Result        `json:"result,omitempty"`
	Message   *string                                        `json:"message,omitempty"`
}

func validateStorageCredentialRequest_ValidationResultToWire(v *ValidateStorageCredentialRequest_ValidationResult) *validateStorageCredentialRequest_ValidationResultWire {
	if v == nil {
		return nil
	}
	return &validateStorageCredentialRequest_ValidationResultWire{
		Operation: v.Operation,
		Result:    v.Result,
		Message:   v.Message,
	}
}

func validateStorageCredentialRequest_ValidationResultFromWire(w *validateStorageCredentialRequest_ValidationResultWire) *ValidateStorageCredentialRequest_ValidationResult {
	if w == nil {
		return nil
	}
	return &ValidateStorageCredentialRequest_ValidationResult{
		Operation: w.Operation,
		Result:    w.Result,
		Message:   w.Message,
	}
}

type validateStorageCredentialResponseWire struct {
	IsDir   *bool                                                   `json:"isDir,omitempty"`
	Results []validateStorageCredentialRequest_ValidationResultWire `json:"results,omitempty"`
}

func validateStorageCredentialResponseToWire(v *ValidateStorageCredentialResponse) *validateStorageCredentialResponseWire {
	if v == nil {
		return nil
	}
	return &validateStorageCredentialResponseWire{
		IsDir:   v.IsDir,
		Results: convertSlice(v.Results, validateStorageCredentialRequest_ValidationResultToWire),
	}
}

func validateStorageCredentialResponseFromWire(w *validateStorageCredentialResponseWire) *ValidateStorageCredentialResponse {
	if w == nil {
		return nil
	}
	return &ValidateStorageCredentialResponse{
		IsDir:   w.IsDir,
		Results: convertSlice(w.Results, validateStorageCredentialRequest_ValidationResultFromWire),
	}
}

func convertSlice[T, W any](s []T, conv func(*T) *W) []W {
	if s == nil {
		return nil
	}
	out := make([]W, len(s))
	for i := range s {
		out[i] = *conv(&s[i])
	}
	return out
}
