// Code generated by Databricks SDK Generator. DO NOT EDIT.

package instanceprofiles

type AddInstanceProfileRequest struct {
	SkipValidation        *bool
	InstanceProfileArn    *string
	IsMetaInstanceProfile *bool
	IamRoleArn            *string
}

type AddInstanceProfileResponse struct {
}

type EditInstanceProfileRequest struct {
	InstanceProfileArn    *string
	IsMetaInstanceProfile *bool
	IamRoleArn            *string
}

type EditInstanceProfileResponse struct {
}

type InstanceProfile struct {
	InstanceProfileArn    *string
	IsMetaInstanceProfile *bool
	IamRoleArn            *string
}

type ListInstanceProfilesRequest struct {
}

type ListInstanceProfilesResponse struct {
	InstanceProfiles []InstanceProfile
}

type RemoveInstanceProfileRequest struct {
	InstanceProfileArn *string
}

type RemoveInstanceProfileResponse struct {
}
