// Code generated by Databricks SDK Generator. DO NOT EDIT.

package cleanrooms

type cleanRoomWire struct {
	Name                   *string                     `json:"name,omitempty"`
	RemoteDetailedInfo     *cleanRoomRemoteDetailWire  `json:"remote_detailed_info,omitempty"`
	Owner                  *string                     `json:"owner,omitempty"`
	Comment                *string                     `json:"comment,omitempty"`
	CreatedAt              *int64                      `json:"created_at,omitempty"`
	UpdatedAt              *int64                      `json:"updated_at,omitempty"`
	Status                 CleanRoom_Status_Enum       `json:"status,omitempty"`
	LocalCollaboratorAlias *string                     `json:"local_collaborator_alias,omitempty"`
	OutputCatalog          *cleanRoomOutputCatalogWire `json:"output_catalog,omitempty"`
	AccessRestricted       CleanRoom_AccessRestricted  `json:"access_restricted,omitempty"`
	EnableSharedOutput     *bool                       `json:"enable_shared_output,omitempty"`
}

func cleanRoomToWire(v *CleanRoom) *cleanRoomWire {
	if v == nil {
		return nil
	}
	return &cleanRoomWire{
		Name:                   v.Name,
		RemoteDetailedInfo:     cleanRoomRemoteDetailToWire(v.RemoteDetailedInfo),
		Owner:                  v.Owner,
		Comment:                v.Comment,
		CreatedAt:              v.CreatedAt,
		UpdatedAt:              v.UpdatedAt,
		Status:                 v.Status,
		LocalCollaboratorAlias: v.LocalCollaboratorAlias,
		OutputCatalog:          cleanRoomOutputCatalogToWire(v.OutputCatalog),
		AccessRestricted:       v.AccessRestricted,
		EnableSharedOutput:     v.EnableSharedOutput,
	}
}

func cleanRoomFromWire(w *cleanRoomWire) *CleanRoom {
	if w == nil {
		return nil
	}
	return &CleanRoom{
		Name:                   w.Name,
		RemoteDetailedInfo:     cleanRoomRemoteDetailFromWire(w.RemoteDetailedInfo),
		Owner:                  w.Owner,
		Comment:                w.Comment,
		CreatedAt:              w.CreatedAt,
		UpdatedAt:              w.UpdatedAt,
		Status:                 w.Status,
		LocalCollaboratorAlias: w.LocalCollaboratorAlias,
		OutputCatalog:          cleanRoomOutputCatalogFromWire(w.OutputCatalog),
		AccessRestricted:       w.AccessRestricted,
		EnableSharedOutput:     w.EnableSharedOutput,
	}
}

type cleanRoom_StatusWire struct {
}

func cleanRoom_StatusToWire(v *CleanRoom_Status) *cleanRoom_StatusWire {
	if v == nil {
		return nil
	}
	return &cleanRoom_StatusWire{}
}

func cleanRoom_StatusFromWire(w *cleanRoom_StatusWire) *CleanRoom_Status {
	if w == nil {
		return nil
	}
	return &CleanRoom_Status{}
}

type cleanRoomAssetWire struct {
	CleanRoomName            *string                                      `json:"clean_room_name,omitempty"`
	Name                     *string                                      `json:"name,omitempty"`
	AssetType                CleanRoomAsset_AssetType                     `json:"asset_type,omitempty"`
	AddedAt                  *int64                                       `json:"added_at,omitempty"`
	Status                   CleanRoomAsset_Status_Enum                   `json:"status,omitempty"`
	OwnerCollaboratorAlias   *string                                      `json:"owner_collaborator_alias,omitempty"`
	TableLocalDetails        *cleanRoomAsset_TableLocalDetailsWire        `json:"table_local_details,omitempty"`
	VolumeLocalDetails       *cleanRoomAsset_VolumeLocalDetailsWire       `json:"volume_local_details,omitempty"`
	ViewLocalDetails         *cleanRoomAsset_ViewLocalDetailsWire         `json:"view_local_details,omitempty"`
	ForeignTableLocalDetails *cleanRoomAsset_ForeignTableLocalDetailsWire `json:"foreign_table_local_details,omitempty"`
	Table                    *cleanRoomAsset_TableWire                    `json:"table,omitempty"`
	Notebook                 *cleanRoomAsset_NotebookWire                 `json:"notebook,omitempty"`
	View                     *cleanRoomAsset_ViewWire                     `json:"view,omitempty"`
	ForeignTable             *cleanRoomAsset_ForeignTableWire             `json:"foreign_table,omitempty"`
	JarAnalysis              *cleanRoomAsset_JarAnalysisWire              `json:"jar_analysis,omitempty"`
}

func cleanRoomAssetToWire(v *CleanRoomAsset) *cleanRoomAssetWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAssetWire{
		CleanRoomName:            v.CleanRoomName,
		Name:                     v.Name,
		AssetType:                v.AssetType,
		AddedAt:                  v.AddedAt,
		Status:                   v.Status,
		OwnerCollaboratorAlias:   v.OwnerCollaboratorAlias,
		TableLocalDetails:        cleanRoomAsset_TableLocalDetailsToWire(v.TableLocalDetails),
		VolumeLocalDetails:       cleanRoomAsset_VolumeLocalDetailsToWire(v.VolumeLocalDetails),
		ViewLocalDetails:         cleanRoomAsset_ViewLocalDetailsToWire(v.ViewLocalDetails),
		ForeignTableLocalDetails: cleanRoomAsset_ForeignTableLocalDetailsToWire(v.ForeignTableLocalDetails),
		Table:                    cleanRoomAsset_TableToWire(v.Table),
		Notebook:                 cleanRoomAsset_NotebookToWire(v.Notebook),
		View:                     cleanRoomAsset_ViewToWire(v.View),
		ForeignTable:             cleanRoomAsset_ForeignTableToWire(v.ForeignTable),
		JarAnalysis:              cleanRoomAsset_JarAnalysisToWire(v.JarAnalysis),
	}
}

func cleanRoomAssetFromWire(w *cleanRoomAssetWire) *CleanRoomAsset {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset{
		CleanRoomName:            w.CleanRoomName,
		Name:                     w.Name,
		AssetType:                w.AssetType,
		AddedAt:                  w.AddedAt,
		Status:                   w.Status,
		OwnerCollaboratorAlias:   w.OwnerCollaboratorAlias,
		TableLocalDetails:        cleanRoomAsset_TableLocalDetailsFromWire(w.TableLocalDetails),
		VolumeLocalDetails:       cleanRoomAsset_VolumeLocalDetailsFromWire(w.VolumeLocalDetails),
		ViewLocalDetails:         cleanRoomAsset_ViewLocalDetailsFromWire(w.ViewLocalDetails),
		ForeignTableLocalDetails: cleanRoomAsset_ForeignTableLocalDetailsFromWire(w.ForeignTableLocalDetails),
		Table:                    cleanRoomAsset_TableFromWire(w.Table),
		Notebook:                 cleanRoomAsset_NotebookFromWire(w.Notebook),
		View:                     cleanRoomAsset_ViewFromWire(w.View),
		ForeignTable:             cleanRoomAsset_ForeignTableFromWire(w.ForeignTable),
		JarAnalysis:              cleanRoomAsset_JarAnalysisFromWire(w.JarAnalysis),
	}
}

type cleanRoomAsset_ForeignTableWire struct {
	Columns []columnInfoWire `json:"columns,omitempty"`
}

func cleanRoomAsset_ForeignTableToWire(v *CleanRoomAsset_ForeignTable) *cleanRoomAsset_ForeignTableWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_ForeignTableWire{
		Columns: convertSlice(v.Columns, columnInfoToWire),
	}
}

func cleanRoomAsset_ForeignTableFromWire(w *cleanRoomAsset_ForeignTableWire) *CleanRoomAsset_ForeignTable {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_ForeignTable{
		Columns: convertSlice(w.Columns, columnInfoFromWire),
	}
}

type cleanRoomAsset_ForeignTableLocalDetailsWire struct {
	LocalName *string `json:"local_name,omitempty"`
}

func cleanRoomAsset_ForeignTableLocalDetailsToWire(v *CleanRoomAsset_ForeignTableLocalDetails) *cleanRoomAsset_ForeignTableLocalDetailsWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_ForeignTableLocalDetailsWire{
		LocalName: v.LocalName,
	}
}

func cleanRoomAsset_ForeignTableLocalDetailsFromWire(w *cleanRoomAsset_ForeignTableLocalDetailsWire) *CleanRoomAsset_ForeignTableLocalDetails {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_ForeignTableLocalDetails{
		LocalName: w.LocalName,
	}
}

type cleanRoomAsset_JarAnalysisWire struct {
	Etag                      *string                                           `json:"etag,omitempty"`
	Description               *string                                           `json:"description,omitempty"`
	RunnerCollaboratorAliases []string                                          `json:"runner_collaborator_aliases,omitempty"`
	Reviews                   []cleanRoomJarAnalysisReviewWire                  `json:"reviews,omitempty"`
	ReviewState               CleanRoomJarAnalysisReview_JarAnalysisReviewState `json:"review_state,omitempty"`
	MainClassName             *string                                           `json:"main_class_name,omitempty"`
	CentralJarFilePaths       []string                                          `json:"central_jar_file_paths,omitempty"`
	EnvironmentVersion        *string                                           `json:"environment_version,omitempty"`
}

func cleanRoomAsset_JarAnalysisToWire(v *CleanRoomAsset_JarAnalysis) *cleanRoomAsset_JarAnalysisWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_JarAnalysisWire{
		Etag:                      v.Etag,
		Description:               v.Description,
		RunnerCollaboratorAliases: v.RunnerCollaboratorAliases,
		Reviews:                   convertSlice(v.Reviews, cleanRoomJarAnalysisReviewToWire),
		ReviewState:               v.ReviewState,
		MainClassName:             v.MainClassName,
		CentralJarFilePaths:       v.CentralJarFilePaths,
		EnvironmentVersion:        v.EnvironmentVersion,
	}
}

func cleanRoomAsset_JarAnalysisFromWire(w *cleanRoomAsset_JarAnalysisWire) *CleanRoomAsset_JarAnalysis {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_JarAnalysis{
		Etag:                      w.Etag,
		Description:               w.Description,
		RunnerCollaboratorAliases: w.RunnerCollaboratorAliases,
		Reviews:                   convertSlice(w.Reviews, cleanRoomJarAnalysisReviewFromWire),
		ReviewState:               w.ReviewState,
		MainClassName:             w.MainClassName,
		CentralJarFilePaths:       w.CentralJarFilePaths,
		EnvironmentVersion:        w.EnvironmentVersion,
	}
}

type cleanRoomAsset_NotebookWire struct {
	NotebookContent           *string                                     `json:"notebook_content,omitempty"`
	Etag                      *string                                     `json:"etag,omitempty"`
	RunnerCollaboratorAliases []string                                    `json:"runner_collaborator_aliases,omitempty"`
	Reviews                   []cleanRoomNotebookReviewWire               `json:"reviews,omitempty"`
	ReviewState               CleanRoomNotebookReview_NotebookReviewState `json:"review_state,omitempty"`
	Description               *string                                     `json:"description,omitempty"`
	EnvironmentVersion        *string                                     `json:"environment_version,omitempty"`
}

func cleanRoomAsset_NotebookToWire(v *CleanRoomAsset_Notebook) *cleanRoomAsset_NotebookWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_NotebookWire{
		NotebookContent:           v.NotebookContent,
		Etag:                      v.Etag,
		RunnerCollaboratorAliases: v.RunnerCollaboratorAliases,
		Reviews:                   convertSlice(v.Reviews, cleanRoomNotebookReviewToWire),
		ReviewState:               v.ReviewState,
		Description:               v.Description,
		EnvironmentVersion:        v.EnvironmentVersion,
	}
}

func cleanRoomAsset_NotebookFromWire(w *cleanRoomAsset_NotebookWire) *CleanRoomAsset_Notebook {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_Notebook{
		NotebookContent:           w.NotebookContent,
		Etag:                      w.Etag,
		RunnerCollaboratorAliases: w.RunnerCollaboratorAliases,
		Reviews:                   convertSlice(w.Reviews, cleanRoomNotebookReviewFromWire),
		ReviewState:               w.ReviewState,
		Description:               w.Description,
		EnvironmentVersion:        w.EnvironmentVersion,
	}
}

type cleanRoomAsset_StatusWire struct {
}

func cleanRoomAsset_StatusToWire(v *CleanRoomAsset_Status) *cleanRoomAsset_StatusWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_StatusWire{}
}

func cleanRoomAsset_StatusFromWire(w *cleanRoomAsset_StatusWire) *CleanRoomAsset_Status {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_Status{}
}

type cleanRoomAsset_TableWire struct {
	Columns []columnInfoWire `json:"columns,omitempty"`
}

func cleanRoomAsset_TableToWire(v *CleanRoomAsset_Table) *cleanRoomAsset_TableWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_TableWire{
		Columns: convertSlice(v.Columns, columnInfoToWire),
	}
}

func cleanRoomAsset_TableFromWire(w *cleanRoomAsset_TableWire) *CleanRoomAsset_Table {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_Table{
		Columns: convertSlice(w.Columns, columnInfoFromWire),
	}
}

type cleanRoomAsset_TableLocalDetailsWire struct {
	LocalName  *string                                `json:"local_name,omitempty"`
	Partitions []partitionSpecification_PartitionWire `json:"partitions,omitempty"`
}

func cleanRoomAsset_TableLocalDetailsToWire(v *CleanRoomAsset_TableLocalDetails) *cleanRoomAsset_TableLocalDetailsWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_TableLocalDetailsWire{
		LocalName:  v.LocalName,
		Partitions: convertSlice(v.Partitions, partitionSpecification_PartitionToWire),
	}
}

func cleanRoomAsset_TableLocalDetailsFromWire(w *cleanRoomAsset_TableLocalDetailsWire) *CleanRoomAsset_TableLocalDetails {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_TableLocalDetails{
		LocalName:  w.LocalName,
		Partitions: convertSlice(w.Partitions, partitionSpecification_PartitionFromWire),
	}
}

type cleanRoomAsset_ViewWire struct {
	Columns []columnInfoWire `json:"columns,omitempty"`
}

func cleanRoomAsset_ViewToWire(v *CleanRoomAsset_View) *cleanRoomAsset_ViewWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_ViewWire{
		Columns: convertSlice(v.Columns, columnInfoToWire),
	}
}

func cleanRoomAsset_ViewFromWire(w *cleanRoomAsset_ViewWire) *CleanRoomAsset_View {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_View{
		Columns: convertSlice(w.Columns, columnInfoFromWire),
	}
}

type cleanRoomAsset_ViewLocalDetailsWire struct {
	LocalName *string `json:"local_name,omitempty"`
}

func cleanRoomAsset_ViewLocalDetailsToWire(v *CleanRoomAsset_ViewLocalDetails) *cleanRoomAsset_ViewLocalDetailsWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_ViewLocalDetailsWire{
		LocalName: v.LocalName,
	}
}

func cleanRoomAsset_ViewLocalDetailsFromWire(w *cleanRoomAsset_ViewLocalDetailsWire) *CleanRoomAsset_ViewLocalDetails {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_ViewLocalDetails{
		LocalName: w.LocalName,
	}
}

type cleanRoomAsset_VolumeLocalDetailsWire struct {
	LocalName *string `json:"local_name,omitempty"`
}

func cleanRoomAsset_VolumeLocalDetailsToWire(v *CleanRoomAsset_VolumeLocalDetails) *cleanRoomAsset_VolumeLocalDetailsWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAsset_VolumeLocalDetailsWire{
		LocalName: v.LocalName,
	}
}

func cleanRoomAsset_VolumeLocalDetailsFromWire(w *cleanRoomAsset_VolumeLocalDetailsWire) *CleanRoomAsset_VolumeLocalDetails {
	if w == nil {
		return nil
	}
	return &CleanRoomAsset_VolumeLocalDetails{
		LocalName: w.LocalName,
	}
}

type cleanRoomAutoApprovalRuleWire struct {
	CleanRoomName              *string                               `json:"clean_room_name,omitempty"`
	RuleId                     *string                               `json:"rule_id,omitempty"`
	RuleOwnerCollaboratorAlias *string                               `json:"rule_owner_collaborator_alias,omitempty"`
	AuthorCollaboratorAlias    *string                               `json:"author_collaborator_alias,omitempty"`
	AuthorScope                CleanRoomAutoApprovalRule_AuthorScope `json:"author_scope,omitempty"`
	RunnerCollaboratorAlias    *string                               `json:"runner_collaborator_alias,omitempty"`
	CreatedAt                  *int64                                `json:"created_at,omitempty"`
}

func cleanRoomAutoApprovalRuleToWire(v *CleanRoomAutoApprovalRule) *cleanRoomAutoApprovalRuleWire {
	if v == nil {
		return nil
	}
	return &cleanRoomAutoApprovalRuleWire{
		CleanRoomName:              v.CleanRoomName,
		RuleId:                     v.RuleId,
		RuleOwnerCollaboratorAlias: v.RuleOwnerCollaboratorAlias,
		AuthorCollaboratorAlias:    v.AuthorCollaboratorAlias,
		AuthorScope:                v.AuthorScope,
		RunnerCollaboratorAlias:    v.RunnerCollaboratorAlias,
		CreatedAt:                  v.CreatedAt,
	}
}

func cleanRoomAutoApprovalRuleFromWire(w *cleanRoomAutoApprovalRuleWire) *CleanRoomAutoApprovalRule {
	if w == nil {
		return nil
	}
	return &CleanRoomAutoApprovalRule{
		CleanRoomName:              w.CleanRoomName,
		RuleId:                     w.RuleId,
		RuleOwnerCollaboratorAlias: w.RuleOwnerCollaboratorAlias,
		AuthorCollaboratorAlias:    w.AuthorCollaboratorAlias,
		AuthorScope:                w.AuthorScope,
		RunnerCollaboratorAlias:    w.RunnerCollaboratorAlias,
		CreatedAt:                  w.CreatedAt,
	}
}

type cleanRoomCollaboratorWire struct {
	GlobalMetastoreId          *string `json:"global_metastore_id,omitempty"`
	OrganizationName           *string `json:"organization_name,omitempty"`
	InviteRecipientWorkspaceId *int64  `json:"invite_recipient_workspace_id,omitempty"`
	InviteRecipientEmail       *string `json:"invite_recipient_email,omitempty"`
	CollaboratorAlias          *string `json:"collaborator_alias,omitempty"`
	DisplayName                *string `json:"display_name,omitempty"`
}

func cleanRoomCollaboratorToWire(v *CleanRoomCollaborator) *cleanRoomCollaboratorWire {
	if v == nil {
		return nil
	}
	return &cleanRoomCollaboratorWire{
		GlobalMetastoreId:          v.GlobalMetastoreId,
		OrganizationName:           v.OrganizationName,
		InviteRecipientWorkspaceId: v.InviteRecipientWorkspaceId,
		InviteRecipientEmail:       v.InviteRecipientEmail,
		CollaboratorAlias:          v.CollaboratorAlias,
		DisplayName:                v.DisplayName,
	}
}

func cleanRoomCollaboratorFromWire(w *cleanRoomCollaboratorWire) *CleanRoomCollaborator {
	if w == nil {
		return nil
	}
	return &CleanRoomCollaborator{
		GlobalMetastoreId:          w.GlobalMetastoreId,
		OrganizationName:           w.OrganizationName,
		InviteRecipientWorkspaceId: w.InviteRecipientWorkspaceId,
		InviteRecipientEmail:       w.InviteRecipientEmail,
		CollaboratorAlias:          w.CollaboratorAlias,
		DisplayName:                w.DisplayName,
	}
}

type cleanRoomJarAnalysisReviewWire struct {
	ReviewerCollaboratorAlias *string                                               `json:"reviewer_collaborator_alias,omitempty"`
	CreatedAtMillis           *int64                                                `json:"created_at_millis,omitempty"`
	ReviewState               CleanRoomJarAnalysisReview_JarAnalysisReviewState     `json:"review_state,omitempty"`
	Comment                   *string                                               `json:"comment,omitempty"`
	ReviewSubReason           CleanRoomJarAnalysisReview_JarAnalysisReviewSubReason `json:"review_sub_reason,omitempty"`
}

func cleanRoomJarAnalysisReviewToWire(v *CleanRoomJarAnalysisReview) *cleanRoomJarAnalysisReviewWire {
	if v == nil {
		return nil
	}
	return &cleanRoomJarAnalysisReviewWire{
		ReviewerCollaboratorAlias: v.ReviewerCollaboratorAlias,
		CreatedAtMillis:           v.CreatedAtMillis,
		ReviewState:               v.ReviewState,
		Comment:                   v.Comment,
		ReviewSubReason:           v.ReviewSubReason,
	}
}

func cleanRoomJarAnalysisReviewFromWire(w *cleanRoomJarAnalysisReviewWire) *CleanRoomJarAnalysisReview {
	if w == nil {
		return nil
	}
	return &CleanRoomJarAnalysisReview{
		ReviewerCollaboratorAlias: w.ReviewerCollaboratorAlias,
		CreatedAtMillis:           w.CreatedAtMillis,
		ReviewState:               w.ReviewState,
		Comment:                   w.Comment,
		ReviewSubReason:           w.ReviewSubReason,
	}
}

type cleanRoomNotebookReviewWire struct {
	ReviewerCollaboratorAlias *string                                         `json:"reviewer_collaborator_alias,omitempty"`
	CreatedAtMillis           *int64                                          `json:"created_at_millis,omitempty"`
	ReviewState               CleanRoomNotebookReview_NotebookReviewState     `json:"review_state,omitempty"`
	Comment                   *string                                         `json:"comment,omitempty"`
	ReviewSubReason           CleanRoomNotebookReview_NotebookReviewSubReason `json:"review_sub_reason,omitempty"`
}

func cleanRoomNotebookReviewToWire(v *CleanRoomNotebookReview) *cleanRoomNotebookReviewWire {
	if v == nil {
		return nil
	}
	return &cleanRoomNotebookReviewWire{
		ReviewerCollaboratorAlias: v.ReviewerCollaboratorAlias,
		CreatedAtMillis:           v.CreatedAtMillis,
		ReviewState:               v.ReviewState,
		Comment:                   v.Comment,
		ReviewSubReason:           v.ReviewSubReason,
	}
}

func cleanRoomNotebookReviewFromWire(w *cleanRoomNotebookReviewWire) *CleanRoomNotebookReview {
	if w == nil {
		return nil
	}
	return &CleanRoomNotebookReview{
		ReviewerCollaboratorAlias: w.ReviewerCollaboratorAlias,
		CreatedAtMillis:           w.CreatedAtMillis,
		ReviewState:               w.ReviewState,
		Comment:                   w.Comment,
		ReviewSubReason:           w.ReviewSubReason,
	}
}

type cleanRoomNotebookTaskRunWire struct {
	NotebookName                     *string                     `json:"notebook_name,omitempty"`
	StartTime                        *int64                      `json:"start_time,omitempty"`
	RunDuration                      *int64                      `json:"run_duration,omitempty"`
	NotebookJobRunState              *cleanRoomTaskRunStateWire  `json:"notebook_job_run_state,omitempty"`
	CollaboratorJobRunInfo           *collaboratorJobRunInfoWire `json:"collaborator_job_run_info,omitempty"`
	OutputSchemaName                 *string                     `json:"output_schema_name,omitempty"`
	OutputSchemaExpirationTime       *int64                      `json:"output_schema_expiration_time,omitempty"`
	NotebookEtag                     *string                     `json:"notebook_etag,omitempty"`
	NotebookUpdatedAt                *int64                      `json:"notebook_updated_at,omitempty"`
	SharedOutputSchemaName           *string                     `json:"shared_output_schema_name,omitempty"`
	SharedOutputSchemaExpirationTime *int64                      `json:"shared_output_schema_expiration_time,omitempty"`
}

func cleanRoomNotebookTaskRunToWire(v *CleanRoomNotebookTaskRun) *cleanRoomNotebookTaskRunWire {
	if v == nil {
		return nil
	}
	return &cleanRoomNotebookTaskRunWire{
		NotebookName:                     v.NotebookName,
		StartTime:                        v.StartTime,
		RunDuration:                      v.RunDuration,
		NotebookJobRunState:              cleanRoomTaskRunStateToWire(v.NotebookJobRunState),
		CollaboratorJobRunInfo:           collaboratorJobRunInfoToWire(v.CollaboratorJobRunInfo),
		OutputSchemaName:                 v.OutputSchemaName,
		OutputSchemaExpirationTime:       v.OutputSchemaExpirationTime,
		NotebookEtag:                     v.NotebookEtag,
		NotebookUpdatedAt:                v.NotebookUpdatedAt,
		SharedOutputSchemaName:           v.SharedOutputSchemaName,
		SharedOutputSchemaExpirationTime: v.SharedOutputSchemaExpirationTime,
	}
}

func cleanRoomNotebookTaskRunFromWire(w *cleanRoomNotebookTaskRunWire) *CleanRoomNotebookTaskRun {
	if w == nil {
		return nil
	}
	return &CleanRoomNotebookTaskRun{
		NotebookName:                     w.NotebookName,
		StartTime:                        w.StartTime,
		RunDuration:                      w.RunDuration,
		NotebookJobRunState:              cleanRoomTaskRunStateFromWire(w.NotebookJobRunState),
		CollaboratorJobRunInfo:           collaboratorJobRunInfoFromWire(w.CollaboratorJobRunInfo),
		OutputSchemaName:                 w.OutputSchemaName,
		OutputSchemaExpirationTime:       w.OutputSchemaExpirationTime,
		NotebookEtag:                     w.NotebookEtag,
		NotebookUpdatedAt:                w.NotebookUpdatedAt,
		SharedOutputSchemaName:           w.SharedOutputSchemaName,
		SharedOutputSchemaExpirationTime: w.SharedOutputSchemaExpirationTime,
	}
}

type cleanRoomOutputCatalogWire struct {
	Status      CleanRoomOutputCatalog_OutputCatalogStatus `json:"status,omitempty"`
	CatalogName *string                                    `json:"catalog_name,omitempty"`
}

func cleanRoomOutputCatalogToWire(v *CleanRoomOutputCatalog) *cleanRoomOutputCatalogWire {
	if v == nil {
		return nil
	}
	return &cleanRoomOutputCatalogWire{
		Status:      v.Status,
		CatalogName: v.CatalogName,
	}
}

func cleanRoomOutputCatalogFromWire(w *cleanRoomOutputCatalogWire) *CleanRoomOutputCatalog {
	if w == nil {
		return nil
	}
	return &CleanRoomOutputCatalog{
		Status:      w.Status,
		CatalogName: w.CatalogName,
	}
}

type cleanRoomRemoteDetailWire struct {
	CentralCleanRoomId               *string                        `json:"central_clean_room_id,omitempty"`
	CloudVendor                      *string                        `json:"cloud_vendor,omitempty"`
	Region                           *string                        `json:"region,omitempty"`
	Collaborators                    []cleanRoomCollaboratorWire    `json:"collaborators,omitempty"`
	Creator                          *cleanRoomCollaboratorWire     `json:"creator,omitempty"`
	EgressNetworkPolicy              *egressNetworkPolicyWire       `json:"egress_network_policy,omitempty"`
	ComplianceSecurityProfile        *complianceSecurityProfileWire `json:"compliance_security_profile,omitempty"`
	EnableSharedOutput               *bool                          `json:"enable_shared_output,omitempty"`
	PackageProviderCollaboratorAlias *string                        `json:"package_provider_collaborator_alias,omitempty"`
}

func cleanRoomRemoteDetailToWire(v *CleanRoomRemoteDetail) *cleanRoomRemoteDetailWire {
	if v == nil {
		return nil
	}
	return &cleanRoomRemoteDetailWire{
		CentralCleanRoomId:               v.CentralCleanRoomId,
		CloudVendor:                      v.CloudVendor,
		Region:                           v.Region,
		Collaborators:                    convertSlice(v.Collaborators, cleanRoomCollaboratorToWire),
		Creator:                          cleanRoomCollaboratorToWire(v.Creator),
		EgressNetworkPolicy:              egressNetworkPolicyToWire(v.EgressNetworkPolicy),
		ComplianceSecurityProfile:        complianceSecurityProfileToWire(v.ComplianceSecurityProfile),
		EnableSharedOutput:               v.EnableSharedOutput,
		PackageProviderCollaboratorAlias: v.PackageProviderCollaboratorAlias,
	}
}

func cleanRoomRemoteDetailFromWire(w *cleanRoomRemoteDetailWire) *CleanRoomRemoteDetail {
	if w == nil {
		return nil
	}
	return &CleanRoomRemoteDetail{
		CentralCleanRoomId:               w.CentralCleanRoomId,
		CloudVendor:                      w.CloudVendor,
		Region:                           w.Region,
		Collaborators:                    convertSlice(w.Collaborators, cleanRoomCollaboratorFromWire),
		Creator:                          cleanRoomCollaboratorFromWire(w.Creator),
		EgressNetworkPolicy:              egressNetworkPolicyFromWire(w.EgressNetworkPolicy),
		ComplianceSecurityProfile:        complianceSecurityProfileFromWire(w.ComplianceSecurityProfile),
		EnableSharedOutput:               w.EnableSharedOutput,
		PackageProviderCollaboratorAlias: w.PackageProviderCollaboratorAlias,
	}
}

type cleanRoomTaskRunWire struct {
	Name                   *string                                            `json:"name,omitempty"`
	TaskType               CleanRoomTaskType                                  `json:"task_type,omitempty"`
	StartTime              *int64                                             `json:"start_time,omitempty"`
	RunDuration            *int64                                             `json:"run_duration,omitempty"`
	TaskRunState           *cleanRoomTaskRunStateWire                         `json:"task_run_state,omitempty"`
	CollaboratorJobRunInfo *collaboratorJobRunInfoWire                        `json:"collaborator_job_run_info,omitempty"`
	OutputInfo             *cleanRoomTaskRun_OutputInfoWire                   `json:"output_info,omitempty"`
	AnalysisDetails        *cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsWire `json:"analysis_details,omitempty"`
	SharedOutputInfo       *cleanRoomTaskRun_OutputInfoWire                   `json:"shared_output_info,omitempty"`
}

func cleanRoomTaskRunToWire(v *CleanRoomTaskRun) *cleanRoomTaskRunWire {
	if v == nil {
		return nil
	}
	return &cleanRoomTaskRunWire{
		Name:                   v.Name,
		TaskType:               v.TaskType,
		StartTime:              v.StartTime,
		RunDuration:            v.RunDuration,
		TaskRunState:           cleanRoomTaskRunStateToWire(v.TaskRunState),
		CollaboratorJobRunInfo: collaboratorJobRunInfoToWire(v.CollaboratorJobRunInfo),
		OutputInfo:             cleanRoomTaskRun_OutputInfoToWire(v.OutputInfo),
		AnalysisDetails:        cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsToWire(v.AnalysisDetails),
		SharedOutputInfo:       cleanRoomTaskRun_OutputInfoToWire(v.SharedOutputInfo),
	}
}

func cleanRoomTaskRunFromWire(w *cleanRoomTaskRunWire) *CleanRoomTaskRun {
	if w == nil {
		return nil
	}
	return &CleanRoomTaskRun{
		Name:                   w.Name,
		TaskType:               w.TaskType,
		StartTime:              w.StartTime,
		RunDuration:            w.RunDuration,
		TaskRunState:           cleanRoomTaskRunStateFromWire(w.TaskRunState),
		CollaboratorJobRunInfo: collaboratorJobRunInfoFromWire(w.CollaboratorJobRunInfo),
		OutputInfo:             cleanRoomTaskRun_OutputInfoFromWire(w.OutputInfo),
		AnalysisDetails:        cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsFromWire(w.AnalysisDetails),
		SharedOutputInfo:       cleanRoomTaskRun_OutputInfoFromWire(w.SharedOutputInfo),
	}
}

type cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsWire struct {
	Etag      *string `json:"etag,omitempty"`
	UpdatedAt *int64  `json:"updated_at,omitempty"`
}

func cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsToWire(v *CleanRoomTaskRun_CleanRoomTaskAnalysisDetails) *cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsWire {
	if v == nil {
		return nil
	}
	return &cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsWire{
		Etag:      v.Etag,
		UpdatedAt: v.UpdatedAt,
	}
}

func cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsFromWire(w *cleanRoomTaskRun_CleanRoomTaskAnalysisDetailsWire) *CleanRoomTaskRun_CleanRoomTaskAnalysisDetails {
	if w == nil {
		return nil
	}
	return &CleanRoomTaskRun_CleanRoomTaskAnalysisDetails{
		Etag:      w.Etag,
		UpdatedAt: w.UpdatedAt,
	}
}

type cleanRoomTaskRun_OutputInfoWire struct {
	OutputSchemaName           *string `json:"output_schema_name,omitempty"`
	OutputSchemaExpirationTime *int64  `json:"output_schema_expiration_time,omitempty"`
}

func cleanRoomTaskRun_OutputInfoToWire(v *CleanRoomTaskRun_OutputInfo) *cleanRoomTaskRun_OutputInfoWire {
	if v == nil {
		return nil
	}
	return &cleanRoomTaskRun_OutputInfoWire{
		OutputSchemaName:           v.OutputSchemaName,
		OutputSchemaExpirationTime: v.OutputSchemaExpirationTime,
	}
}

func cleanRoomTaskRun_OutputInfoFromWire(w *cleanRoomTaskRun_OutputInfoWire) *CleanRoomTaskRun_OutputInfo {
	if w == nil {
		return nil
	}
	return &CleanRoomTaskRun_OutputInfo{
		OutputSchemaName:           w.OutputSchemaName,
		OutputSchemaExpirationTime: w.OutputSchemaExpirationTime,
	}
}

type cleanRoomTaskRunStateWire struct {
	LifeCycleState CleanRoomTaskRunLifeCycleState `json:"life_cycle_state,omitempty"`
	ResultState    CleanRoomTaskRunResultState    `json:"result_state,omitempty"`
}

func cleanRoomTaskRunStateToWire(v *CleanRoomTaskRunState) *cleanRoomTaskRunStateWire {
	if v == nil {
		return nil
	}
	return &cleanRoomTaskRunStateWire{
		LifeCycleState: v.LifeCycleState,
		ResultState:    v.ResultState,
	}
}

func cleanRoomTaskRunStateFromWire(w *cleanRoomTaskRunStateWire) *CleanRoomTaskRunState {
	if w == nil {
		return nil
	}
	return &CleanRoomTaskRunState{
		LifeCycleState: w.LifeCycleState,
		ResultState:    w.ResultState,
	}
}

type collaboratorJobRunInfoWire struct {
	CollaboratorJobId       *int64  `json:"collaborator_job_id,omitempty"`
	CollaboratorJobRunId    *int64  `json:"collaborator_job_run_id,omitempty"`
	CollaboratorTaskRunId   *int64  `json:"collaborator_task_run_id,omitempty"`
	CollaboratorWorkspaceId *int64  `json:"collaborator_workspace_id,omitempty"`
	CollaboratorAlias       *string `json:"collaborator_alias,omitempty"`
}

func collaboratorJobRunInfoToWire(v *CollaboratorJobRunInfo) *collaboratorJobRunInfoWire {
	if v == nil {
		return nil
	}
	return &collaboratorJobRunInfoWire{
		CollaboratorJobId:       v.CollaboratorJobId,
		CollaboratorJobRunId:    v.CollaboratorJobRunId,
		CollaboratorTaskRunId:   v.CollaboratorTaskRunId,
		CollaboratorWorkspaceId: v.CollaboratorWorkspaceId,
		CollaboratorAlias:       v.CollaboratorAlias,
	}
}

func collaboratorJobRunInfoFromWire(w *collaboratorJobRunInfoWire) *CollaboratorJobRunInfo {
	if w == nil {
		return nil
	}
	return &CollaboratorJobRunInfo{
		CollaboratorJobId:       w.CollaboratorJobId,
		CollaboratorJobRunId:    w.CollaboratorJobRunId,
		CollaboratorTaskRunId:   w.CollaboratorTaskRunId,
		CollaboratorWorkspaceId: w.CollaboratorWorkspaceId,
		CollaboratorAlias:       w.CollaboratorAlias,
	}
}

type columnInfoWire struct {
	Name             *string         `json:"name,omitempty"`
	TypeText         *string         `json:"type_text,omitempty"`
	TypeName         ColumnTypeName  `json:"type_name,omitempty"`
	Position         *int            `json:"position,omitempty"`
	TypePrecision    *int            `json:"type_precision,omitempty"`
	TypeScale        *int            `json:"type_scale,omitempty"`
	TypeIntervalType *string         `json:"type_interval_type,omitempty"`
	TypeJson         *string         `json:"type_json,omitempty"`
	Comment          *string         `json:"comment,omitempty"`
	Nullable         *bool           `json:"nullable,omitempty"`
	PartitionIndex   *int            `json:"partition_index,omitempty"`
	Mask             *columnMaskWire `json:"mask,omitempty"`
}

func columnInfoToWire(v *ColumnInfo) *columnInfoWire {
	if v == nil {
		return nil
	}
	return &columnInfoWire{
		Name:             v.Name,
		TypeText:         v.TypeText,
		TypeName:         v.TypeName,
		Position:         v.Position,
		TypePrecision:    v.TypePrecision,
		TypeScale:        v.TypeScale,
		TypeIntervalType: v.TypeIntervalType,
		TypeJson:         v.TypeJson,
		Comment:          v.Comment,
		Nullable:         v.Nullable,
		PartitionIndex:   v.PartitionIndex,
		Mask:             columnMaskToWire(v.Mask),
	}
}

func columnInfoFromWire(w *columnInfoWire) *ColumnInfo {
	if w == nil {
		return nil
	}
	return &ColumnInfo{
		Name:             w.Name,
		TypeText:         w.TypeText,
		TypeName:         w.TypeName,
		Position:         w.Position,
		TypePrecision:    w.TypePrecision,
		TypeScale:        w.TypeScale,
		TypeIntervalType: w.TypeIntervalType,
		TypeJson:         w.TypeJson,
		Comment:          w.Comment,
		Nullable:         w.Nullable,
		PartitionIndex:   w.PartitionIndex,
		Mask:             columnMaskFromWire(w.Mask),
	}
}

type columnMaskWire struct {
	FunctionName     *string                      `json:"function_name,omitempty"`
	UsingColumnNames []string                     `json:"using_column_names,omitempty"`
	UsingArguments   []policyFunctionArgumentWire `json:"using_arguments,omitempty"`
}

func columnMaskToWire(v *ColumnMask) *columnMaskWire {
	if v == nil {
		return nil
	}
	return &columnMaskWire{
		FunctionName:     v.FunctionName,
		UsingColumnNames: v.UsingColumnNames,
		UsingArguments:   convertSlice(v.UsingArguments, policyFunctionArgumentToWire),
	}
}

func columnMaskFromWire(w *columnMaskWire) *ColumnMask {
	if w == nil {
		return nil
	}
	return &ColumnMask{
		FunctionName:     w.FunctionName,
		UsingColumnNames: w.UsingColumnNames,
		UsingArguments:   convertSlice(w.UsingArguments, policyFunctionArgumentFromWire),
	}
}

type complianceSecurityProfileWire struct {
	IsEnabled           *bool                `json:"is_enabled,omitempty"`
	ComplianceStandards []ComplianceStandard `json:"compliance_standards,omitempty"`
}

func complianceSecurityProfileToWire(v *ComplianceSecurityProfile) *complianceSecurityProfileWire {
	if v == nil {
		return nil
	}
	return &complianceSecurityProfileWire{
		IsEnabled:           v.IsEnabled,
		ComplianceStandards: v.ComplianceStandards,
	}
}

func complianceSecurityProfileFromWire(w *complianceSecurityProfileWire) *ComplianceSecurityProfile {
	if w == nil {
		return nil
	}
	return &ComplianceSecurityProfile{
		IsEnabled:           w.IsEnabled,
		ComplianceStandards: w.ComplianceStandards,
	}
}

type createCleanRoomAssetRequestWire struct {
	Asset *cleanRoomAssetWire `json:"asset,omitempty"`
}

func createCleanRoomAssetRequestToWire(v *CreateCleanRoomAssetRequest) *createCleanRoomAssetRequestWire {
	if v == nil {
		return nil
	}
	return &createCleanRoomAssetRequestWire{
		Asset: cleanRoomAssetToWire(v.Asset),
	}
}

func createCleanRoomAssetRequestFromWire(w *createCleanRoomAssetRequestWire) *CreateCleanRoomAssetRequest {
	if w == nil {
		return nil
	}
	return &CreateCleanRoomAssetRequest{
		Asset: cleanRoomAssetFromWire(w.Asset),
	}
}

type createCleanRoomAssetReviewRequestWire struct {
	CleanRoomName     *string                       `json:"clean_room_name,omitempty"`
	Name              *string                       `json:"name,omitempty"`
	AssetType         CleanRoomAsset_AssetType      `json:"asset_type,omitempty"`
	NotebookReview    *notebookVersionReviewWire    `json:"notebook_review,omitempty"`
	JarAnalysisReview *jarAnalysisVersionReviewWire `json:"jar_analysis_review,omitempty"`
}

func createCleanRoomAssetReviewRequestToWire(v *CreateCleanRoomAssetReviewRequest) *createCleanRoomAssetReviewRequestWire {
	if v == nil {
		return nil
	}
	return &createCleanRoomAssetReviewRequestWire{
		CleanRoomName:     v.CleanRoomName,
		Name:              v.Name,
		AssetType:         v.AssetType,
		NotebookReview:    notebookVersionReviewToWire(v.NotebookReview),
		JarAnalysisReview: jarAnalysisVersionReviewToWire(v.JarAnalysisReview),
	}
}

func createCleanRoomAssetReviewRequestFromWire(w *createCleanRoomAssetReviewRequestWire) *CreateCleanRoomAssetReviewRequest {
	if w == nil {
		return nil
	}
	return &CreateCleanRoomAssetReviewRequest{
		CleanRoomName:     w.CleanRoomName,
		Name:              w.Name,
		AssetType:         w.AssetType,
		NotebookReview:    notebookVersionReviewFromWire(w.NotebookReview),
		JarAnalysisReview: jarAnalysisVersionReviewFromWire(w.JarAnalysisReview),
	}
}

type createCleanRoomAssetReviewResponseWire struct {
	NotebookReviews        []cleanRoomNotebookReviewWire                     `json:"notebook_reviews,omitempty"`
	JarAnalysisReviews     []cleanRoomJarAnalysisReviewWire                  `json:"jar_analysis_reviews,omitempty"`
	NotebookReviewState    CleanRoomNotebookReview_NotebookReviewState       `json:"notebook_review_state,omitempty"`
	JarAnalysisReviewState CleanRoomJarAnalysisReview_JarAnalysisReviewState `json:"jar_analysis_review_state,omitempty"`
}

func createCleanRoomAssetReviewResponseToWire(v *CreateCleanRoomAssetReviewResponse) *createCleanRoomAssetReviewResponseWire {
	if v == nil {
		return nil
	}
	return &createCleanRoomAssetReviewResponseWire{
		NotebookReviews:        convertSlice(v.NotebookReviews, cleanRoomNotebookReviewToWire),
		JarAnalysisReviews:     convertSlice(v.JarAnalysisReviews, cleanRoomJarAnalysisReviewToWire),
		NotebookReviewState:    v.NotebookReviewState,
		JarAnalysisReviewState: v.JarAnalysisReviewState,
	}
}

func createCleanRoomAssetReviewResponseFromWire(w *createCleanRoomAssetReviewResponseWire) *CreateCleanRoomAssetReviewResponse {
	if w == nil {
		return nil
	}
	return &CreateCleanRoomAssetReviewResponse{
		NotebookReviews:        convertSlice(w.NotebookReviews, cleanRoomNotebookReviewFromWire),
		JarAnalysisReviews:     convertSlice(w.JarAnalysisReviews, cleanRoomJarAnalysisReviewFromWire),
		NotebookReviewState:    w.NotebookReviewState,
		JarAnalysisReviewState: w.JarAnalysisReviewState,
	}
}

type createCleanRoomAutoApprovalRuleRequestWire struct {
	AutoApprovalRule *cleanRoomAutoApprovalRuleWire `json:"auto_approval_rule,omitempty"`
}

func createCleanRoomAutoApprovalRuleRequestToWire(v *CreateCleanRoomAutoApprovalRuleRequest) *createCleanRoomAutoApprovalRuleRequestWire {
	if v == nil {
		return nil
	}
	return &createCleanRoomAutoApprovalRuleRequestWire{
		AutoApprovalRule: cleanRoomAutoApprovalRuleToWire(v.AutoApprovalRule),
	}
}

func createCleanRoomAutoApprovalRuleRequestFromWire(w *createCleanRoomAutoApprovalRuleRequestWire) *CreateCleanRoomAutoApprovalRuleRequest {
	if w == nil {
		return nil
	}
	return &CreateCleanRoomAutoApprovalRuleRequest{
		AutoApprovalRule: cleanRoomAutoApprovalRuleFromWire(w.AutoApprovalRule),
	}
}

type createCleanRoomOutputCatalogRequestWire struct {
	CleanRoomName *string                     `json:"clean_room_name,omitempty"`
	OutputCatalog *cleanRoomOutputCatalogWire `json:"output_catalog,omitempty"`
}

func createCleanRoomOutputCatalogRequestToWire(v *CreateCleanRoomOutputCatalogRequest) *createCleanRoomOutputCatalogRequestWire {
	if v == nil {
		return nil
	}
	return &createCleanRoomOutputCatalogRequestWire{
		CleanRoomName: v.CleanRoomName,
		OutputCatalog: cleanRoomOutputCatalogToWire(v.OutputCatalog),
	}
}

func createCleanRoomOutputCatalogRequestFromWire(w *createCleanRoomOutputCatalogRequestWire) *CreateCleanRoomOutputCatalogRequest {
	if w == nil {
		return nil
	}
	return &CreateCleanRoomOutputCatalogRequest{
		CleanRoomName: w.CleanRoomName,
		OutputCatalog: cleanRoomOutputCatalogFromWire(w.OutputCatalog),
	}
}

type createCleanRoomOutputCatalogResponseWire struct {
	OutputCatalog *cleanRoomOutputCatalogWire `json:"output_catalog,omitempty"`
}

func createCleanRoomOutputCatalogResponseToWire(v *CreateCleanRoomOutputCatalogResponse) *createCleanRoomOutputCatalogResponseWire {
	if v == nil {
		return nil
	}
	return &createCleanRoomOutputCatalogResponseWire{
		OutputCatalog: cleanRoomOutputCatalogToWire(v.OutputCatalog),
	}
}

func createCleanRoomOutputCatalogResponseFromWire(w *createCleanRoomOutputCatalogResponseWire) *CreateCleanRoomOutputCatalogResponse {
	if w == nil {
		return nil
	}
	return &CreateCleanRoomOutputCatalogResponse{
		OutputCatalog: cleanRoomOutputCatalogFromWire(w.OutputCatalog),
	}
}

type createCleanRoomRequestWire struct {
	CleanRoom *cleanRoomWire `json:"clean_room,omitempty"`
}

func createCleanRoomRequestToWire(v *CreateCleanRoomRequest) *createCleanRoomRequestWire {
	if v == nil {
		return nil
	}
	return &createCleanRoomRequestWire{
		CleanRoom: cleanRoomToWire(v.CleanRoom),
	}
}

func createCleanRoomRequestFromWire(w *createCleanRoomRequestWire) *CreateCleanRoomRequest {
	if w == nil {
		return nil
	}
	return &CreateCleanRoomRequest{
		CleanRoom: cleanRoomFromWire(w.CleanRoom),
	}
}

type deleteCleanRoomAssetRequestWire struct {
	CleanRoomName *string                  `json:"clean_room_name,omitempty"`
	AssetType     CleanRoomAsset_AssetType `json:"asset_type,omitempty"`
	Name          *string                  `json:"name,omitempty"`
}

func deleteCleanRoomAssetRequestToWire(v *DeleteCleanRoomAssetRequest) *deleteCleanRoomAssetRequestWire {
	if v == nil {
		return nil
	}
	return &deleteCleanRoomAssetRequestWire{
		CleanRoomName: v.CleanRoomName,
		AssetType:     v.AssetType,
		Name:          v.Name,
	}
}

func deleteCleanRoomAssetRequestFromWire(w *deleteCleanRoomAssetRequestWire) *DeleteCleanRoomAssetRequest {
	if w == nil {
		return nil
	}
	return &DeleteCleanRoomAssetRequest{
		CleanRoomName: w.CleanRoomName,
		AssetType:     w.AssetType,
		Name:          w.Name,
	}
}

type deleteCleanRoomAssetResponseWire struct {
}

func deleteCleanRoomAssetResponseToWire(v *DeleteCleanRoomAssetResponse) *deleteCleanRoomAssetResponseWire {
	if v == nil {
		return nil
	}
	return &deleteCleanRoomAssetResponseWire{}
}

func deleteCleanRoomAssetResponseFromWire(w *deleteCleanRoomAssetResponseWire) *DeleteCleanRoomAssetResponse {
	if w == nil {
		return nil
	}
	return &DeleteCleanRoomAssetResponse{}
}

type deleteCleanRoomAutoApprovalRuleRequestWire struct {
	CleanRoomName *string `json:"clean_room_name,omitempty"`
	RuleId        *string `json:"rule_id,omitempty"`
}

func deleteCleanRoomAutoApprovalRuleRequestToWire(v *DeleteCleanRoomAutoApprovalRuleRequest) *deleteCleanRoomAutoApprovalRuleRequestWire {
	if v == nil {
		return nil
	}
	return &deleteCleanRoomAutoApprovalRuleRequestWire{
		CleanRoomName: v.CleanRoomName,
		RuleId:        v.RuleId,
	}
}

func deleteCleanRoomAutoApprovalRuleRequestFromWire(w *deleteCleanRoomAutoApprovalRuleRequestWire) *DeleteCleanRoomAutoApprovalRuleRequest {
	if w == nil {
		return nil
	}
	return &DeleteCleanRoomAutoApprovalRuleRequest{
		CleanRoomName: w.CleanRoomName,
		RuleId:        w.RuleId,
	}
}

type deleteCleanRoomRequestWire struct {
	Name *string `json:"name,omitempty"`
}

func deleteCleanRoomRequestToWire(v *DeleteCleanRoomRequest) *deleteCleanRoomRequestWire {
	if v == nil {
		return nil
	}
	return &deleteCleanRoomRequestWire{
		Name: v.Name,
	}
}

func deleteCleanRoomRequestFromWire(w *deleteCleanRoomRequestWire) *DeleteCleanRoomRequest {
	if w == nil {
		return nil
	}
	return &DeleteCleanRoomRequest{
		Name: w.Name,
	}
}

type egressNetworkPolicyWire struct {
	InternetAccess *egressNetworkPolicy_InternetAccessPolicyWire `json:"internet_access,omitempty"`
}

func egressNetworkPolicyToWire(v *EgressNetworkPolicy) *egressNetworkPolicyWire {
	if v == nil {
		return nil
	}
	return &egressNetworkPolicyWire{
		InternetAccess: egressNetworkPolicy_InternetAccessPolicyToWire(v.InternetAccess),
	}
}

func egressNetworkPolicyFromWire(w *egressNetworkPolicyWire) *EgressNetworkPolicy {
	if w == nil {
		return nil
	}
	return &EgressNetworkPolicy{
		InternetAccess: egressNetworkPolicy_InternetAccessPolicyFromWire(w.InternetAccess),
	}
}

type egressNetworkPolicy_InternetAccessPolicyWire struct {
	RestrictionMode             EgressNetworkPolicy_InternetAccessPolicy_RestrictionMode           `json:"restriction_mode,omitempty"`
	AllowedInternetDestinations []egressNetworkPolicy_InternetAccessPolicy_InternetDestinationWire `json:"allowed_internet_destinations,omitempty"`
	AllowedStorageDestinations  []egressNetworkPolicy_InternetAccessPolicy_StorageDestinationWire  `json:"allowed_storage_destinations,omitempty"`
	LogOnlyMode                 *egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeWire          `json:"log_only_mode,omitempty"`
}

func egressNetworkPolicy_InternetAccessPolicyToWire(v *EgressNetworkPolicy_InternetAccessPolicy) *egressNetworkPolicy_InternetAccessPolicyWire {
	if v == nil {
		return nil
	}
	return &egressNetworkPolicy_InternetAccessPolicyWire{
		RestrictionMode:             v.RestrictionMode,
		AllowedInternetDestinations: convertSlice(v.AllowedInternetDestinations, egressNetworkPolicy_InternetAccessPolicy_InternetDestinationToWire),
		AllowedStorageDestinations:  convertSlice(v.AllowedStorageDestinations, egressNetworkPolicy_InternetAccessPolicy_StorageDestinationToWire),
		LogOnlyMode:                 egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeToWire(v.LogOnlyMode),
	}
}

func egressNetworkPolicy_InternetAccessPolicyFromWire(w *egressNetworkPolicy_InternetAccessPolicyWire) *EgressNetworkPolicy_InternetAccessPolicy {
	if w == nil {
		return nil
	}
	return &EgressNetworkPolicy_InternetAccessPolicy{
		RestrictionMode:             w.RestrictionMode,
		AllowedInternetDestinations: convertSlice(w.AllowedInternetDestinations, egressNetworkPolicy_InternetAccessPolicy_InternetDestinationFromWire),
		AllowedStorageDestinations:  convertSlice(w.AllowedStorageDestinations, egressNetworkPolicy_InternetAccessPolicy_StorageDestinationFromWire),
		LogOnlyMode:                 egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeFromWire(w.LogOnlyMode),
	}
}

type egressNetworkPolicy_InternetAccessPolicy_InternetDestinationWire struct {
	Destination *string                                                                                           `json:"destination,omitempty"`
	Type        EgressNetworkPolicy_InternetAccessPolicy_InternetDestination_InternetDestinationType              `json:"type,omitempty"`
	Protocol    EgressNetworkPolicy_InternetAccessPolicy_InternetDestination_InternetDestinationFilteringProtocol `json:"protocol,omitempty"`
}

func egressNetworkPolicy_InternetAccessPolicy_InternetDestinationToWire(v *EgressNetworkPolicy_InternetAccessPolicy_InternetDestination) *egressNetworkPolicy_InternetAccessPolicy_InternetDestinationWire {
	if v == nil {
		return nil
	}
	return &egressNetworkPolicy_InternetAccessPolicy_InternetDestinationWire{
		Destination: v.Destination,
		Type:        v.Type,
		Protocol:    v.Protocol,
	}
}

func egressNetworkPolicy_InternetAccessPolicy_InternetDestinationFromWire(w *egressNetworkPolicy_InternetAccessPolicy_InternetDestinationWire) *EgressNetworkPolicy_InternetAccessPolicy_InternetDestination {
	if w == nil {
		return nil
	}
	return &EgressNetworkPolicy_InternetAccessPolicy_InternetDestination{
		Destination: w.Destination,
		Type:        w.Type,
		Protocol:    w.Protocol,
	}
}

type egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeWire struct {
	LogOnlyModeType EgressNetworkPolicy_InternetAccessPolicy_LogOnlyMode_LogOnlyModeType `json:"log_only_mode_type,omitempty"`
	Workloads       []EgressNetworkPolicy_InternetAccessPolicy_LogOnlyMode_WorkloadType  `json:"workloads,omitempty"`
}

func egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeToWire(v *EgressNetworkPolicy_InternetAccessPolicy_LogOnlyMode) *egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeWire {
	if v == nil {
		return nil
	}
	return &egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeWire{
		LogOnlyModeType: v.LogOnlyModeType,
		Workloads:       v.Workloads,
	}
}

func egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeFromWire(w *egressNetworkPolicy_InternetAccessPolicy_LogOnlyModeWire) *EgressNetworkPolicy_InternetAccessPolicy_LogOnlyMode {
	if w == nil {
		return nil
	}
	return &EgressNetworkPolicy_InternetAccessPolicy_LogOnlyMode{
		LogOnlyModeType: w.LogOnlyModeType,
		Workloads:       w.Workloads,
	}
}

type egressNetworkPolicy_InternetAccessPolicy_StorageDestinationWire struct {
	BucketName          *string                                                                            `json:"bucket_name,omitempty"`
	Region              *string                                                                            `json:"region,omitempty"`
	Type                EgressNetworkPolicy_InternetAccessPolicy_StorageDestination_StorageDestinationType `json:"type,omitempty"`
	AzureStorageAccount *string                                                                            `json:"azure_storage_account,omitempty"`
	AllowedPaths        []string                                                                           `json:"allowed_paths,omitempty"`
	AzureStorageService *string                                                                            `json:"azure_storage_service,omitempty"`
	AzureDnsZone        *string                                                                            `json:"azure_dns_zone,omitempty"`
	AzureContainer      *string                                                                            `json:"azure_container,omitempty"`
}

func egressNetworkPolicy_InternetAccessPolicy_StorageDestinationToWire(v *EgressNetworkPolicy_InternetAccessPolicy_StorageDestination) *egressNetworkPolicy_InternetAccessPolicy_StorageDestinationWire {
	if v == nil {
		return nil
	}
	return &egressNetworkPolicy_InternetAccessPolicy_StorageDestinationWire{
		BucketName:          v.BucketName,
		Region:              v.Region,
		Type:                v.Type,
		AzureStorageAccount: v.AzureStorageAccount,
		AllowedPaths:        v.AllowedPaths,
		AzureStorageService: v.AzureStorageService,
		AzureDnsZone:        v.AzureDnsZone,
		AzureContainer:      v.AzureContainer,
	}
}

func egressNetworkPolicy_InternetAccessPolicy_StorageDestinationFromWire(w *egressNetworkPolicy_InternetAccessPolicy_StorageDestinationWire) *EgressNetworkPolicy_InternetAccessPolicy_StorageDestination {
	if w == nil {
		return nil
	}
	return &EgressNetworkPolicy_InternetAccessPolicy_StorageDestination{
		BucketName:          w.BucketName,
		Region:              w.Region,
		Type:                w.Type,
		AzureStorageAccount: w.AzureStorageAccount,
		AllowedPaths:        w.AllowedPaths,
		AzureStorageService: w.AzureStorageService,
		AzureDnsZone:        w.AzureDnsZone,
		AzureContainer:      w.AzureContainer,
	}
}

type getCleanRoomAssetRequestWire struct {
	CleanRoomName *string                  `json:"clean_room_name,omitempty"`
	AssetType     CleanRoomAsset_AssetType `json:"asset_type,omitempty"`
	Name          *string                  `json:"name,omitempty"`
}

func getCleanRoomAssetRequestToWire(v *GetCleanRoomAssetRequest) *getCleanRoomAssetRequestWire {
	if v == nil {
		return nil
	}
	return &getCleanRoomAssetRequestWire{
		CleanRoomName: v.CleanRoomName,
		AssetType:     v.AssetType,
		Name:          v.Name,
	}
}

func getCleanRoomAssetRequestFromWire(w *getCleanRoomAssetRequestWire) *GetCleanRoomAssetRequest {
	if w == nil {
		return nil
	}
	return &GetCleanRoomAssetRequest{
		CleanRoomName: w.CleanRoomName,
		AssetType:     w.AssetType,
		Name:          w.Name,
	}
}

type getCleanRoomAssetRevisionRequestWire struct {
	CleanRoomName *string                  `json:"clean_room_name,omitempty"`
	Name          *string                  `json:"name,omitempty"`
	AssetType     CleanRoomAsset_AssetType `json:"asset_type,omitempty"`
	Etag          *string                  `json:"etag,omitempty"`
}

func getCleanRoomAssetRevisionRequestToWire(v *GetCleanRoomAssetRevisionRequest) *getCleanRoomAssetRevisionRequestWire {
	if v == nil {
		return nil
	}
	return &getCleanRoomAssetRevisionRequestWire{
		CleanRoomName: v.CleanRoomName,
		Name:          v.Name,
		AssetType:     v.AssetType,
		Etag:          v.Etag,
	}
}

func getCleanRoomAssetRevisionRequestFromWire(w *getCleanRoomAssetRevisionRequestWire) *GetCleanRoomAssetRevisionRequest {
	if w == nil {
		return nil
	}
	return &GetCleanRoomAssetRevisionRequest{
		CleanRoomName: w.CleanRoomName,
		Name:          w.Name,
		AssetType:     w.AssetType,
		Etag:          w.Etag,
	}
}

type getCleanRoomAutoApprovalRuleRequestWire struct {
	CleanRoomName *string `json:"clean_room_name,omitempty"`
	RuleId        *string `json:"rule_id,omitempty"`
}

func getCleanRoomAutoApprovalRuleRequestToWire(v *GetCleanRoomAutoApprovalRuleRequest) *getCleanRoomAutoApprovalRuleRequestWire {
	if v == nil {
		return nil
	}
	return &getCleanRoomAutoApprovalRuleRequestWire{
		CleanRoomName: v.CleanRoomName,
		RuleId:        v.RuleId,
	}
}

func getCleanRoomAutoApprovalRuleRequestFromWire(w *getCleanRoomAutoApprovalRuleRequestWire) *GetCleanRoomAutoApprovalRuleRequest {
	if w == nil {
		return nil
	}
	return &GetCleanRoomAutoApprovalRuleRequest{
		CleanRoomName: w.CleanRoomName,
		RuleId:        w.RuleId,
	}
}

type getCleanRoomRequestWire struct {
	Name *string `json:"name,omitempty"`
}

func getCleanRoomRequestToWire(v *GetCleanRoomRequest) *getCleanRoomRequestWire {
	if v == nil {
		return nil
	}
	return &getCleanRoomRequestWire{
		Name: v.Name,
	}
}

func getCleanRoomRequestFromWire(w *getCleanRoomRequestWire) *GetCleanRoomRequest {
	if w == nil {
		return nil
	}
	return &GetCleanRoomRequest{
		Name: w.Name,
	}
}

type jarAnalysisVersionReviewWire struct {
	Etag        *string                                           `json:"etag,omitempty"`
	ReviewState CleanRoomJarAnalysisReview_JarAnalysisReviewState `json:"review_state,omitempty"`
	Comment     *string                                           `json:"comment,omitempty"`
}

func jarAnalysisVersionReviewToWire(v *JarAnalysisVersionReview) *jarAnalysisVersionReviewWire {
	if v == nil {
		return nil
	}
	return &jarAnalysisVersionReviewWire{
		Etag:        v.Etag,
		ReviewState: v.ReviewState,
		Comment:     v.Comment,
	}
}

func jarAnalysisVersionReviewFromWire(w *jarAnalysisVersionReviewWire) *JarAnalysisVersionReview {
	if w == nil {
		return nil
	}
	return &JarAnalysisVersionReview{
		Etag:        w.Etag,
		ReviewState: w.ReviewState,
		Comment:     w.Comment,
	}
}

type listCleanRoomAssetRevisionsRequestWire struct {
	CleanRoomName *string                  `json:"clean_room_name,omitempty"`
	Name          *string                  `json:"name,omitempty"`
	AssetType     CleanRoomAsset_AssetType `json:"asset_type,omitempty"`
	PageSize      *int                     `json:"page_size,omitempty"`
	PageToken     *string                  `json:"page_token,omitempty"`
}

func listCleanRoomAssetRevisionsRequestToWire(v *ListCleanRoomAssetRevisionsRequest) *listCleanRoomAssetRevisionsRequestWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomAssetRevisionsRequestWire{
		CleanRoomName: v.CleanRoomName,
		Name:          v.Name,
		AssetType:     v.AssetType,
		PageSize:      v.PageSize,
		PageToken:     v.PageToken,
	}
}

func listCleanRoomAssetRevisionsRequestFromWire(w *listCleanRoomAssetRevisionsRequestWire) *ListCleanRoomAssetRevisionsRequest {
	if w == nil {
		return nil
	}
	return &ListCleanRoomAssetRevisionsRequest{
		CleanRoomName: w.CleanRoomName,
		Name:          w.Name,
		AssetType:     w.AssetType,
		PageSize:      w.PageSize,
		PageToken:     w.PageToken,
	}
}

type listCleanRoomAssetRevisionsResponseWire struct {
	Revisions     []cleanRoomAssetWire `json:"revisions,omitempty"`
	NextPageToken *string              `json:"next_page_token,omitempty"`
}

func listCleanRoomAssetRevisionsResponseToWire(v *ListCleanRoomAssetRevisionsResponse) *listCleanRoomAssetRevisionsResponseWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomAssetRevisionsResponseWire{
		Revisions:     convertSlice(v.Revisions, cleanRoomAssetToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listCleanRoomAssetRevisionsResponseFromWire(w *listCleanRoomAssetRevisionsResponseWire) *ListCleanRoomAssetRevisionsResponse {
	if w == nil {
		return nil
	}
	return &ListCleanRoomAssetRevisionsResponse{
		Revisions:     convertSlice(w.Revisions, cleanRoomAssetFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type listCleanRoomAssetsRequestWire struct {
	CleanRoomName *string `json:"clean_room_name,omitempty"`
	PageToken     *string `json:"page_token,omitempty"`
}

func listCleanRoomAssetsRequestToWire(v *ListCleanRoomAssetsRequest) *listCleanRoomAssetsRequestWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomAssetsRequestWire{
		CleanRoomName: v.CleanRoomName,
		PageToken:     v.PageToken,
	}
}

func listCleanRoomAssetsRequestFromWire(w *listCleanRoomAssetsRequestWire) *ListCleanRoomAssetsRequest {
	if w == nil {
		return nil
	}
	return &ListCleanRoomAssetsRequest{
		CleanRoomName: w.CleanRoomName,
		PageToken:     w.PageToken,
	}
}

type listCleanRoomAssetsResponseWire struct {
	Assets        []cleanRoomAssetWire `json:"assets,omitempty"`
	NextPageToken *string              `json:"next_page_token,omitempty"`
}

func listCleanRoomAssetsResponseToWire(v *ListCleanRoomAssetsResponse) *listCleanRoomAssetsResponseWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomAssetsResponseWire{
		Assets:        convertSlice(v.Assets, cleanRoomAssetToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listCleanRoomAssetsResponseFromWire(w *listCleanRoomAssetsResponseWire) *ListCleanRoomAssetsResponse {
	if w == nil {
		return nil
	}
	return &ListCleanRoomAssetsResponse{
		Assets:        convertSlice(w.Assets, cleanRoomAssetFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type listCleanRoomAutoApprovalRulesRequestWire struct {
	CleanRoomName *string `json:"clean_room_name,omitempty"`
	PageSize      *int    `json:"page_size,omitempty"`
	PageToken     *string `json:"page_token,omitempty"`
}

func listCleanRoomAutoApprovalRulesRequestToWire(v *ListCleanRoomAutoApprovalRulesRequest) *listCleanRoomAutoApprovalRulesRequestWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomAutoApprovalRulesRequestWire{
		CleanRoomName: v.CleanRoomName,
		PageSize:      v.PageSize,
		PageToken:     v.PageToken,
	}
}

func listCleanRoomAutoApprovalRulesRequestFromWire(w *listCleanRoomAutoApprovalRulesRequestWire) *ListCleanRoomAutoApprovalRulesRequest {
	if w == nil {
		return nil
	}
	return &ListCleanRoomAutoApprovalRulesRequest{
		CleanRoomName: w.CleanRoomName,
		PageSize:      w.PageSize,
		PageToken:     w.PageToken,
	}
}

type listCleanRoomAutoApprovalRulesResponseWire struct {
	Rules         []cleanRoomAutoApprovalRuleWire `json:"rules,omitempty"`
	NextPageToken *string                         `json:"next_page_token,omitempty"`
}

func listCleanRoomAutoApprovalRulesResponseToWire(v *ListCleanRoomAutoApprovalRulesResponse) *listCleanRoomAutoApprovalRulesResponseWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomAutoApprovalRulesResponseWire{
		Rules:         convertSlice(v.Rules, cleanRoomAutoApprovalRuleToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listCleanRoomAutoApprovalRulesResponseFromWire(w *listCleanRoomAutoApprovalRulesResponseWire) *ListCleanRoomAutoApprovalRulesResponse {
	if w == nil {
		return nil
	}
	return &ListCleanRoomAutoApprovalRulesResponse{
		Rules:         convertSlice(w.Rules, cleanRoomAutoApprovalRuleFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type listCleanRoomNotebookTaskRunsRequestWire struct {
	CleanRoomName *string `json:"clean_room_name,omitempty"`
	NotebookName  *string `json:"notebook_name,omitempty"`
	PageSize      *int    `json:"page_size,omitempty"`
	PageToken     *string `json:"page_token,omitempty"`
}

func listCleanRoomNotebookTaskRunsRequestToWire(v *ListCleanRoomNotebookTaskRunsRequest) *listCleanRoomNotebookTaskRunsRequestWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomNotebookTaskRunsRequestWire{
		CleanRoomName: v.CleanRoomName,
		NotebookName:  v.NotebookName,
		PageSize:      v.PageSize,
		PageToken:     v.PageToken,
	}
}

func listCleanRoomNotebookTaskRunsRequestFromWire(w *listCleanRoomNotebookTaskRunsRequestWire) *ListCleanRoomNotebookTaskRunsRequest {
	if w == nil {
		return nil
	}
	return &ListCleanRoomNotebookTaskRunsRequest{
		CleanRoomName: w.CleanRoomName,
		NotebookName:  w.NotebookName,
		PageSize:      w.PageSize,
		PageToken:     w.PageToken,
	}
}

type listCleanRoomNotebookTaskRunsResponseWire struct {
	Runs          []cleanRoomNotebookTaskRunWire `json:"runs,omitempty"`
	NextPageToken *string                        `json:"next_page_token,omitempty"`
}

func listCleanRoomNotebookTaskRunsResponseToWire(v *ListCleanRoomNotebookTaskRunsResponse) *listCleanRoomNotebookTaskRunsResponseWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomNotebookTaskRunsResponseWire{
		Runs:          convertSlice(v.Runs, cleanRoomNotebookTaskRunToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listCleanRoomNotebookTaskRunsResponseFromWire(w *listCleanRoomNotebookTaskRunsResponseWire) *ListCleanRoomNotebookTaskRunsResponse {
	if w == nil {
		return nil
	}
	return &ListCleanRoomNotebookTaskRunsResponse{
		Runs:          convertSlice(w.Runs, cleanRoomNotebookTaskRunFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type listCleanRoomTaskRunsRequestWire struct {
	CleanRoomName *string           `json:"clean_room_name,omitempty"`
	Name          *string           `json:"name,omitempty"`
	TaskType      CleanRoomTaskType `json:"task_type,omitempty"`
	PageSize      *int              `json:"page_size,omitempty"`
	PageToken     *string           `json:"page_token,omitempty"`
}

func listCleanRoomTaskRunsRequestToWire(v *ListCleanRoomTaskRunsRequest) *listCleanRoomTaskRunsRequestWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomTaskRunsRequestWire{
		CleanRoomName: v.CleanRoomName,
		Name:          v.Name,
		TaskType:      v.TaskType,
		PageSize:      v.PageSize,
		PageToken:     v.PageToken,
	}
}

func listCleanRoomTaskRunsRequestFromWire(w *listCleanRoomTaskRunsRequestWire) *ListCleanRoomTaskRunsRequest {
	if w == nil {
		return nil
	}
	return &ListCleanRoomTaskRunsRequest{
		CleanRoomName: w.CleanRoomName,
		Name:          w.Name,
		TaskType:      w.TaskType,
		PageSize:      w.PageSize,
		PageToken:     w.PageToken,
	}
}

type listCleanRoomTaskRunsResponseWire struct {
	Runs          []cleanRoomTaskRunWire `json:"runs,omitempty"`
	NextPageToken *string                `json:"next_page_token,omitempty"`
}

func listCleanRoomTaskRunsResponseToWire(v *ListCleanRoomTaskRunsResponse) *listCleanRoomTaskRunsResponseWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomTaskRunsResponseWire{
		Runs:          convertSlice(v.Runs, cleanRoomTaskRunToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listCleanRoomTaskRunsResponseFromWire(w *listCleanRoomTaskRunsResponseWire) *ListCleanRoomTaskRunsResponse {
	if w == nil {
		return nil
	}
	return &ListCleanRoomTaskRunsResponse{
		Runs:          convertSlice(w.Runs, cleanRoomTaskRunFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type listCleanRoomsRequestWire struct {
	PageSize  *int    `json:"page_size,omitempty"`
	PageToken *string `json:"page_token,omitempty"`
}

func listCleanRoomsRequestToWire(v *ListCleanRoomsRequest) *listCleanRoomsRequestWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomsRequestWire{
		PageSize:  v.PageSize,
		PageToken: v.PageToken,
	}
}

func listCleanRoomsRequestFromWire(w *listCleanRoomsRequestWire) *ListCleanRoomsRequest {
	if w == nil {
		return nil
	}
	return &ListCleanRoomsRequest{
		PageSize:  w.PageSize,
		PageToken: w.PageToken,
	}
}

type listCleanRoomsResponseWire struct {
	CleanRooms    []cleanRoomWire `json:"clean_rooms,omitempty"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

func listCleanRoomsResponseToWire(v *ListCleanRoomsResponse) *listCleanRoomsResponseWire {
	if v == nil {
		return nil
	}
	return &listCleanRoomsResponseWire{
		CleanRooms:    convertSlice(v.CleanRooms, cleanRoomToWire),
		NextPageToken: v.NextPageToken,
	}
}

func listCleanRoomsResponseFromWire(w *listCleanRoomsResponseWire) *ListCleanRoomsResponse {
	if w == nil {
		return nil
	}
	return &ListCleanRoomsResponse{
		CleanRooms:    convertSlice(w.CleanRooms, cleanRoomFromWire),
		NextPageToken: w.NextPageToken,
	}
}

type notebookVersionReviewWire struct {
	Etag        *string                                     `json:"etag,omitempty"`
	ReviewState CleanRoomNotebookReview_NotebookReviewState `json:"review_state,omitempty"`
	Comment     *string                                     `json:"comment,omitempty"`
}

func notebookVersionReviewToWire(v *NotebookVersionReview) *notebookVersionReviewWire {
	if v == nil {
		return nil
	}
	return &notebookVersionReviewWire{
		Etag:        v.Etag,
		ReviewState: v.ReviewState,
		Comment:     v.Comment,
	}
}

func notebookVersionReviewFromWire(w *notebookVersionReviewWire) *NotebookVersionReview {
	if w == nil {
		return nil
	}
	return &NotebookVersionReview{
		Etag:        w.Etag,
		ReviewState: w.ReviewState,
		Comment:     w.Comment,
	}
}

type partitionSpecificationWire struct {
}

func partitionSpecificationToWire(v *PartitionSpecification) *partitionSpecificationWire {
	if v == nil {
		return nil
	}
	return &partitionSpecificationWire{}
}

func partitionSpecificationFromWire(w *partitionSpecificationWire) *PartitionSpecification {
	if w == nil {
		return nil
	}
	return &PartitionSpecification{}
}

type partitionSpecification_PartitionWire struct {
	Values []partitionSpecification_Partition_PartitionValueWire `json:"values,omitempty"`
}

func partitionSpecification_PartitionToWire(v *PartitionSpecification_Partition) *partitionSpecification_PartitionWire {
	if v == nil {
		return nil
	}
	return &partitionSpecification_PartitionWire{
		Values: convertSlice(v.Values, partitionSpecification_Partition_PartitionValueToWire),
	}
}

func partitionSpecification_PartitionFromWire(w *partitionSpecification_PartitionWire) *PartitionSpecification_Partition {
	if w == nil {
		return nil
	}
	return &PartitionSpecification_Partition{
		Values: convertSlice(w.Values, partitionSpecification_Partition_PartitionValueFromWire),
	}
}

type partitionSpecification_Partition_PartitionValueWire struct {
	Name                 *string                                                          `json:"name,omitempty"`
	Value                *string                                                          `json:"value,omitempty"`
	RecipientPropertyKey *string                                                          `json:"recipient_property_key,omitempty"`
	Op                   PartitionSpecification_Partition_PartitionValue_PartitionValueOp `json:"op,omitempty"`
}

func partitionSpecification_Partition_PartitionValueToWire(v *PartitionSpecification_Partition_PartitionValue) *partitionSpecification_Partition_PartitionValueWire {
	if v == nil {
		return nil
	}
	return &partitionSpecification_Partition_PartitionValueWire{
		Name:                 v.Name,
		Value:                v.Value,
		RecipientPropertyKey: v.RecipientPropertyKey,
		Op:                   v.Op,
	}
}

func partitionSpecification_Partition_PartitionValueFromWire(w *partitionSpecification_Partition_PartitionValueWire) *PartitionSpecification_Partition_PartitionValue {
	if w == nil {
		return nil
	}
	return &PartitionSpecification_Partition_PartitionValue{
		Name:                 w.Name,
		Value:                w.Value,
		RecipientPropertyKey: w.RecipientPropertyKey,
		Op:                   w.Op,
	}
}

type policyFunctionArgumentWire struct {
	Column   *string `json:"column,omitempty"`
	Constant *string `json:"constant,omitempty"`
}

func policyFunctionArgumentToWire(v *PolicyFunctionArgument) *policyFunctionArgumentWire {
	if v == nil {
		return nil
	}
	return &policyFunctionArgumentWire{
		Column:   v.Column,
		Constant: v.Constant,
	}
}

func policyFunctionArgumentFromWire(w *policyFunctionArgumentWire) *PolicyFunctionArgument {
	if w == nil {
		return nil
	}
	return &PolicyFunctionArgument{
		Column:   w.Column,
		Constant: w.Constant,
	}
}

type updateCleanRoomAssetRequestWire struct {
	CleanRoomName *string             `json:"clean_room_name,omitempty"`
	Asset         *cleanRoomAssetWire `json:"asset,omitempty"`
}

func updateCleanRoomAssetRequestToWire(v *UpdateCleanRoomAssetRequest) *updateCleanRoomAssetRequestWire {
	if v == nil {
		return nil
	}
	return &updateCleanRoomAssetRequestWire{
		CleanRoomName: v.CleanRoomName,
		Asset:         cleanRoomAssetToWire(v.Asset),
	}
}

func updateCleanRoomAssetRequestFromWire(w *updateCleanRoomAssetRequestWire) *UpdateCleanRoomAssetRequest {
	if w == nil {
		return nil
	}
	return &UpdateCleanRoomAssetRequest{
		CleanRoomName: w.CleanRoomName,
		Asset:         cleanRoomAssetFromWire(w.Asset),
	}
}

type updateCleanRoomAutoApprovalRuleRequestWire struct {
	AutoApprovalRule *cleanRoomAutoApprovalRuleWire `json:"auto_approval_rule,omitempty"`
}

func updateCleanRoomAutoApprovalRuleRequestToWire(v *UpdateCleanRoomAutoApprovalRuleRequest) *updateCleanRoomAutoApprovalRuleRequestWire {
	if v == nil {
		return nil
	}
	return &updateCleanRoomAutoApprovalRuleRequestWire{
		AutoApprovalRule: cleanRoomAutoApprovalRuleToWire(v.AutoApprovalRule),
	}
}

func updateCleanRoomAutoApprovalRuleRequestFromWire(w *updateCleanRoomAutoApprovalRuleRequestWire) *UpdateCleanRoomAutoApprovalRuleRequest {
	if w == nil {
		return nil
	}
	return &UpdateCleanRoomAutoApprovalRuleRequest{
		AutoApprovalRule: cleanRoomAutoApprovalRuleFromWire(w.AutoApprovalRule),
	}
}

type updateCleanRoomRequestWire struct {
	Name      *string        `json:"name,omitempty"`
	CleanRoom *cleanRoomWire `json:"clean_room,omitempty"`
}

func updateCleanRoomRequestToWire(v *UpdateCleanRoomRequest) *updateCleanRoomRequestWire {
	if v == nil {
		return nil
	}
	return &updateCleanRoomRequestWire{
		Name:      v.Name,
		CleanRoom: cleanRoomToWire(v.CleanRoom),
	}
}

func updateCleanRoomRequestFromWire(w *updateCleanRoomRequestWire) *UpdateCleanRoomRequest {
	if w == nil {
		return nil
	}
	return &UpdateCleanRoomRequest{
		Name:      w.Name,
		CleanRoom: cleanRoomFromWire(w.CleanRoom),
	}
}

func convertSlice[T, W any](s []T, conv func(*T) *W) []W {
	if s == nil {
		return nil
	}
	out := make([]W, len(s))
	for i := range s {
		out[i] = *conv(&s[i])
	}
	return out
}
