// Code generated by Databricks SDK Generator. DO NOT EDIT.

package environments

import (
	"encoding/json"
	"fmt"

	"github.com/databricks/sdk-go/core/types"
)

type BaseEnvironmentType string

const (
	BaseEnvironmentType_Unspecified BaseEnvironmentType = ""
	BaseEnvironmentType_Cpu         BaseEnvironmentType = "CPU"
	BaseEnvironmentType_Gpu         BaseEnvironmentType = "GPU"
)

type ErrorCode string

const (
	ErrorCode_Unspecified                      ErrorCode = ""
	ErrorCode_InternalError                    ErrorCode = "INTERNAL_ERROR"
	ErrorCode_TemporarilyUnavailable           ErrorCode = "TEMPORARILY_UNAVAILABLE"
	ErrorCode_IoError                          ErrorCode = "IO_ERROR"
	ErrorCode_BadRequest                       ErrorCode = "BAD_REQUEST"
	ErrorCode_ServiceUnderMaintenance          ErrorCode = "SERVICE_UNDER_MAINTENANCE"
	ErrorCode_WorkspaceTemporarilyUnavailable  ErrorCode = "WORKSPACE_TEMPORARILY_UNAVAILABLE"
	ErrorCode_DeadlineExceeded                 ErrorCode = "DEADLINE_EXCEEDED"
	ErrorCode_Cancelled                        ErrorCode = "CANCELLED"
	ErrorCode_ResourceExhausted                ErrorCode = "RESOURCE_EXHAUSTED"
	ErrorCode_Aborted                          ErrorCode = "ABORTED"
	ErrorCode_NotFound                         ErrorCode = "NOT_FOUND"
	ErrorCode_AlreadyExists                    ErrorCode = "ALREADY_EXISTS"
	ErrorCode_Unauthenticated                  ErrorCode = "UNAUTHENTICATED"
	ErrorCode_Unavailable                      ErrorCode = "UNAVAILABLE"
	ErrorCode_InvalidParameterValue            ErrorCode = "INVALID_PARAMETER_VALUE"
	ErrorCode_EndpointNotFound                 ErrorCode = "ENDPOINT_NOT_FOUND"
	ErrorCode_MalformedRequest                 ErrorCode = "MALFORMED_REQUEST"
	ErrorCode_InvalidState                     ErrorCode = "INVALID_STATE"
	ErrorCode_PermissionDenied                 ErrorCode = "PERMISSION_DENIED"
	ErrorCode_FeatureDisabled                  ErrorCode = "FEATURE_DISABLED"
	ErrorCode_CustomerUnauthorized             ErrorCode = "CUSTOMER_UNAUTHORIZED"
	ErrorCode_RequestLimitExceeded             ErrorCode = "REQUEST_LIMIT_EXCEEDED"
	ErrorCode_ResourceConflict                 ErrorCode = "RESOURCE_CONFLICT"
	ErrorCode_UnparseableHttpError             ErrorCode = "UNPARSEABLE_HTTP_ERROR"
	ErrorCode_NotImplemented                   ErrorCode = "NOT_IMPLEMENTED"
	ErrorCode_DataLoss                         ErrorCode = "DATA_LOSS"
	ErrorCode_InvalidStateTransition           ErrorCode = "INVALID_STATE_TRANSITION"
	ErrorCode_CouldNotAcquireLock              ErrorCode = "COULD_NOT_ACQUIRE_LOCK"
	ErrorCode_ResourceAlreadyExists            ErrorCode = "RESOURCE_ALREADY_EXISTS"
	ErrorCode_ResourceDoesNotExist             ErrorCode = "RESOURCE_DOES_NOT_EXIST"
	ErrorCode_QuotaExceeded                    ErrorCode = "QUOTA_EXCEEDED"
	ErrorCode_MaxBlockSizeExceeded             ErrorCode = "MAX_BLOCK_SIZE_EXCEEDED"
	ErrorCode_MaxReadSizeExceeded              ErrorCode = "MAX_READ_SIZE_EXCEEDED"
	ErrorCode_PartialDelete                    ErrorCode = "PARTIAL_DELETE"
	ErrorCode_MaxListSizeExceeded              ErrorCode = "MAX_LIST_SIZE_EXCEEDED"
	ErrorCode_DryRunFailed                     ErrorCode = "DRY_RUN_FAILED"
	ErrorCode_ResourceLimitExceeded            ErrorCode = "RESOURCE_LIMIT_EXCEEDED"
	ErrorCode_DirectoryNotEmpty                ErrorCode = "DIRECTORY_NOT_EMPTY"
	ErrorCode_DirectoryProtected               ErrorCode = "DIRECTORY_PROTECTED"
	ErrorCode_MaxNotebookSizeExceeded          ErrorCode = "MAX_NOTEBOOK_SIZE_EXCEEDED"
	ErrorCode_MaxChildNodeSizeExceeded         ErrorCode = "MAX_CHILD_NODE_SIZE_EXCEEDED"
	ErrorCode_SearchQueryTooLong               ErrorCode = "SEARCH_QUERY_TOO_LONG"
	ErrorCode_SearchQueryTooShort              ErrorCode = "SEARCH_QUERY_TOO_SHORT"
	ErrorCode_ManagedResourceGroupDoesNotExist ErrorCode = "MANAGED_RESOURCE_GROUP_DOES_NOT_EXIST"
	ErrorCode_PermissionNotPropagated          ErrorCode = "PERMISSION_NOT_PROPAGATED"
	ErrorCode_DeploymentTimeout                ErrorCode = "DEPLOYMENT_TIMEOUT"
	ErrorCode_GitConflict                      ErrorCode = "GIT_CONFLICT"
	ErrorCode_GitUnknownRef                    ErrorCode = "GIT_UNKNOWN_REF"
	ErrorCode_GitSensitiveTokenDetected        ErrorCode = "GIT_SENSITIVE_TOKEN_DETECTED"
	ErrorCode_GitUrlNotOnAllowList             ErrorCode = "GIT_URL_NOT_ON_ALLOW_LIST"
	ErrorCode_GitRemoteError                   ErrorCode = "GIT_REMOTE_ERROR"
	ErrorCode_ProjectsOperationTimeout         ErrorCode = "PROJECTS_OPERATION_TIMEOUT"
	ErrorCode_IpynbFileInRepo                  ErrorCode = "IPYNB_FILE_IN_REPO"
	ErrorCode_InsecurePartnerResponse          ErrorCode = "INSECURE_PARTNER_RESPONSE"
	ErrorCode_MalformedPartnerResponse         ErrorCode = "MALFORMED_PARTNER_RESPONSE"
	ErrorCode_MetastoreDoesNotExist            ErrorCode = "METASTORE_DOES_NOT_EXIST"
	ErrorCode_DacDoesNotExist                  ErrorCode = "DAC_DOES_NOT_EXIST"
	ErrorCode_CatalogDoesNotExist              ErrorCode = "CATALOG_DOES_NOT_EXIST"
	ErrorCode_SchemaDoesNotExist               ErrorCode = "SCHEMA_DOES_NOT_EXIST"
	ErrorCode_TableDoesNotExist                ErrorCode = "TABLE_DOES_NOT_EXIST"
	ErrorCode_ShareDoesNotExist                ErrorCode = "SHARE_DOES_NOT_EXIST"
	ErrorCode_RecipientDoesNotExist            ErrorCode = "RECIPIENT_DOES_NOT_EXIST"
	ErrorCode_StorageCredentialDoesNotExist    ErrorCode = "STORAGE_CREDENTIAL_DOES_NOT_EXIST"
	ErrorCode_ExternalLocationDoesNotExist     ErrorCode = "EXTERNAL_LOCATION_DOES_NOT_EXIST"
	ErrorCode_PrincipalDoesNotExist            ErrorCode = "PRINCIPAL_DOES_NOT_EXIST"
	ErrorCode_ProviderDoesNotExist             ErrorCode = "PROVIDER_DOES_NOT_EXIST"
	ErrorCode_MetastoreAlreadyExists           ErrorCode = "METASTORE_ALREADY_EXISTS"
	ErrorCode_DacAlreadyExists                 ErrorCode = "DAC_ALREADY_EXISTS"
	ErrorCode_CatalogAlreadyExists             ErrorCode = "CATALOG_ALREADY_EXISTS"
	ErrorCode_SchemaAlreadyExists              ErrorCode = "SCHEMA_ALREADY_EXISTS"
	ErrorCode_TableAlreadyExists               ErrorCode = "TABLE_ALREADY_EXISTS"
	ErrorCode_ShareAlreadyExists               ErrorCode = "SHARE_ALREADY_EXISTS"
	ErrorCode_RecipientAlreadyExists           ErrorCode = "RECIPIENT_ALREADY_EXISTS"
	ErrorCode_StorageCredentialAlreadyExists   ErrorCode = "STORAGE_CREDENTIAL_ALREADY_EXISTS"
	ErrorCode_ExternalLocationAlreadyExists    ErrorCode = "EXTERNAL_LOCATION_ALREADY_EXISTS"
	ErrorCode_ProviderAlreadyExists            ErrorCode = "PROVIDER_ALREADY_EXISTS"
	ErrorCode_CatalogNotEmpty                  ErrorCode = "CATALOG_NOT_EMPTY"
	ErrorCode_SchemaNotEmpty                   ErrorCode = "SCHEMA_NOT_EMPTY"
	ErrorCode_MetastoreNotEmpty                ErrorCode = "METASTORE_NOT_EMPTY"
	ErrorCode_ProviderShareNotAccessible       ErrorCode = "PROVIDER_SHARE_NOT_ACCESSIBLE"
)

type WorkspaceBaseEnvironmentCache_Status string

const (
	WorkspaceBaseEnvironmentCache_Status_Unspecified WorkspaceBaseEnvironmentCache_Status = ""
	WorkspaceBaseEnvironmentCache_Status_Pending     WorkspaceBaseEnvironmentCache_Status = "PENDING"
	WorkspaceBaseEnvironmentCache_Status_Created     WorkspaceBaseEnvironmentCache_Status = "CREATED"
	WorkspaceBaseEnvironmentCache_Status_Failed      WorkspaceBaseEnvironmentCache_Status = "FAILED"
	WorkspaceBaseEnvironmentCache_Status_Expired     WorkspaceBaseEnvironmentCache_Status = "EXPIRED"
	WorkspaceBaseEnvironmentCache_Status_Invalid     WorkspaceBaseEnvironmentCache_Status = "INVALID"
	WorkspaceBaseEnvironmentCache_Status_Refreshing  WorkspaceBaseEnvironmentCache_Status = "REFRESHING"
)

// Databricks Error that is returned by all Databricks APIs..
type ApiError struct {
	ErrorCode  ErrorCode
	Message    *string
	StackTrace *string
	Details    []json.RawMessage
}

// Request message for CreateWorkspaceBaseEnvironment..
type CreateWorkspaceBaseEnvironmentRequest struct {
	WorkspaceBaseEnvironment   *WorkspaceBaseEnvironment
	WorkspaceBaseEnvironmentId *string
	RequestId                  *string
}

// A singleton resource representing the default workspace base environment
// configuration. This resource contains the workspace base environments that
// are used as defaults for serverless notebooks and jobs in the workspace, for
// both CPU and GPU compute types..
type DefaultWorkspaceBaseEnvironment struct {
	Name                        *string
	CpuWorkspaceBaseEnvironment *string
	GpuWorkspaceBaseEnvironment *string
}

// Request message for DeleteWorkspaceBaseEnvironment..
type DeleteWorkspaceBaseEnvironmentRequest struct {
	Name *string
}

// Environment specification for a WorkspaceBaseEnvironment. Contains the
// environment version and dependencies configuration..
type EnvironmentSpec struct {
	Dependencies       []string
	EnvironmentVersion *string
}

// Request message for GetDefaultWorkspaceBaseEnvironment..
type GetDefaultWorkspaceBaseEnvironmentRequest struct {
	Name *string
}

// The request message for `GetOperation` method..
type GetOperationRequest struct {
	Name *string
}

// Request message for GetWorkspaceBaseEnvironment..
type GetWorkspaceBaseEnvironmentRequest struct {
	Name *string
}

// Request message for ListWorkspaceBaseEnvironments..
type ListWorkspaceBaseEnvironmentsRequest struct {
	PageSize  *int
	PageToken *string
}

// Response message for ListWorkspaceBaseEnvironments..
type ListWorkspaceBaseEnvironmentsResponse struct {
	WorkspaceBaseEnvironments []WorkspaceBaseEnvironment
	NextPageToken             *string
}

// This resource represents a long-running operation that is the result of a
// network API call..
type Operation struct {
	Name     *string
	Metadata json.RawMessage
	Done     *bool
	Error    *ApiError
	Response json.RawMessage
}

// Request message for RefreshWorkspaceBaseEnvironments..
type RefreshWorkspaceBaseEnvironmentRequest struct {
	Name *string
}

// Request message for UpdateDefaultWorkspaceBaseEnvironment..
type UpdateDefaultWorkspaceBaseEnvironmentRequest struct {
	DefaultWorkspaceBaseEnvironment *DefaultWorkspaceBaseEnvironment
	UpdateMask                      *string
}

// Request message for UpdateWorkspaceBaseEnvironment..
type UpdateWorkspaceBaseEnvironmentRequest struct {
	Name                     *string
	WorkspaceBaseEnvironment *WorkspaceBaseEnvironment
}

// A WorkspaceBaseEnvironment defines a workspace-level environment
// configuration consisting of an environment version and a list of
// dependencies..
type WorkspaceBaseEnvironment struct {
	Name                *string
	DisplayName         *string
	Filepath            *string
	CreatorUserId       *string
	CreateTime          *types.Time
	LastUpdatedUserId   *string
	UpdateTime          *types.Time
	Status              WorkspaceBaseEnvironmentCache_Status
	Message             *string
	IsDefault           *bool
	BaseEnvironmentType BaseEnvironmentType
	Spec                *EnvironmentSpec
}

// Materialized environment information for a WorkspaceBaseEnvironment..
type WorkspaceBaseEnvironmentCache struct {
}

// Metadata for the WorkspaceBaseEnvironment long-running operations. This
// message tracks the progress of the workspace base environment long-running
// process..
type WorkspaceBaseEnvironmentOperationMetadata struct {
}

// Error returns the LRO error code and message.
func (e *ApiError) Error() string {
	message := "unknown error"
	if e.Message != nil && *e.Message != "" {
		message = *e.Message
	}
	if e.ErrorCode != "" {
		return fmt.Sprintf("[%v] %s", e.ErrorCode, message)
	}
	return message
}
