// Code generated by Databricks SDK Generator. DO NOT EDIT.

package artifactallowlists

// The artifact type
type ArtifactType string

const (
	ArtifactType_Unspecified  ArtifactType = ""
	ArtifactType_InitScript   ArtifactType = "INIT_SCRIPT"
	ArtifactType_LibraryJar   ArtifactType = "LIBRARY_JAR"
	ArtifactType_LibraryMaven ArtifactType = "LIBRARY_MAVEN"
)

// The artifact pattern matching type
type ArtifactMatcher_MatchType string

const (
	ArtifactMatcher_MatchType_Unspecified ArtifactMatcher_MatchType = ""
	ArtifactMatcher_MatchType_PrefixMatch ArtifactMatcher_MatchType = "PREFIX_MATCH"
)

type ArtifactAllowlistInfo struct {
	// A list of allowed artifact match patterns.
	ArtifactMatchers []ArtifactMatcher
	// Unique identifier of parent metastore.
	MetastoreId *string
	// Username of the user who set the artifact allowlist.
	CreatedBy *string
	// Time at which this artifact allowlist was set, in epoch milliseconds.
	CreatedAt *int64
}

type ArtifactMatcher struct {
	// The artifact path or maven coordinate
	Artifact *string
	// The pattern matching type of the artifact
	MatchType ArtifactMatcher_MatchType
}

type GetArtifactAllowlistRequest struct {
	// The artifact type of the allowlist.
	ArtifactType ArtifactType
}

type SetArtifactAllowlistRequest struct {
	// The artifact type of the allowlist.
	ArtifactType ArtifactType
	// A list of allowed artifact match patterns.
	ArtifactMatchers []ArtifactMatcher
	// Unique identifier of parent metastore.
	MetastoreId *string
	// Username of the user who set the artifact allowlist.
	CreatedBy *string
	// Time at which this artifact allowlist was set, in epoch milliseconds.
	CreatedAt *int64
}
